### ISSUE TITLE
Resolving nested structured config of Lists with interpolation raises ValidationError

### ISSUE THREAD

**Issue by soldni** [omry/omegaconf#1005]
**Describe the bug**
This is a follow up to #847; OmegaConf raises a ValidationError when trying to use an interpolation inside a structured ListConfig. 

**To Reproduce**
```python
from omegaconf import OmegaConf, MISSING, II
from dataclasses import dataclass
from typing import List


@dataclass
class User:
    name: str = MISSING


@dataclass
class Config:
    user: User = User("John")
    admins: List[User] = "[${user}]"


cfg: Config = OmegaConf.structured(Config)
OmegaConf.resolve(cfg) # this  raises ValidationError
```

**Expected behavior**
I expect this resolution to not fail. 

**Additional context**
- [x] OmegaConf version: 2.2.3
- [x] Python version: 3.9
- [x] Operating system: macOS 12.5.1
- [x] Please provide a minimal repro

**Comment by binkjakub** [comment]
Are there any updates on whether this is planned to be fixed? I think it is important to handle nested interpolations.

**Comment by Jasha10** [comment]
I believe there is as typo in the original repro.
The interpolation should be `["${user}"]`, not `"[${user}]"`.
Here's the updated repro (also using `dataclasses.field` for python3.11 compatibility):
```python
from dataclasses import dataclass, field
from typing import List

from omegaconf import MISSING, OmegaConf


@dataclass
class User:
    name: str = MISSING


@dataclass
class Config:
    user: User = User("John")
    admins: List[User] = field(default_factory=lambda: ["${user}"])


cfg: Config = OmegaConf.structured(Config)
OmegaConf.resolve(cfg)  # this  raises ValidationError
```

**Comment by Jasha10** [comment]
@binkjakub the OmegaConf team is currently volunteer-run and lacking in bandwidth. I cannot make a promise as to when this will be fixed.
