### ISSUE TITLE
Add `is_unresolved` to OmegaConf

### ISSUE THREAD

**Issue by kunaltyagi** [omry/omegaconf#1081]
**Is your feature request related to a problem? Please describe.**
I'd like to know when the value would be an indirect call and when it's a direct input

**Describe the solution you'd like**
There are other helper functions like `is_missing` and `is_unresolved` would be able to allow custom logic around detecting the source of the value

**Describe alternatives you've considered**
None

**Comment by omry** [comment]
What is the difference between your new proposed function and [is_interpolation](https://omegaconf.readthedocs.io/en/2.3_branch/usage.html#omegaconf-is-interpolation) ?

**Comment by omry** [comment]
I am starting to see what you are asking for.
OmegaConf does not remember that OmegaConf.resolve have been called.
This process is simply replacing interpolations with the resolved value, but after its called - new interpolations can be assigned again:
```python
cfg = OmegaConf.create({"a": "${b}", "b" : 10})
OmegaConf.resolve(cfg)
// resolved?
cfg.a = "${b}"
// not resolved again?
```

I don't think this something worth adding.
@Jasha10, @odelalleau, @shagunsodhani: any comments?

**Comment by kunaltyagi** [comment]
Like I said, if OmegaConf can return the is_resolved status, then I can choose to use a wrapper function to access values instead of using the dot notation or accessor functions.

```py
get_val = lambda conf, var: conf._get_node(var)._value()

if not OmegaConf.is_resolved(config): OmegaConf.resolve(config)

# now we use only get_val and nothing else
print(config.debug)  # Don't allow during code reviews
print(get_val(config, "debug"))  # Safe for leaf nodes
```

It's not perfect. A slightly better way would be to add an option to the getter so we don't have to rely on a `get_val` (`config.get("debug", interpolate=False)` ), but even then we need `is_resolved` to resolve the config once

In our usecase, we don't control the loading of the config, that is handled by either a test stub or a library. And depending on what the test is testing, we want to resolve or not resolve the config to keep a consistent behavior

**Comment by Jasha10** [comment]
```python
>>> OmegaConf.register_new_resolver('my_resolver', lambda: '${foo}')
>>> cfg = OmegaConf.create("a: ${my_resolver:}")
>>> cfg['a']
'${foo}'
```

So option 2 is to change behavior so that `cfg['a']` returns the string `"\${foo}"` instead of `"${foo}"`?

**Comment by kunaltyagi** [comment]
Can both of these be done?

Maybe we can have an API something like the following
```py
OmegaConf.resolve(cfg, depth:int|None)
# depth=0...INT_MAX: No future resolutions: 0: infinite recursion, 1...INT_MAX for recursion depth
# depth = None, same as calling depth=1 and then unlock_interpolation

OmegaConf.lock_interpolation(cfg)  # all ${x} now treated as strings
OmegaConf.unlock_interpolation(cfg)  # back to default behavior
```

**Comment by odelalleau** [comment]
> Brainstorming - here's an idea that may or may not make sense: A third option (in addition to the two proposed by @odelalleau above) is to make interpolation resolution recursive: dereferencing node `cfg.a` would check if the string returned by an interpolation is again an interpolation. If it is, recursively dereference again.

The issue with making interpolation resolution recursive is that it wouldn't be possible to have `${` in a string option, which some users may need.

> Also, clients wouldn't need to worry about "unescaping" strings returned by `__getitem__` (as would be the case if we implement option 2?).

To be clear, there would be no need to un-escape strings in Option 2. You could have `cfg["x"] == cfg.x == "${y}"`. The un-escaping would be done on access (like it currently happens e.g. with `OmegaConf.create({"x": r"\${y}"}).x`).

**Comment by Jasha10** [comment]
> it wouldn't be possible to have `${` in a string option, which some users may need.

Good point.

> To be clear, there would be no need to un-escape strings in Option 2. You could have `cfg["x"] == cfg.x == "${y}"`. The un-escaping would be done under the hood on access (like it currently happens e.g. with `OmegaConf.create({"x": r"\${y}"}).x`).

This would require the node to own extra metadata for keeping track of whether the string needs to be unescaped when `__getitem__`/`__getattr__` is called, right?

**Comment by odelalleau** [comment]
> > To be clear, there would be no need to un-escape strings in Option 2. You could have `cfg["x"] == cfg.x == "${y}"`. The un-escaping would be done under the hood on access (like it currently happens e.g. with `OmegaConf.create({"x": r"\${y}"}).x`).
> 
> This would require the node to own extra metadata for keeping track of whether the string needs to be unescaped when `__getitem__`/`__getattr__` is called, right?

No, this mechanism already exists and is part of the resolution of interpolations.

**Comment by omry** [comment]
> Like I said, if OmegaConf can return the is_resolved status, then I can choose to use a wrapper function to access values instead of using the dot notation or accessor functions.

1. Why do you need to use private API to access the config fields in the first place?
2. Why can't you just resolve the config when you load it if you want to always avoid the interpolation resolution later?

**Comment by kunaltyagi** [comment]
> 2. Why can't you just resolve the config when you load it if you want to always avoid the interpolation resolution later?

1. We don't want issues like this. (code snippet by @Jasha10 )
```py
>>> os.environ["FOO"] = "${b}"
>>> cfg = OmegaConf.create("{a: '${oc.env:FOO}', b: 123}")
>>> cfg.a
'${b}'
>>> OmegaConf.resolve(cfg)
>>> cfg.a
123
```
2. Because we don't load the config ourselves. We are using two middle-ware library, one of which already calls resolve. In order to stay correct, we need to know if the config is already resolved in our mock (else we'd need to monkey patch or detect the middleware and do weird stuff)

Re: point 1, that's a consequence of the fact that the public api **always** calls resolve while accessing

**Comment by omry** [comment]
I feel like my solution is addressing your problem. Feel free to followup here further.
