### ISSUE TITLE
Request support for anltr 4.11.1

### ISSUE THREAD

**Issue by DManowitz** [omry/omegaconf#1091]
I realize that this has been brought up a few times before (e.g., #1000), but I currently have fugue installed in an environment with omegaconf, and I would like to be able to upgrade it, and it and dependent packages all have versions compatible with antlr-python-runtime 4.11.1.  So, I'd like to request a version of omegaconf that uses this version of antlr-python-runtime.

**Comment by astrojuanlu** [comment]
xref #1114

**Comment by DManowitz** [comment]
Thank you for your work on vendoring the antlr dependency.  However, do you have any idea when a new version with this capability will be released?

**Comment by Jasha10** [comment]
Hi @DManowitz, have you tried `pip install omegaconf>=2.4.0.dev2`?

**Comment by DManowitz** [comment]
@Jasha10 I'm mostly using conda for my package management right now, so I haven't noticed that yet.  I'll consider that, although I'd prefer a conda install.
