### ISSUE TITLE
Default Not Being Set

### ISSUE THREAD

**Issue by timolson** [omry/omegaconf#1110]
First, I love OmegaConf so far.  It's _almost_ perfect...

**Describe the bug**
My config has a nested `dict[...,list[Child]]` structure, where nested elements have defaults, but the defaults are NOT being set.

**To Reproduce**
```python
from dataclasses import dataclass
from omegaconf import OmegaConf


@dataclass
class ParentConfig:
    children: dict[str, list['ChildConfig']]


@dataclass
class ChildConfig:
    required: int
    optional: int = 3


schema = OmegaConf.structured(ParentConfig)
conf = OmegaConf.create({'children': {'items': [{'required': 'r'}]}}) # NOTE: wrong type for 'required'
print(OmegaConf.merge(schema, conf)
```

Outputs:
```{'children': {'items': [{'required': 'r'}]}}```

**Expected behavior**
The `ChildConfig` item should have `optional=3`

Notice that I used the wrong type for required, passing a string instead of an int.  This suggests that the typing system is not recursing properly.  Perhaps only one level of nesting is hardcoded?

**Additional context**
- [X] OmegaConf version: 2.3.0
- [X] Python version: 3.11.4
- [X] Operating system: Linux
- [X] Please provide a minimal repro

**Comment by odelalleau** [comment]
Thanks, at first sight it looks this may be related to #1058

**Comment by timolson** [comment]
Yes, agreed, it's likely the same issue.

If I remove the list and just have a dict of objects, it works.

**Comment by omry** [comment]
Thanks for the report. Closing as a duplicate.
