### ISSUE TITLE
Question : why we need "???" and what's for ?

### ISSUE THREAD

**Issue by HuangChiEn** [omry/omegaconf#1128]
As the title, it's hard to think the reason that we need "???" placeholder. 
When you define a config to control the behavior of program, the argument should have the determined value ( that's the meaning of configuration ). If we can set an argument with "???" placeholder and the value still cannot be determined finally.
The argument itself may be not necessary to define in the config, isn't it?
( As we can expect, if we try to access "???", it will raise MissConfig error, this behavior potentially not permit the argument to be non-determined.

**Comment by Jasha10** [comment]
The `???` placeholder represents a "Missing" value. It's usually used when you know that some data is needed, but you don't yet know what the correct value should be. The idea is that you can later fill in the missing value with real data.

**Comment by HuangChiEn** [comment]
> The `???` placeholder represents a "Missing" value. It's usually used when you know that some data is needed, but you don't yet know what the correct value should be. The idea is that you can later fill in the missing value with real data.

Ok, sounds rational, TKS for your explanation ~
