### ISSUE TITLE
Consider inheriting from collections.Mapping and Sequence

### ISSUE THREAD

**Issue by omry** [omry/omegaconf#114]

**Comment by omry** [comment]
Landed with typing.MutableMapping and typing.MutableSequence which are just as good.

**Comment by poweic** [comment]
Hi @omry,

I was trying to use `isinstance` and [`collections.abc.Mapping`](https://docs.python.org/3/library/collections.abc.html) to check if an OmegaConf variable is a dictionary-like object but both `isinstance(cfg, collections.abc.Mapping)` and `isinstance(cfg, collections.abc.MutableMapping)` returned `False`.

Other packages like [attrdict](https://pypi.org/project/attrdict/) and [dotmap](https://pypi.org/project/dotmap/) inherit from `collections.abc.Mapping`.

Have you considered inheriting from `collections.abc.Mapping`? Thanks

```python
In [1]: import omegaconf

In [2]: import collections

In [3]: isinstance(omegaconf.OmegaConf.create({"x": 10}), collections.abc.Mapping)
Out[3]: False

In [4]: isinstance(omegaconf.OmegaConf.create({"x": 10}), collections.abc.MutableMapping)
Out[4]: False

In [5]: from attrdict import AttrDict

In [6]: isinstance(AttrDict(x), collections.abc.Mapping)
Out[6]: True

In [7]: isinstance(AttrDict(x), collections.abc.MutableMapping)
Out[7]: True

In [8]: from dotmap import DotMap

In [9]: isinstance(DotMap({"x": 10}), collections.abc.Mapping)
Out[9]: True

In [10]: isinstance(DotMap({"x": 10}), collections.abc.MutableMapping)
Out[10]: True

In [11]: AttrDict?
Init signature: AttrDict(*args, **kwargs)
Docstring:      A dict that implements MutableAttr.
File:           ~/anaconda3/envs/xxx/lib/python3.7/site-packages/attrdict/dictionary.py
Type:           ABCMeta
Subclasses:

In [12]: DotMap?
Init signature: DotMap(*args, **kwargs)
Docstring:      Dictionary that remembers insertion order
File:           ~/anaconda3/envs/xxx/lib/python3.7/site-packages/dotmap/__init__.py
Type:           ABCMeta
Subclasses:

In [13]: omegaconf.dictconfig.DictConfig?
Init signature: omegaconf.dictconfig.DictConfig(content, parent=None)
Docstring:      <no docstring>
File:           ~/anaconda3/envs/xxx/lib/python3.7/site-packages/omegaconf/dictconfig.py
Type:           type
Subclasses:
```

**Comment by omry** [comment]
@poweic, did you test on 2.0?

**Comment by poweic** [comment]
My bad :sweat_smile: Not sure why I got an older version of omegaconf (1.4.1) with freshly installed `hydra-core`. But they works in 2.0! Thanks!! :smiley:

**Comment by omry** [comment]
Hydra 0.11 is not compatible with OmegaConf 1.4. 
Check the 1.0 pre release if you want to use Hydra and OmegaConf 2.0.
