### ISSUE TITLE
Node interpolation not working

### ISSUE THREAD

**Issue by Qolorerr** [omry/omegaconf#1145]
I trying to use node interpolation in the config file but it doesn't work. It doesn't work on the basic examples too, like:
`
cfg = oc.create({'test': 255, 'tes2': '${test}'})
print(cfg)
`
And I get
`
{'test': 255, 'tes2': '${test}'}
`
What am I doing wrong?

**Comment by Qolorerr** [comment]
OmegaConf.resolve(cfg) fixed issue

**Comment by odelalleau** [comment]
You can also look at the `OmegaConf.{to_object,to_container,to_yaml}` functions that provide various options to export the config with / without resolution of interpolations.

**Comment by omry** [comment]
Interpolation is evaluated lazily on access.
As mentioned, you can call resolve to eagerly update all interpolations to their resolved values.
