### ISSUE TITLE
oc:env interpolation w/default resolves to empty string when env var is missing

### ISSUE THREAD

**Issue by EtcetFelix** [omry/omegaconf#1179]
**Describe the bug**
When using the built in interpolation resolver `oc:env` with a default value, the resolution is an empty string when the environment variable doesn't exist or is empty. 

**To Reproduce**
I've attached the files to reproduce the issue below but here is the code:
```
from dataclasses import dataclass, field
from omegaconf import II, OmegaConf

@dataclass
class EnvironmentSettings:
    host: str = field(default=II("oc.env:REDIS_HOST,default_host"))

config = OmegaConf.structured(EnvironmentSettings)

print(config)
print(config.host)	# Should be 'default_host', but is empty string
print("done")
```
REDIS_HOST is not set in the environment on purpose.

Zip file with everything related to reproduce the issue:
[testingOcEnvEmptyDefaultBug.zip](https://github.com/user-attachments/files/15945515/testingOcEnvEmptyDefaultBug.zip)

**Expected behavior**
According to the [documentation](https://omegaconf.readthedocs.io/en/2.3_branch/custom_resolvers.html#oc-env): 
> You can specify a default value to use in case the environment variable is not set.

The expectation is that the output of the interpolation resolution is the default value. In this case, the output of config.host should be the string 'default_host'

**Additional context**
- [ ] OmegaConf version: 2.3.0
- [ ] Python version: Python 3.11.9
- [ ] Operating system: Ubuntu 22.04.4 LTS
- [ ] Please provide a minimal repro: [testingOcEnvEmptyDefaultBug.zip](https://github.com/user-attachments/files/15945515/testingOcEnvEmptyDefaultBug.zip)

**Comment by omry** [comment]
I can't reproduce this on master or on 2.3:
```
~/PycharmProjects/omegaconf (2.3_branch)
$ python test.py
{'host': '${oc.env:REDIS_HOST,default_host}'}
default_host
done
(hydra)
omry@GameStation MINGW64 ~/PycharmProjects/omegaconf (2.3_branch)
$ ipython
Python 3.11.9 | packaged by Anaconda, Inc. | (main, Apr 19 2024, 16:40:41) [MSC v.1916 64 bit (AMD64)]
Type 'copyright', 'credits' or 'license' for more information
IPython 8.26.0 -- An enhanced Interactive Python. Type '?' for help.

In [1]: import omegaconf

In [2]: omegaconf.__version__
Out[2]: '2.3.0'
```

**Comment by omry** [comment]
Please double check your environment variables. If you are still not getting the desired response I suggest you do some debugging. As far as I can tell `oc.env` is working as intended.
It is also well tested and the [test file](https://github.com/omry/omegaconf/blob/master/tests/interpolation/built_in_resolvers/test_oc_env.py) have not been touched for two years.

**Comment by omry** [comment]
(changed close type)

**Comment by omry** [comment]
Please double check your environment variables. If you are still not getting the desired response I suggest you do some debugging. As far as I can tell `oc.env` is working as intended.
It is also well tested and the [test file](https://github.com/omry/omegaconf/blob/master/tests/interpolation/built_in_resolvers/test_oc_env.py) have not been touched for two years.
