### ISSUE TITLE
Hash value for dictconfig is inconsistent between Python 3.7+ and older versions

### ISSUE THREAD

**Issue by matsui528** [omry/omegaconf#148]
Hi,
Thanks for this wonderful library! Hydra+omegaconf helps me quite a lot.

I found that a hash value for dictconfig is inconsistent in some cases. Is this an expected behaviour or a bug? 

Suppose I have two identical dictionaries with the different insertion order: `d1={"a": 123, "b": 456}` and `d2 = {"b": 456, "a": 123}`. When printing a dictionary, the order of the insertion is preserved in Python 3.7+, meaning that `str(d1) != str(d2)`. In older Python, the order is ignored and the items are automatically sorted, which means that the string is same: `str(d1) == str(d2)`.

Let me create dictconfig instances from them: `dc1 = OmegaConf.create(d1)` and `dc2 = OmegaConf.create(d2)`. As a hash value of dictconfig is computed based on `str()`, `hash(dc1) != hash(dc2)` for Python 3.7+ and `hash(dc1) == hash(dc2)` for older Python.

This results in a different behaviour for Python 3.7+ and older Python in some cases. For example, if I use `dc1` as the key of a dictionary: `a = {dc1: "xxx", dc2: "yyy"}`, two items are kept in Python 3.7, but only one remains in Python 3.5.

I guess either behaviour is ok, but would it be consistent between different versions of Python3.X?

Thanks!

Reference: ["the insertion-order preservation nature of dict objects has been declared to be an official part of the Python language spec."](https://docs.python.org/3/whatsnew/3.7.html)

Test code:
```python
from omegaconf import OmegaConf

# Identical dictionaries with the different insertion order
d1 = {"a": 123, "b": 456}
d2 = {"b": 456, "a": 123}

dc1 = OmegaConf.create(d1)
dc2 = OmegaConf.create(d2)

print(str(d1), str(d2))
# Python 3.5: {'b': 456, 'a': 123} {'b': 456, 'a': 123}  <- Sorted
# Python 3.7: {'a': 123, 'b': 456} {'b': 456, 'a': 123}  <- Not sorted

print(hash(dc1), hash(dc2))
# Python 3.5: -7197075476224411740 -7197075476224411740   <- same
# Python 3.7: 9040302285363809012 -3745572629213257466    <- different

a = {dc1: "xxx", dc2: "yyy"}
print(a)
# The result is different. Which is an expected behavior?
# Python 3.5: {{'b': 456, 'a': 123}: 'yyy'}
# Python 3.7: {{'a': 123, 'b': 456}: 'xxx', {'b': 456, 'a': 123}: 'yyy'}
```

**Comment by omry** [comment]
Hi,
Thanks! I am really happy to see both Hydra and OmegaConf getting some adoption (especially from the research community, which I am a part of :) ).
What you are seeing is probably expected, if a bit unfortunate.
Currently the hash of OmegaConf objects is computed as the hash of the string, as you can see by looking [here](https://github.com/omry/omegaconf/blob/master/omegaconf/dictconfig.py#L305-L306).

So, the string representation is determining the the hash.
As to why we get a different order in different versions of Python:
As of Python 3.7, and probably even for 3.6 as well (please check), Python is standard dictionaries iteration order is the same as insertion order.
Since OmegaConf (and Hydra) are both in the way to drop Python older than 3.6 in the next version (including 3.5!) this is probably not (unless you see differences with 3.6 as well).

Please consider dropping 3.5. if you wish to continue using it you will not be able to upgrade to the next major version of both Hydra and OmegaConf.
You can learn about the amazing things coming to OmegaConf in the release notes of the [2.0.0 release candidate](https://github.com/omry/omegaconf/releases/tag/2.0.0rc6).

**Comment by omry** [comment]
I have to ask though, what is the use case for using the config object as a key in a dictionary? I never thought someone might do that :)

**Comment by matsui528** [comment]
> Since OmegaConf (and Hydra) are both in the way to drop Python older than 3.6 in the next version (including 3.5!) this is probably not (unless you see differences with 3.6 as well).

Good to know that! Ok, then the difference of the version is not the problem :)

> I have to ask though, what is the use case for using the config object as a key in a dictionary? I never thought someone might do that :)

Let's say I have a parameter set `p=OmegaConf.create({"abc": 123, "xyz": 456, ...})` and try to compute something by `out = f(p)`. I might want to maintain results from several parameter sets by a dictionary, e.g:
```python
outs = {}
for p in p_set:
    outs[p] = f(p)
```
I simplified my problem so it may be a weird example though :)

Note that I cannot do this by the default dictionary because it's not hashable (I need to convert a dict to a namedtuple or something). 

Anyway, thanks for your quick reply, and I'm looking forward to the new release!

**Comment by omry** [comment]
I see.
With Hydra, the generated config is stored for you automatically into the output directory (under .hydra, along with a few other things). this is happening when you are doing a parameter sweep, which sounds close to what you are describing here.
not sure this is addressing your use case.

Can you give more details about what is the purpose of this loop in your program?

**Comment by matsui528** [comment]
I'm benchmarking several search algorithms on several datasets. The parameter sweep by Hydra is done for algos and datasets: `python benchmark.py algo=algo1,algo2,algo3 dataset=dataset1,datset2,dataset3`.  I guess this is a typical use case for Hydra, and indeed it works pretty well :)

For each algo, there are several parameters I'd like to evaluate with, e.g., in `algo1.yaml`:
```
name: algo1
runtime_params:
- {"num_of_trees": 12, "threshold": 0.3, ...}
- {"num_of_trees": 15, "threshold": 0.3, ...}
```

In `benchmark.py`, given `dataset` and `algo`, what I want to try is:
```python
search_results = {}
for param in cfg.algo.runtime_params:
    search_results[param] = run_algo1(param, dataset)   # Takes time. Want to compute here and store results

# Here, use search_results for further analysis, drawing a figure, etc
```
That's all.

Here, suppose one accidentally writes a wrong description on `algo1.yaml` (This can be happened because it is manually written by users)
```
name: algo1
runtime_params:
- {"num_of_trees": 12, "threshold": 0.3, ...}
- {"threshold": 0.3, "num_of_trees": 12, ...}   # mistake. a duplicated row with the different insertion order
- {"num_of_trees": 15, "threshold": 0.3, ...}
```
Then, `search_results` will have two items in Python 3.5, but three items in Python 3.7. I first thought that this is a bug, so reported it on Github issue.

Actually this is not a big deal. For example, an ugly but straightforward approach is to convert a dictconfig to a namedtuple with a sort by its key, then it works for any Python versions:
```
search_results[dict_to_namedtuple(param)] = run_algo1(param, dataset)
```
I just wanted to make sure this behavior of the `hash` on dictconig is expected or not. Now everything is clear to me :)

**Comment by omry** [comment]
Thanks for the additional details.
This is something you can probably use Hydra sweeps.
```
conf/
  model/
    ..
  dataset/
    ..
  algo/
    algo1.ymal
    algo2.yaml
```

Now you can sweep over algos as well:
```
python foo.py -m  model=m1,m2 algo=algo1,algo2
```

For visualization, you can store checkpoints in the sweep directory and run a second command that will visualize al the results.
```
python visualize -m dir/multirun/.../DATE/DAY/
```

You mentioned users. which lead me to think you either have or are starting to have a framework. Hydra offers some facilities for frameworks to share configs with user code.


Closing this for now.
If you want to chat about Hydra or OmegaConf please join the chat (link at the Hydra README/website).
