### ISSUE TITLE
Integer as dict key

### ISSUE THREAD

**Issue by noklam** [omry/omegaconf#149]
I get this error when using int as dictkey in config, is this being blocked for specific reason? If I remove the assert statement I can run successfully.

I encounter this error when I use facebookresearch/hydra, which depends on omegaconf

```
from omegaconf import OmegaConf
conf = OmegaConf.create( dict([(1, 2), (3, 4)]))
print(conf.pretty())  
```

> 
> File "C:\ProgramData\Anaconda3\lib\site-packages\omegaconf\dictconfig.py", line 35, in __setitem__
>     assert isinstance(key, str)
> AssertionError

**Comment by omry** [comment]
As you have noted, integers are not supported as dictionary keys in OmegaConf.
This is something I will consider for the after 2.0.0. which already ads a lot of new surface area.
As a temporary solution, do not use int keys (you convert them to string somehow, maybe like:
```yaml
1_: foo
2_: bar
```
the keys should now be strings.
Definitely look at 2.0.0 (docs), it adds support for Enum as keys which may be even better for you. don't try 2.0.0 with stable Hydra, they are incompatible (Integration is still work in progress).

**Comment by noklam** [comment]
@omry Thanks for the quick response! Ok I guess I will try convert it into string for now.

**Comment by Jasha10** [comment]
I've submitted PR #454 related to this issue.
Before moving further with test coverage, here is a design question:
will we want to support other primitive key types besides int?
Currently (before the above PR), DictConfig keys can be one of
`[Any, str, Enum, None]`
and DictConfig values can be one of
`[Any, str, float, bool, int, None, StructuredConfig]`.

**Comment by omry** [comment]
Let's move the discussion to the PR.

**Comment by Jasha10** [comment]
I think this can be closed now.

**Comment by omry** [comment]
Yup.
