### ISSUE TITLE
[Feature Request] overriding by a dictionary

### ISSUE THREAD

**Issue by matsui528** [omry/omegaconf#168]
It would be nice to enable overriding a variable by a dictionary.
```
$ python app.py xxx={abc:123}
```
(Discussion with @omry from the Zulip group)

**Comment by omry** [comment]
This is now implemented in Hydra.
support for pure OmegaConf is plausible but low pri.

Are you using Hydra or OmegaConf directly?

**Comment by matsui528** [comment]
Thank you! I'm using Hydra. Support for Hydra is good enough for me.

**Comment by omry** [comment]
Take a look at [this](https://hydra.cc/docs/advanced/override_grammar/basic#dictionaries).

In Hydra 1.0.1 the semantics is going to change from assign to merge ([link](https://hydra.cc/docs/next/advanced/override_grammar/basic#dictionaries)).
