### ISSUE TITLE
Set default value when environment variable is missing

### ISSUE THREAD

**Issue by kfollesdal** [omry/omegaconf#170]
It would be nice to be able to set a default value in yaml file for
environment variable interpolation when a variable is missing. 

E.g syntax can be `${env:ENVIROMENT_VARIABLE,default_value}`

`a: ${env:VALUE_A,1}`

if `VALUE_A `do not exist give `1`

**Comment by omry** [comment]
Thanks, I have been wanting to do this.
The motivation for allowing multiple arguments for resolvers was exactly this use case, but I never got to add this.
