### ISSUE TITLE
Fallback when merg config with enviroment variabels

### ISSUE THREAD

**Issue by kfollesdal** [omry/omegaconf#172]
A nice feature for merging configs with environment variables and an environment variable is missing it to fallback to next value in merge order.

Take a look at the following example and suppose VALUE_A does not exist.

```
from omegaconf import OmegaConf

yaml = "a: 12"

yaml_env = "a: ${env:VALUE_A}"

config = OmegaConf.create(yaml)
config_env = OmegaConf.create(yaml_env)
configm = OmegaConf.merge(config, config_env)
print(configm.a)
```

You will get the following error: 
`KeyError: "Environment variable 'VALUE_A' not found"`

It would be nice if you get `12 `in this example.

**Comment by omry** [comment]
This is unlikely to be implemented, it does not line up with the rest of OmegaConf's merge behavior.

The support for default value for env that you are proposing in the other issue + PR is not enough?

**Comment by omry** [comment]
once #100 is done, along with #171, you will be able to do this:
```
default_env: foo
yaml_env = "a: ${env:NAME,${default_env}}"
```

**Comment by kfollesdal** [comment]
#171 is enough for me. 

Was just thinking that this was a natural and "expected" behaviour of the merge method. And understand if you do not think it fit into your merge scheme. 

The idea was that then you can have one yaml file with default values. And another yaml file with the same keys defined as environment variables. Then it is possible to use them independent of each other or you can merge them if you want to override some of the default values with environment variables. 

With #100 and #171 I expect you need to have different key names? Do not expect this will work: 

yaml1
`a: 12`

yaml_env
`a: ${env: NAME, ${a}}`

So if you mere yaml1 and yaml_env 12 is the default value. 

But this is not a problem was just a thought, #171 solves the problem.

**Comment by omry** [comment]
The merge is more of an overlay of configs.
In this case, adding support for resolvers here would mean they will need to return some kind of a special "don't know" return value to allow for it (and such a return value is not something that exists in OmegaConf.
resolvers right now are very basic in OmegaConf, and does not support many things you might want.

I am closing this one because #171 will address it.
