### ISSUE TITLE
Clear resolver catch method

### ISSUE THREAD

**Issue by kfollesdal** [omry/omegaconf#175]
Method to clear resolver catch today is: `OmegaConf.set_cache(cfg, defaultdict(dict, {}))`

Propose to make this into an own method: `OmegaConf.clear_cache(cfg)`

**Comment by omry** [comment]
sounds good. be sure to add a test.
I think this is too much of a corner use case to warrant docs update.

**Comment by kfollesdal** [comment]
Ok. Make it into an own pull request or just add it to #171?

**Comment by omry** [comment]
Add to #171, this is a small enough addition.
