### ISSUE TITLE
[Feature Request] Array Element Overrides from dotlist via getitem syntax 

### ISSUE THREAD

**Issue by apsdehal** [omry/omegaconf#179]
Currently, OmegaConf supports overriding as `training_parameters.lr_steps.1=500` for overriding a specific element of an array. This is not intuitive and we should support proper getitem syntax for array element overrides. 

`training_parameters.lr_steps[1]=500` should be supported.

**Comment by omry** [comment]
Blocked on #445

**Comment by Jasha10** [comment]
If I am not mistaken, this issue is resolved:
```python
>>> training_parameters = OmegaConf.create({"lr_steps": [1000,800,100,75]})
>>> training_parameters
{'lr_steps': [1000, 800, 100, 75]}
>>> training_parameters.lr_steps[1]
800
>>> training_parameters.lr_steps[1] = 500
>>> training_parameters
{'lr_steps': [1000, 500, 100, 75]}
```

**Comment by odelalleau** [comment]
> If I am not mistaken, this issue is resolved:

No, that's because the way it's phrased can be misleading. `training_parameters.lr_steps[1]=500` is not meant to be read as a Python statement, but as a command line override as would be used in Hydra for instance. In OmegaConf, it's actually more about the `select` / `update` functions that assume the key is dot-separated (search for `split(".")` in the code)

**Comment by omry** [comment]
```
In [3]: cfg = OmegaConf.create({"a" : {"b": [1,2,3]}})

In [4]: cfg
Out[4]: {'a': {'b': [1, 2, 3]}}

In [5]: OmegaConf.select(cfg, "")
Out[5]: {'a': {'b': [1, 2, 3]}}

In [6]: OmegaConf.select(cfg, "a")
Out[6]: {'b': [1, 2, 3]}

In [7]: OmegaConf.select(cfg, "a.b")
Out[7]: [1, 2, 3]

In [8]: OmegaConf.select(cfg, "a.b.0")
Out[8]: 1
```

What would be good is to support:
```
OmegaConf.select(cfg, "a.b[0]")
```

In fact, we can support it for regular dict access as well:
```
OmegaConf.select(cfg, "[a][b][0]")
```

**Comment by omry** [comment]
This should probably cover the interpolation syntax as well, so it can be too much for 2.1:
```yaml
list:
 - a
 - b 
item0: ${list.0} # a, current syntax
item1: ${list[1]} # b, new syntax
```

**Comment by dasturge** [comment]
Hi, I found this issue when trying to figure out how to do just that.  Can you point me to documentation I missed or, can I request documentation of this feature?

**Comment by Jasha10** [comment]
Hi @dasturge,

Take a look at the docs on [Config node interpolation](https://omegaconf.readthedocs.io/en/2.2_branch/usage.html#config-node-interpolation).

Also, there are usage examples in the [`OmegaConf.select` docs](https://omegaconf.readthedocs.io/en/2.2_branch/usage.html#omegaconf-select) and the [`OmegaConf.update` docs](https://omegaconf.readthedocs.io/en/2.2_branch/usage.html#omegaconf-update).
