### ISSUE TITLE
[Feature Request] Debug mode for merge 

### ISSUE THREAD

**Issue by apsdehal** [omry/omegaconf#180]
Sometimes, we need to know what exactly was overridden for debugging purposes and can save a lot of headaches. 

I can think of two possible solutions here:

`OmegaConf.merge(a, b, debug=True)`. This will have to implemented for other functions such as `merge_from_dot_list` as well and is more useful for my usecase.

Otherwise, you can add logging debug statements which I don't think you use anywhere as of now.

**Comment by omry** [comment]
I think I want to support is blame mode.
Each node can know where it came from (a specific file? the command line? a dotlist? a direct modification in the code?), and a git-blame-like visualization can tell where each line in the config originated from.

**Comment by omry** [comment]
Opened #182 which will address the underlying problem.
