### ISSUE TITLE
Assert configuration is a subset of a template configuration

### ISSUE THREAD

**Issue by asafmanor** [omry/omegaconf#183]
It is sometimes useful to make sure that a certain config is a subset of a given template configuration,
e.g. when passing arguments through the command line.

That way you make sure no keys are "getting lost" and the application is misconfigured.
Assuming a template conf:
```yaml
foo:
  bar: True
  bar2: True
```
I would want something like this:
```py
cfg = OmegaConf.create({"foo": {"bar": 100}})
cfg.assert_subset(template)
cfg = OmegaConf.create({"foo": {"bar1": 100, "bar2": 101}})
cfg.assert_subset(template). # Fails on assertion / KeyError
cfg = OmegaConf.create({"foo2": {"bar": 100, "bar2": 101}})
cfg.assert_subset(template). # Fails on assertion / KeyError
```

Another option would be:
```py
OmegaConf.assert_subset(cfg, template)
```

I've implemented a simple recursion that takes care of DictConfig, and if you see this feature as needed I'll be happy to discuss and then PR.

**Comment by omry** [comment]
Hi Assaf,
The next version of OmegaConf will support this in a better way that what you probably implemented.

Pre release nodes:
https://github.com/omry/omegaconf/releases/tag/2.0.0rc6

Intro in primary doc:
https://omegaconf.readthedocs.io/en/latest/usage.html#from-structured-config

Full docs:
https://omegaconf.readthedocs.io/en/latest/structured_config.

There is a release candidate if you want to try (currently omegaconf-2.0.0-rc16).
This version is not compatible with the stable Hydra yet (I am guessing you are using Hydra as well).
There is a version in master that introduces this support which you can try.

Check the tutorial for it here:
https://hydra.cc/docs/next/tutorials/structured_config/basic

Closing for now, but happy to continue discussing here or in the chat.
