### ISSUE TITLE
[bug] OmegaConf.merge should respect interpolations

### ISSUE THREAD

**Issue by apsdehal** [omry/omegaconf#184]
```py
from omegaconf import OmegaConf

first = OmegaConf.create({
    "a": {
        "aa": 1,
        "ab": 2
    },
    "b": "${a}"
})

second = OmegaConf.create({
    "b": {
        "ba": 1,
        "bb": 2
    }
})

third = OmegaConf.merge(first, second)


expected = OmegaConf.create({
   "a": {
        "aa": 1,
        "ab": 2
   },
   "b": { 
        "aa": 1,
        "ab": 2,
        "ba": 1,
        "bb": 2
    }       
})
assert third == expected
# throws AssertionError
```

Version: 2.0.0rc16

**Comment by omry** [comment]
Thanks, I will take a look before 2.0 is released.

By the way, you can compare to primitive maps directly:
```python
assert third == {
   "a": {
        "aa": 1,
        "ab": 2
   },
   "b": { 
        "aa": 1,
        "ab": 2,
        "ba": 1,
        "bb": 2
    }       
}
```

**Comment by omry** [comment]
What you expect is not what should happen.
Interpolation is a pointer.
You should end up with:

```python
{
    "a": {
        "aa": 1,
        "ab": 2,
        "ba": 1,
        "bb": 2
    },
    "b": "${a}"
}
```

Which is equivalent but not the same.

**Comment by omry** [comment]
However, interpolations are not writethrough.
by the same logic, you would expect:
```python
cfg = OmegaConf.create({
  "a":  10,
  "b" : "${a}"
})

cfg.b = 20
```
To result in 
```yaml
a: 20
b: ${a}
```

But this is useful: you can achieve the same result by just modifying a directly.

instead, this results in:
```yaml
a: 10
b: 20
```

This is a conscience choice, and I don't want to make node interpolation inconsistent with this choice.

**Comment by apsdehal** [comment]
Regardless of pointer interpretation I would still expect Merge to respect interpolations. For the example you gave, I would say it is more of the choice on your end on how you would like to handle it in OmegaConf. Nevertheless, I have been thinking of interpolations as pass by value rather than pass by reference.
