### ISSUE TITLE
Variables not resolved when accessing through iterator

### ISSUE THREAD

**Issue by binshengliu** [omry/omegaconf#203]
When accessing `ListConfig` through the iterator, the variables are not resolved. A similar issue is #21 regarding DictConfig.

config.yaml:
```
var1: 1
var2: 2
var3:
  - ${var1}
  - ${var2}
```

test.py:
```
import hydra

from omegaconf import DictConfig


@hydra.main('config.yaml')
def main(cfg: DictConfig) -> None:
    print(cfg.var1)
    print(cfg.var2)
    print(cfg.var3)
    print([x for x in cfg.var3])
    print([cfg.var3[i] for i in range(len(cfg.var3))])
    print(next(iter(cfg.var3)))

    return


if __name__ == '__main__':
    main()
```

Output:
```
$ python test.py
1
2
['${var1}', '${var2}']
['${var1}', '${var2}']
[1, 2]
${var1}
```

Hydra version: facebookresearch/hydra@b9df40a2
Omegaconf version: 4c5be9a

**Comment by omry** [comment]
Thanks for reporting. I have a fix coming for this one.

**Comment by omry** [comment]
@binshengliu , Thanks again.
if you can, please join the Hydra chat. I would like learn more about what you are doing with Hydra and OmegaConf.

**Comment by binshengliu** [comment]
No worries. Also thank you for making such amazing tools. I don't know what Hydra chat is but I'd like to share how I use it here.

I've been fiddling with neural networks and I was looking for tools to keep track of different hyperparameter settings. Another reason I need such a tool is our devices have different computing capacities so I need to switch configurations when I'm using different machines. Then I came across hydra from [pytorch-lightning](https://pytorch-lightning.readthedocs.io/en/latest/hyperparameters.html#hyperparameter-optimization) documentation and read [your article](https://medium.com/pytorch/hydra-a-fresh-look-at-configuration-for-machine-learning-projects-50583186b710). 

I only used the basic features. The most important one to me is [config groups](https://hydra.cc/docs/tutorial/config_groups). I use it to keep track of different hyperparameter combinations. With hydra, what I do is simply, `python src/train.py conf=setting1`. The flexibility provided by [variable expansion](https://hydra.cc/docs/patterns/specializing_config/#defaults0dataset_defaults1model) is another bonus I found later. It makes the config less verbose. With a line `data_file: data/${architecture}_${seq_len}` in the top-level `config.yaml` I can change the data path according to the variables in a particular config group. Variable overriding is also quite handy and intuitive. I might also use the multirun feature to do cross-validation with my other projects.

That's basically how I use it so far. It satisfies my needs quiet well. Thank you again for your work!

**Comment by omry** [comment]
This is awesome!

That lightning referral to Hydra is appreciated, but Hydra is not a Hyper parameter optimization library.
However, there are two optimization plugins for Hydra in master:
- [Ax sweepr](https://hydra.cc/docs/next/plugins/ax_sweeper/)
- [NeverGrad sweeper](https://hydra.cc/docs/next/plugins/nevergrad_sweeper/) 

Both should be installed from master from now, but looks you are already using Hydra from master so give them a shot!
(Both are still going to change a bit before we finally release them, but are working.

There is another plugin you might find useful, which is the [Joblib launcher](https://hydra.cc/docs/next/plugins/joblib_launcher/). With it you can multirun in parallel locally (potentially using multiple GPUs on the same host).

An even more important new feature of Hydra 1.0 (master), is structured configs.
Take a look at the new tutorial [here](https://hydra.cc/docs/next/intro).
The tutorial is still work in progress and needs some refinement, but it's already pretty good.

Finally, There is a Ray based plugin in the works which will allow you to launch to AWS directly from the command line!

[This](https://hydra-framework.zulipchat.com/) is the chat I was talking about, feel free to join if you have any questions :)

You can also check out the [FLOSS weekly interview](https://twit.tv/shows/floss-weekly/episodes/573?autostart=false) I gave about Hydra last week!

One request for you:
Please tell your friends about Hydra, it's still a new projects and it can use awareness.
If you use Twitter, you can also twit about it (mention [Hydra_Framework](https://twitter.com/Hydra_Framework))

**Comment by binshengliu** [comment]
I realized hydra was not for optimization very soon but that was a happy accident for me. Those plugins also look really interesting and fit the research work. Thanks for the info!

For sure I'm more than happy to recommend it to my friends. Actually I've already been recommending it to people. It absolutely relieves our minds from repetitive routines and optimizes our research workflow. Thanks again!
