### ISSUE TITLE
Thank you!

### ISSUE THREAD

**Issue by kumuji** [omry/omegaconf#207]
I extremely like your package. And I use it a lot.
It is awesome and I think is a bit underrated.
Thank you for your work!

**Comment by omry** [comment]
Thanks a lot!
I see that you are an ML and Robotics engineer, you will be happy to hear that I started working on OmegaConf after running into some configuration problems working on robotics and ML at Facebook AI.

Another thing that came out of this work is [Hydra](http://hydra.cc) which is something you should definitely check out.

A few interesting links about Hydra:
- [Blog post](http://bit.ly/2Sdq2B3) on the PyTorch Medium channel
- A recent [interview](https://twit.tv/shows/floss-weekly/episodes/573) I had at FLOSS weekly about Hydra.

Can you join the [Hydra chat](https://hydra-framework.zulipchat.com/#)? I would love to learn about your work and how you are using OmegaConf.
