### ISSUE TITLE
Include base/requirements.txt and optionally tests in source dist

### ISSUE THREAD

**Issue by hadim** [omry/omegaconf#221]
Any ETA for releasing the 2.0?

**Comment by omry** [comment]
Hi Hadim,
Hydra is closely related to OmegaConf and 2.0 will likely be released with Hydra 1.0.
In the mean time I recommend that you install release candidates, they are getting pretty mature.

Are you using OmegaConf without Hydra?

**Comment by omry** [comment]
Gotcha.
You should probably look at Hydra, but regardless - for now feel free to install RC versions.
keep in mind that they are still may still be some minor incompatibilities between different RC versions that are not documented in the release notes. if you see any regression let me know.

**Comment by hadim** [comment]
Also, I am trying to conda build a package for the 2.0rc: https://github.com/conda-forge/omegaconf-feedstock/pull/3

The build fails because the `requirements.txt` file is not in the pypi source archive. Would that be possible to include that file or hard code deps in the `setup.py` file?

This issue does not only impact the conda recipe but also people who wants to build omegaconf from the pypi source archive.

**Comment by omry** [comment]
sure, can you send a PR that adds it?

**Comment by omry** [comment]
@hadim, it would actually be awesome to also include the tests in the source dist (but not in the wheel).
I have never done anything like this, do you happen to know how to do it?

**Comment by omry** [comment]
And, out of curiosity:
Why do you need 2.0? are you using Structured configs? anything else?

**Comment by hadim** [comment]
2.0 is soon to be released so I prefer to use this one in my code rather than 1.4.

I don't think we can include tests without also including it into the wheel.

**Comment by hadim** [comment]
I was wrong about the tests folder so it's possible.

**Comment by hadim** [comment]
See https://github.com/omry/omegaconf/pull/223
