### ISSUE TITLE
pop and del should throw in struct mode

### ISSUE THREAD

**Issue by omry** [omry/omegaconf#225]
This is a behavior change. DictConfig pop and del should not be permitted in struct mode (and in structured mode) because it's inconsistent with the the expected behavior of classes.

**Comment by cuichenx** [comment]
What is the correct way to delete a key in DictConfig then?
`del conf.some_key` works if you know the key name, but what if the key is specified by a variable?

**Comment by odelalleau** [comment]
> What is the correct way to delete a key in DictConfig then? `del conf.some_key` works if you know the key name, but what if the key is specified by a variable?

`del cfg[variable_name]`

**Comment by cuichenx** [comment]
> `del cfg[variable_name]`

Doesn't work for me. I get `omegaconf.errors.ConfigTypeError: DictConfig in struct mode does not support deletion`
Unless this works in a newer version? I'm using 2.2.3

**Comment by odelalleau** [comment]
> > `del cfg[variable_name]`
> 
> Doesn't work for me. I get `omegaconf.errors.ConfigTypeError: DictConfig in struct mode does not support deletion` Unless this works in a newer version? I'm using 2.2.3

Any removal / addition will fail in struct mode, you can use the `open_dict` context manager to make it work (see https://omegaconf.readthedocs.io/en/2.3_branch/usage.html#struct-flag for an example of usage when adding a new key, but the same applies for deletion).

**Comment by cuichenx** [comment]
Thanks for your reply.
I also found that cfg.__delattr__(key) works
