### ISSUE TITLE
null as default value for env interpolation

### ISSUE THREAD

**Issue by apsdehal** [omry/omegaconf#230]
If I pass null as default value to env interpolation, as with yaml, I expect to get the value as None, but I get the string 'null'.

```py
from omegaconf import OmegaConf
a = OmegaConf.create({"a": "${env:a, null}"})
print(a.a) # prints "null"
```

If this is a not a bug, how can I specify None as the default value?

**Comment by omry** [comment]
smells like a bug to me.

**Comment by omry** [comment]
PR welcome :)

**Comment by omry** [comment]
The [docs](https://omegaconf.readthedocs.io/en/latest/usage.html#custom-interpolations) does not specify the type of arguments and currently they are strings.
```python
OmegaConf.register_resolver("concat", lambda x,y: print(type(x), type(y), x+y))
cfg = OmegaConf.create({"foo" : "${concat:10,foo}"})
<class 'str'> <class 'str'> 10foo
cfg.foo
```
There is a case to make for converting the strings to a primitive or even with yaml_decode but the parsing now is very primitive and I really don't want to support something as sophisticated as yaml there.

Let me think about it, I am leaning toward keeping things as is. giving arbitrary types may not be simpler for the receiving code. for example the registered resolver will need to handle a plathora of types based on what the user is passing in which will probably make most cases more complicated, only to simplify one case (yours).

**Comment by apsdehal** [comment]
A current workaround for this is to pass empty string as default parameter. This will give empty string back. Then `if` will evaluate it directly to false.

**Comment by omry** [comment]
default value where? code? config?

**Comment by apsdehal** [comment]
`OmegaConf.create({"a": "${env:a,}"})`

**Comment by omry** [comment]
Okay, I can consider adding a flag to register resolver that will cause the variables to be converted to primitives for 2.1.

**Comment by omry** [comment]
blocked on #445
