### ISSUE TITLE
What is the license

### ISSUE THREAD

**Issue by thbaz** [omry/omegaconf#249]
What would be the license of this repository?
- GNU General Public License v3.0
- MIT License
- BSD 3-Clause "New" or "Revised" License
- Apache License 2.0

**Comment by omry** [comment]
BSD 3-Clause License, thanks for drawing my attention to the license file.
I updated it.

**Comment by omry** [comment]
I am toying with the idea of switching to MIT, which I grown to like more - but for now I am keeping BSD (3 clause).
