### ISSUE TITLE
[Feature Request/Question] Save Interpolated Value, Select .. where

### ISSUE THREAD

**Issue by sbyrakur** [omry/omegaconf#256]
1)  Let's say I have a yaml like this:
> user: ${env:USER}

And, I want to save the config to a file with the interpolated values. 

Loading a file:
> user = OmegaConf.load('user.yaml')

Writing a file (without referencing any attributes)
> OmegaConf.save(user, 'cfg.yaml')

Should write:
> user:  jsmith

Is this possible?

2) Is it possible to select a node/list of nodes with a where clause?

> users:
>   - type: admin
>   .. 
>   - type: guest
 
I was to select from users where type == 'admin'

Thanks,
Vish

**Comment by omry** [comment]
Check the signature of save:
```
    @staticmethod
    def save(
        config: Container, f: Union[str, pathlib.Path, IO[Any]], resolve: bool = False
    ) -> None:
        """
        Save as configuration object to a file
        :param config: omegaconf.Config object (DictConfig or ListConfig).
        :param f: filename or file object
        :param resolve: True to save a resolved config (defaults to False)
        """
```
You want to use resolve=True.

**Comment by sbyrakur** [comment]
Thank you. And, can I select .. where?

**Comment by omry** [comment]
Ah, missed that one.
This is not supported. you can select the parent node and do your own filtering.

**Comment by sbyrakur** [comment]
Thank you @omry
