### ISSUE TITLE
AttributeError for unpickling a PyTorch dataset

### ISSUE THREAD

**Issue by jgbos** [omry/omegaconf#268]
I'm failing to find any info on this error: 

```bash
----> 1 torch.load('epoch=1004.ckpt', map_location=torch.device('cpu'))

~/.conda/envs/test/lib/python3.7/site-packages/torch/serialization.py in load(f, map_location, pickle_module, **pickle_load_args)
    591                     return torch.jit.load(f)
    592                 return _load(opened_zipfile, map_location, pickle_module, **pickle_load_args)
--> 593         return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
    594
    595

~/.conda/envs/test/lib/python3.7/site-packages/torch/serialization.py in _legacy_load(f, map_location, pickle_module, **pickle_load_args)
    771     unpickler = pickle_module.Unpickler(f, **pickle_load_args)
    772     unpickler.persistent_load = persistent_load
--> 773     result = unpickler.load()
    774
    775     deserialized_storage_keys = pickle_module.load(f, **pickle_load_args)

AttributeError: Can't get attribute 'UntypedNode' on <module 'omegaconf.nodes' from '/home/gridsan/jgoodwin/.conda/envs/test/lib/python3.7/site-packages/omegaconf/nodes.py'>

```

The data was produced via Hydra 0.11 (and corresponding OmegaConf version).  I did an upgrade to Hyrda 1.0 which also upgraded OmegaConf.  The problem is I have no idea if this is fixable without downgrading first and if this is helpful to you.

**Comment by omry** [comment]
Do you have an old pickled version of the config object lying around?
Those are probably not compatible between OmegaConf 1.4 and OmegaConf 2.0.

Unfortunately you will have to use OmegaConf 1.4 to deserialize that object. depending on what you want to do, it may need that you need to downgrade Hydra too.

**Comment by jgbos** [comment]
Thanks for the feedback.  Yes it's a pickled version of a config object  created via `OmegaConf.to_container(cfg)`, so it should just be a `dict` object.  It's weird and I'm not sure it's problem with your code.   First, I have successfully loaded the data with downgraded hydra and omegaconf.  

Second, for some models I can load the data object using the upgraded packages, but for this model it throws this error for all saved files.  I wonder if something else is wrong and it throws the error in your code?

**Comment by jgbos** [comment]
Alright, I saved the object again (with the downgraded packages) and successfully loaded in the environment with the upgraded packages.  Something else is wrong.  Thanks for responding again and hope I didn't waste any of your time.  Thanks for the package!

**Comment by omry** [comment]
I suspect at some point there may have been a bug that cause the internal nodes to be returned in some cases.
if you can reproduce it let me know. I think it's fixed now both in 1.4.1 and 2.0.*

**Comment by jgbos** [comment]
ok, I'll see if I can reproduce it.

**Comment by jgbos** [comment]
Alright, first experiment between versions was flawed. I found the culprit within the optimizer state.  I'm using the `Adam` optimizer with parameters set for `betas`.  This parameter is a list and the type of those parameters saved in the data object is ` omegaconf.listconfig.ListConfig`.  This is why my other models didn't have this problem, I used a different optimizer for those.

**Comment by omry** [comment]
you mentioned that you converted with OmegaConf.to_container(cfg).

In that case the config should really be a primitive list/dict and should not have traces of OmegaConf.

**Comment by jgbos** [comment]
that is true.  The problem is how I instantiated the optimizer and how the state dictionary was saved out.  Since I instantiated on the OmegaConf object the state dictionary has traces of OmegaConf objects. So for an data object with keys `['opimizer_state_dic', 'cfg']`, the `cfg` data is a primitive dictionary but the `optimizer_state_dict` has OmegaConf objects.

**Comment by omry** [comment]
Now I get it, thanks for clarifying.

Overall OmegaConf internal datamodel is pretty stable. I changed it in the transition from 1.4 to 2.0 because it was already a breaking change for many reasons.
hopefully future upgrades will be backward compatible.
