### ISSUE TITLE
Revisit extending typing.List and typing.Dict in ListConfig and DictConfig

### ISSUE THREAD

**Issue by omry** [omry/omegaconf#270]
I tried it before and could not make it work.
can try again for 2.1.

**Comment by omry** [comment]
Some context on why I think extending MutableSequence and MutableMapping is the way to go:
https://treyhunner.com/2019/04/why-you-shouldnt-inherit-from-list-and-dict-in-python/

I will take a closer look at this for 2.1.

**Comment by omry** [comment]
not going to happen.

**Comment by wookayin** [comment]
May I ask what is blocking you?

**Comment by omry** [comment]
This is a breaking change and I don't think it's worth it.
OmegaConf containers are extending MutableSequence and MutableMapping and this should be good enough.
