### ISSUE TITLE
Relax OmegaConf.save() to accept Any

### ISSUE THREAD

**Issue by omry** [omry/omegaconf#287]
It should happily accept either a real OmegaConf object or a structured config (something annotated as dataclass).
there should be a runtime check to make sure input is valid.

**Comment by pereman2** [comment]
Should it also accept attr classes ?

**Comment by omry** [comment]
Any covers both dataclasses and attrclasses.

I don't think there is anything (pun!) better to do. if you can find a way to accept dataclasses (and attr classes) without using Any let me know.
