### ISSUE TITLE
With a List[int] config option (structured config), a single integer is still parsed as an integer

### ISSUE THREAD

**Issue by odelalleau** [omry/omegaconf#300]
This is a copy of https://github.com/facebookresearch/hydra/issues/758 moved to OmegaConf as per @omry 's request.

The following code runs fine while it should raise an error since `fudge` is supposed to be a list of integers, not an integer.

```python
from dataclasses import dataclass, field
from typing import List
from omegaconf import OmegaConf

@dataclass
class Config:
    fudge: List[int] = field(default_factory=lambda: [])

cfg = OmegaConf.structured(Config)

cfg.fudge = 1
```

**Comment by omry** [comment]
Thanks for reporting!
