### ISSUE TITLE
pretty() weirdly quote variable named y.

### ISSUE THREAD

**Issue by omry** [omry/omegaconf#317]
This is probably a regression related to the fix for floating point values from last week.
```
print(OmegaConf.create({"x": "???", "y": "???"}).pretty())
x: ???
'y': ???
```

**Comment by pereman2** [comment]
This is happening because 'y' is a pyyaml bool which we are now treating different when representing as string.

**Comment by omry** [comment]
Y is a key, not a value.
OmegaConf does not support bool keys. It supports strings and enuma now and may support integers in the future.

**Comment by omry** [comment]
Upon further reflection, this is expected.
OmegaConf keys does not support boolean values. YAML normally interpret `yes` as  boolean. If quoted it's interpreted as the string "yes".

If and when OmegaConf enable support for boolean keys then - depending on the type of the key it may or may not be quoted.
```python
cfg['yes']   = 10  # quoted in yaml output because it's a string
cfg['False'] = 20 # quoted in yaml output because it's a string
cfg[False]   = 30 # not quoted in yaml output because it's a boolean.
```
