### ISSUE TITLE
Brackets are not allowed in interpolations

### ISSUE THREAD

**Issue by odelalleau** [omry/omegaconf#318]
Currently an interpolation of the form
```
a: ${my_resolver:[0\,1\,2]}
```
is not recognized as an interpolation, and thus is not resolved.

This will mostly become a significant issue once nested interpolations are added (#308), since one may want to do something like:
```
parallel_job_ids: [0, 3, 9]
hydra:
  launcher:
    params:
      cpus_per_task: ${get_cpus_per_task:${parallel_job_ids}}
```
where `get_cpus_per_task()` is a custom resolver that computes the number of CPUs to be reserved on the cluster, from the list of parallel jobs to run.

This is the motivation for #316

**Comment by omry** [comment]
A better motivating example is something like this:
```
In [15]: OmegaConf.create({"foo": "${env:X,1}"}).foo
Out[15]: 1

In [16]: OmegaConf.create({"foo": "${env:X,'1,1'}"}).foo
Out[16]: "${env:X,'1,1'}"

In [17]: OmegaConf.create({"foo": "${env:X,[1,1]}"}).foo
Out[17]: '${env:X,[1,1]}'
```
As you can tell, brackets is just the tip of the iceberg. a proper fix is to switch to using an antlr based grammar here.
I would rather do that than start patching this piecemeal and eventually ending with users depending on new temporary behaviors.

**Comment by odelalleau** [comment]
Yes indeed there are other currently "illegal" characters as well that people might want to use, and I agree that a proper grammar will be needed at some point.

I'm not sure why your example would be "better motivating" though. Your second example can already work fine by writing it `OmegaConf.create({"foo": "${env:X,1\,1}"}).foo`, while there is a workaround for the third one by doing:
```
def env_with_default_list(var, default_list):
    default = f"[{default_list}]"  # add brackets
    return os.getenv(var, default)

OmegaConf.register_resolver("env_with_default_list", env_with_default_list)
OmegaConf.create({"foo": "${env_with_default_list:X,1\,1}"}).foo  # --> '[1,1]'
```

I couldn't find a workaround for my example though, which is why I believe it's a useful feature worth adding while we wait on that grammar.

**Comment by omry** [comment]
The presence of a workaround is not the deciding factor.
The request is to add [] as legal characters here and I already know that those will be used in the future as a part of a complete grammar. what about interpolating into a dictionary node?

```python
In [9]: OmegaConf.create({"z": [], "foo": "${env:X,${z}}"}).foo
Out[9]: '${env:X,[]}'

In [10]: OmegaConf.create({"z": {}, "foo": "${env:X,${z}}"}).foo
Out[10]: '${env:X,{}}'

```

**Comment by omry** [comment]
on a site note, we should probably raise an error in those cases. that's another shortcoming of the current approach.

**Comment by odelalleau** [comment]
> The presence of a workaround is not the deciding factor.
I think it should be *a* deciding factor at least. I wouldn't be proposing #316 if there was a workaround available (as I agree it's indeed a bandaid fix).

> The request is to add [] as legal characters here and I already know that those will be used in the future as a part of a complete grammar. what about interpolating into a dictionary node?
Good point, I hadn't considered it as I was selfishly focusing on my immediate needs. But yes, I think interpolating into a dictionary node should be allowed as well. I'm open to add this too, though that would mean getting rid of the current regex matching logic to implement proper counting of brackets / braces / ...

But maybe you think such use cases shouldn't be allowed at all (even with the future complete grammar)? If so, why?

**Comment by omry** [comment]
Yeah, I get that it seems like a simple enough fix. and I am sorry I am pushing back here.

Take a look at the [overrides grammar](https://hydra.cc/docs/next/advanced/command_line_syntax) in Hydra.
Eventually I would like to use something very similar to parse the values here. including native support for interpolation (it should even be converted to a string and back as it (probably) is now.
That grammar supports lists and dicts with arbitrary nesting. I would like to have something similar here.
the idea is also to pass the parsed objects to the function instead of the string.

By the way, such a grammar would also simplify other parsing tasks like parsing the interpolation keys themselves, and adding support for dict style indexing (`foo[10][bar] == foo.10.bar == foo[10].bar`).

Would you like to work on introducing this?
It took me about 10 days of work to add the grammar to Hydra, that includes:
- Design of the actual grammar (most time in that case)
- Support for automatically generating the parser when building a wheel or sdist, and when installing)
- Documentation updates

I am expecting this to be significantly easier for two reasons:
1. You can follow the model in Hydra and reuse the build mechanism from it.
2. You can reuse large parts of the grammar in Hydra.

It seems like a better way to spend the time than to implement sophisticated but fragile algorithms that will end up getting thrown away in the future anyway.

**Comment by omry** [comment]
If this is too much, I am willing to accept an unsupported API that would change the legal characters here.

I should be clearly labeled as unsupported though.

For example:
```python
OmegaConf.hack("override_interpolation_regex", ...)
```

**Comment by odelalleau** [comment]
> Would you like to work on introducing this?

I'll have a closer look at how it works in Hydra in the next few days and I'll get back to you on this. I'll do this before #319 as it'd probably address that one as well at the same time, if I were to go that direction.

**Comment by omry** [comment]
Awesome, feel free to jump on a chat in Workplace, by the way.

Here are some examples I think the grammar can support:
```yaml
a: ${foo.bar}
b: ${foo:str}
c: ${foo:10,str,3.14,true,false,nan,inf,[1,2,3], {foo:bar},'quoted', "quoted", 'a,b,c'}
```

**Comment by odelalleau** [comment]
Just to be sure, for example `c` did you mean: 

> ```yaml
> c: ${foo:10,str,3.14,true,false,nan,inf,[1,2,3], ${foo:bar},'quoted', "quoted", 'a,b,c'}
> ```
(the only difference is the `$` in front of `{foo:bar}`)

**Comment by omry** [comment]
yes. fixed.

**Comment by odelalleau** [comment]
> yes. fixed.

Thanks!

So after playing around with the grammar I think I finally got something that could be used to parse nested interpolations ==> I'll work on the actual Python code next week.

FYI here is my current version of the grammar, if you want to have a look. Note that I changed a few things compared to Hydra's grammar -- I'll highlight them later so we can discuss them, but if you already have some questions do not hesitate to ask!

Note: supporting something like `url: http://${server.host}:${server.port}/` (from the docs) gave me some headaches, but it works now... also I think even more characters could be allowed in unquoted strings (I already added a few compared to the current codebase, see `STR_NO_DIGIT`) -- to be discussed.

```
// High-level.
root: item EOF
item: (WS)* item_nows (WS)*;
item_nows: primitive | interpolation | list_of_items | dict_of_items;

// Interpolations.
interpolation: simple_interpolation | string_interpolation;
// Simple interpolations are of the form ${..}
simple_interpolation: direct_interpolation | resolver_interpolation;
direct_interpolation: '${' id_maybe_interpolated ('.' id_maybe_interpolated)* '}';  // ${foo}, {foo.bar}
resolver_interpolation: '${' id_maybe_interpolated ':' sequence_of_items '}';  // ${foo:x,y,z}
id_maybe_interpolated: ID | simple_interpolation | string_interpolation_no_other;
// String interpolations combine multiple components into a single string.
// We allow additional characters that can be concatenated without being quoted, in addition to
// those in `STR_NO_DIGIT`. This allows for instance using `http://domain.com:${port}`.
// Note that these additional characters cannot be added to `STR_NO_DIGIT` as otherwise
// some "." and ":" used in interpolations would be "consumed" by the lexer.
other_char: '.' | ':';
string_interpolation: string_interpolation_no_other | string_interpolation_other_left | string_interpolation_other_right;
// The "no other" string interpolation does not contain any character from `other_char`.
// It is used to extract identifiers, so that we can use for instance `${foo_${bar}:arg}`.
// Note that we allow non-string primitive types so as to deal with edge cases like `null${foo}`.
string_interpolation_no_other: primitive_or_simple (primitive_or_simple)+;
// The "other left and "other right" string interpolations are those containing characters
// from `other_char` (respectively starting and not starting with such a character).
string_interpolation_other_left: ((other_char)+ (primitive_or_simple)+)+ (other_char)*;
string_interpolation_other_right: ((primitive_or_simple)+ (other_char)+)+ (primitive_or_simple)*;
primitive_or_simple: primitive | simple_interpolation;

// Containers.
list_of_items: '[' sequence_of_items ']';
sequence_of_items: (item (',' item)*)?;
dict_of_items: '{' (key_value (',' key_value))*? '}';
key_value: (WS)* primitive (WS)* ':' item;

// Primitive types.
primitive: boolean | null | integer | floating_point | string;
integer: INT;
string: ID | BASIC_STR | QUOTED_STR;
floating_point: FLOAT;
boolean: BOOL;
null: NULL;

// *** Lexer rules ***

// Special keywords.
NULL: [Nn][Uu][Ll][Ll];  // null
BOOL:
      [Tt][Rr][Uu][Ee]      // true
    | [Ff][Aa][Ll][Ss][Ee]; // false

// Integers.
// Note: we disallow integers starting with '0' to minimize potential typos, even
// though calling `int()` on such a representation works, and Python also accepts
// them in exponents (ex: 1.5e007).
fragment DIGIT: [0-9];
fragment NZ_DIGIT: [1-9];
fragment INT_UNSIGNED: '0' | (NZ_DIGIT (('_')? DIGIT)*);  // 0, 7, 1_000
INT: [+-]? INT_UNSIGNED;  // 3, -3, +3

// Floats.
fragment FRACTION: '.' INT_UNSIGNED;
fragment POINT_FLOAT: INT_UNSIGNED? FRACTION | INT_UNSIGNED '.';  // .1, 0.1, 0.
fragment EXPONENT: [eE] [+-]? INT; // e5, E-3, e007
fragment EXPONENT_FLOAT: (INT_UNSIGNED | POINT_FLOAT) EXPONENT;
FLOAT: [+-]? (POINT_FLOAT | EXPONENT_FLOAT | [Ii][Nn][Ff] | [Nn][Aa][Nn]);

// Strings.
fragment ALPHA_: [a-zA-Z] | '_';
fragment ESC_SPACE: '\\ ';
fragment ESC_COMMA: '\\,';
ID : ALPHA_ (ALPHA_ | DIGIT)*;  // foo, bar2
STR_NO_DIGIT: ALPHA_ | '/' | '-' | '%' | '#' | '?' | '&' | '@' | ESC_SPACE | ESC_COMMA;
// Basic strings (= non quoted) are not allowed to start with a digit, so as to
// minimize the risk of typos (ex: 1__000).
BASIC_STR: STR_NO_DIGIT (DIGIT | STR_NO_DIGIT)*;  // foo, foo_bar, foo/2, foo\ 2, \,foo\,-bar\,baz\,
QUOTED_STR:
      '\'' ('\\\''|.)*? '\''  // Single quoted string. can contain escaped single quote
    | '"' ('\\"'|.)*? '"' ;   // Double quoted string. can contain escaped double quote
WS: (' ' | '\t');
```

**Comment by omry** [comment]
can you give me some of the test strings you tested this one?
this seems like a big divergence from the Hydra grammar and I would like to minimize the differences.

**Comment by odelalleau** [comment]
I started a PR (#321) to make it easier to have discussions. You'll find some examples there. Let's follow-up in that PR.
