### ISSUE TITLE
Fix interpolation naming discrepancies

### ISSUE THREAD

**Issue by odelalleau** [omry/omegaconf#319]
#308 introduced discrepancies between the intended meaning of some interpolation types vs. the underlying implementation.

For instance, `${foo.${bar}}` is intended to be called a "simple" interpolation, but `get_value_kind()` will identify it as a "string" interpolation. Although the code works fine, this is confusing and could cause other issues down the road => it should be fixed.

The fix may be based on renaming and / or code refactoring (TBD).

**Comment by omry** [comment]
This is probably no longer relevant now that we reverted #308 so I am closing.
