### ISSUE TITLE
Runtime error when creating a config from a dataclass using a Set.

### ISSUE THREAD

**Issue by omry** [omry/omegaconf#326]
```python
from omegaconf import OmegaConf
from dataclasses import dataclass
from typing import Set
@dataclass
class Foo:
    s : Set[str]
OmegaConf.structured(Foo(s = {"abc"}))
```

Results in `TypeError: issubclass() arg 1 must be a class`.

1. Set usage error should be specific to set.
2. Unexpected types should be rejected with a proper error and not a runtime error.

**Comment by pereman2** [comment]
I think this one is solved with #312 , it raises :
```
omegaconf.errors.ValidationError: Unexpected object type : Set[str]
        full_key: 
        reference_type=None
        object_type=None
```

**Comment by omry** [comment]
Cool, if it solves this one add a closes tag for this issue too.

**Comment by pereman2** [comment]
Okay.
