### ISSUE TITLE
Custom interpolation parses input to float, resulting in inf in some cases.

### ISSUE THREAD

**Issue by my-tien** [omry/omegaconf#341]
test.yaml

    key: ${env:val}

test.py

    from omegaconf import OmegaConf
    oconfig = OmegaConf.load('test.yaml')
    config = OmegaConf.to_container(oconfig, resolve=True)
    print(config)

Execution

    $ env val=6e1234 python test.py
    {key: 'inf'}

Expected:

    {key: '6e1234'}

Tested with latest stable release 2.0 and current master.

**Comment by omry** [comment]
@odelalleau, mind taking a look?

**Comment by my-tien** [comment]
Other tings can happen as well: 
144e16 becomes 1.44e+18

**Comment by odelalleau** [comment]
Can’t really until next week but it looks like it is working as intended

Le mer. 26 août 2020 à 23:25, Omry Yadan <notifications@github.com> a
écrit :

**Comment by my-tien** [comment]
Does it? When I pass env vars, I actually expect them to be inserted as they are, not modified.

**Comment by omry** [comment]
The implementation of the built in env resolver is to pass parsed primitives in.
Unfortunately, fixing it is a breaking change and will not happen soon.

The issue you reported does highlight a problem though, so I will keep it open.
I have a few ideas on how to address this class of problems, but this is not going to happen soon.

For now, you can register your own alternative function that will return the environment variable as is.

**Comment by my-tien** [comment]
Okay, for the moment I make my own resolver call this custom `decode_primitive`:

    def decode_primitive(s: str) -> Any:
        if omegaconf._utils.is_bool(s):
            return str.lower(s) == "true"

        if omegaconf._utils.is_int(s) and str(int(s)) == s:
            return int(s)

        if omegaconf._utils.is_float(s) and str(float(s)) == s:
            return float(s)

**Comment by odelalleau** [comment]
Sorry for the delay, vacations got in the way.

So IMO this is working as intended and I don't see why this is a problem. There could be a use case for a different resolver that does not attempt to parse the environment variable, but this would be a new feature (and in the meantime it shouldn't be difficult for someone to implement it by themselves).

Note that the same thing happens without resolvers, for instance:

```python
from omegaconf import OmegaConf
oconfig = OmegaConf.create("foo: 6e1234")
config = OmegaConf.to_container(oconfig, resolve=True)
print(config)  # => {'foo': inf}
```

I'm not sure what exactly is the goal of @my-tien's custom version of `decode_primitive()` but it seems a bit dangerous, for instance `".1"` or `"0."` aren't recognized as floats. I would expect that someone should usually know whether or not they want to parse the content of the env variable (and if they don't, right now they should write their own version of the `env` resolver, until an option to do so is offered in OmegaConf).

**Comment by omry** [comment]
Specifically for the env resolver, I suspect we should not parse the results. but this is a breaking change and we should consider if and how to do it.

Zooming out, this illustrates the tension parsing the parameter creates.
depending on the function, parsing may or may not be needed, we are planning some parameter to control this behavior at the function call level, but we can go even further and use the function signature to deduce what we should be converting to on a per parameter basis.

As an example, if the resolver is
```
def foo(x: int, y : str)
```
We could attempt to convert the first variable to int while keeping the second one untouched.
This conversion can happen quiet easily by creating a dynamic dataclass from the function signature and using OmegaConf merge to combine the input parameters dictionary with the schema.

In any case, this is something to thing about for the future. definitely not a high priority feature.

**Comment by odelalleau** [comment]
> Specifically for the env resolver, I suspect we should not parse the results. but this is a breaking change and we should consider if and how to do it.

I think both approaches can be useful, I don't see why OmegaConf should support only one => it may be better (and easier) to simply add another resolver that doesn't parse env variables.

> Zooming out, this illustrates the tension parsing the parameter creates.
> depending on the function, parsing may or may not be needed, we are planning some parameter to control this behavior at the function call level, but we can go even further and use the function signature to deduce what we should be converting to on a per parameter basis.
> (...)

This seems different to me. For `env` we are talking about parsing the *output* of the function, while here you are talking about parsing its *inputs*. I'm not sure this would be very useful: we can already use quotes to avoid parsing inputs (at least with the upcoming grammar-based version). For instance by writing `${foo:${x}, '${y}'}` we ensure that the second argument to `foo()` is a string, even if `y` is not.

**Comment by my-tien** [comment]
> I'm not sure what exactly is the goal of @my-tien's custom version of decode_primitive()
In my use case I have a .yaml file that has entries such as below:

    some_numerical_param: {env:number}
    some_path: /path/to/data-{env:identifier_hash}

so I am using env variables to set numerical parameters as well as directly in strings.

If my resolver just kept everything as string, the numerical params would become strings as well, e.g.:

    some_numerical_param: "3"

Because of that I have my custom `decode_primitive()` still do type conversions instead of simply converting everything to string.

**Comment by omry** [comment]
Your custom env resolver could just return the string as is. There is no need for this heuristic.

**Comment by omry** [comment]
not to mention that we will likely remove decode_primitive in the future (it is a function in a private utils class, deleting it is not a breaking change because internal APIs are not a part of the official API).

**Comment by my-tien** [comment]
Sorry, finally found some time again.
Thanks for your input, I think it would be a useful new feature to have one env resolver that parses the env variable and another that just leaves the string as is.

**Comment by omry** [comment]
#383 will address the issue in the env resolver.
