### ISSUE TITLE
OmegaConf.create() error: 'str_' is not a supported primitive type

### ISSUE THREAD

**Issue by AtomScott** [omry/omegaconf#344]
I'm using omegaconf in a machine learning project and I get the following error when I use `OmegaConf.create(hparams)` to create a DictConfig. `hparams` is a simple dictionary containing `{'optimizer': 'Adam', 'n_hidden': 112}`.

```
omegaconf.errors.UnsupportedValueType: Value 'str_' is not a supported primitive type
        full_key: optimizer
        reference_type=Optional[Dict[Any, Any]]
        object_type=dict
```

When I debug and set a breakpoint at `OmegaConf.create(hparams)`, and in the debug console manually type  `OmegaConf.create({'optimizer': 'Adam', 'n_hidden': 112})` there is no problem. A DictConfig is created as expected.
However, `OmegaConf.create(hparams)` raises the same error.

I spent a few hours trying to locate the bug, but I frankly have no idea.
I'm using 2.0.1rc6.

**Comment by AtomScott** [comment]
After opening the issue, I realized that `'str'`!=`'str_'` and casting from `str_` to `str` solved the problem.
`'str_'` seems to be `'numpy.str_'`,  https://stackoverflow.com/a/20486771/5034709.

Nevertheless, the code was working before I updated to 2.0.1rc6. So a fix might be in need?

**Comment by AtomScott** [comment]
Pandas also seems to have had a simlar issue before https://github.com/pandas-dev/pandas/issues/31499.
Could just try implicit casting to str.

**Comment by omry** [comment]
OmegaConf does not support numpy or pandas primitives and it never did.
I am surprised it worked before but that could have been a bug.
also, please upgrade to the latest 2.0.1 release candidate.

**Comment by AtomScott** [comment]
> I am surprised it worked before but that could have been a bug.
Yeah seems like it was a bug. Wasn't able to replicate the error in 1.4.0. 
https://colab.research.google.com/drive/1PpCID8iYoqT61MFDGogwoDBcuR3danxu?usp=sharing

Thanks for clearing things up!

**Comment by omry** [comment]
Thanks for the repro.
Yup, this is a bug. weird that it went through in 1.4.
