### ISSUE TITLE
[Bug] Using ${foo.bar} returns ${foo} if `foo` is not a container

### ISSUE THREAD

**Issue by odelalleau** [omry/omegaconf#364]
```
cfg = OmegaConf.create(dict(foo=0, bug="${foo.bar}"))
print(cfg.bug)
```
The above code prints "0" while I would expect it to crash.

What puzzles me is that this behavior is actually tested right now:
```
def test_indirect_interpolation2() -> None:
    d = {
        "a": {"aa": 10},
        "b": "${a.aa}",
        "c": "${b.aa}",
    }

    cfg = OmegaConf.create(d)
    assert cfg.c == 10
```
This test doesn't make sense to me: accessing `cfg.c` should crash since `b` is equal to 10 so `b.aa` should be invalid. Am I missing something?

**Comment by omry** [comment]
This looks like a bug in the test and in the code.
This makes more sense:

```python
def test_indirect_interpolation2() -> None:
    d = {
        "a": {"aa": 10},
        "b": "${a.aa}",
        "c": "${b}",
    }
```

**Comment by omry** [comment]
feel free to send a PR.
