### ISSUE TITLE
Improve the API of register_resolver()

### ISSUE THREAD

**Issue by omry** [omry/omegaconf#370]
1. Currently, if a resolver is already registered there is an assertion error. this should be a regular exception (ValueError)
2. ~~If the same callable is registered twice with the same name (and the same cache settings), we can just ignore the call.~~ (dropped)
2. Allow overriding an existing resolver by registering it with `replace=True`
3. Currently, if one attempts to register a resolver that is not a callable, an assertion error is raised: it should be a TypeError
4. If an empty name is provided, a ValueError should be raised

**Comment by omry** [comment]
Blocked on #445 which makes changes to this API.

@odelalleau, can you pick this one up later?

**Comment by odelalleau** [comment]
> Blocked on #445 which makes changes to this API.
> 
> @odelalleau, can you pick this one up later?

Yes, I added it to #535 (it should be trivial)

Just to clarify, do you want to create a new exception for this, or just raise a `OmegaConfBaseException`?

**Comment by omry** [comment]
I think even ValueError is fine here. assertion errors are not supposed to be used as user interface.
Since we are creating a new register function it's a chance to fix this.
