### ISSUE TITLE
Can't use conditional statement with ListConfig

### ISSUE THREAD

**Issue by rbavery** [omry/omegaconf#372]
**Describe the bug**
I have a dataclass that I use to validate the types of configs stored in a yaml file like so:

```python
@pytest.fixture
def config():
    from omegaconf import OmegaConf
    from aquacroppy.config import Config # the dataclass with typed attributes
    conf_from_file= OmegaConf.load("./tests/exampleTuniswheatconfig.yaml")
    schema = OmegaConf.structured(Config)
    config = OmegaConf.merge(schema, conf_from_file)
    return config
```

The dataclass, `Config` contains a List[float] attribute.

```python
th_fc_profile: List[float] = field(default_factory=lambda : [.31, .31, .31, .31, .31, .31, .31, .31, .31, .31, .31, .31]) # (m3/m3)
```

When the attribute is accessed and used in a conditional, it's not a list type but is a ListConfig type, which causes the error.

```python
>           mask1 = self.config.th_fc_profile > .3
E           TypeError: '>' not supported between instances of 'ListConfig' and 'float'
```

**To Reproduce**
Please provide a minimal repro.
This can include a small Python file, and potentially a few small config files.
If you have more than one file you can attach a zip file with everything to the issue.

```python
import omegaconf
omegaconf.listconfig.ListConfig([1 , 2, 3]) > 2
```

**Expected behavior**
I would think that after merging the schema with the config loaded from the yaml file that the attribute would be a list type not a ListConfig type. Or maybe that the ListConfig type would support conditionals. 

I might be missing something about how the library should be used, any pointers or comments on whether this is actually a bug are appreciated.

**Additional context**
- [x ] OmegaConf version: 2.0.2
- [ x] Python version: Python 3.7.6
- [ x] Operating system : Ubuntu 18.04
- [ x] Please provide a minimal repro

**Comment by omry** [comment]
ListConfig and DictConfig trying to emulate list and dict to the greatest possible extent.
This does not work for a primitive list as well:
```
In [4]: [0.1, 0.2, 0.3] > 0.2
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-4-b11e7e5e09c6> in <module>
----> 1 [0.1, 0.2, 0.3] > 0.2
```

Why are you expecting > between a list and a value to work?

**Comment by rbavery** [comment]
Oops rookie mistake on my part. Been working with numpy arrays so much I assumed. Closing.

**Comment by omry** [comment]
Yup, I suspected as much :).
