### ISSUE TITLE
Evaluate support for non primitive objects

### ISSUE THREAD

**Issue by omry** [omry/omegaconf#382]
This is opening a very large surface area and it will make supporting some things like serialization impossible in such cases, but it's still a highly requested feature.
A few thoughts:
1. For regular DictConfig it could be off by default and enable via a config flag.
2. In Structured Configs, we could support it as a new node type.

**Comment by omry** [comment]
As a temporary solution, I added an unofficial API in #384 and #385, this is a new flag with the name "allow_objects".

Usage is something like:
```python
    iv = object()
    with flag_override(c, "allow_objects", True):
        c.a.b = iv
        assert c.a.b == iv
```

Note that this is not yet an official API, and it's likely to break serialization and possibly cause other issues. If you use it please report any issues.

**Comment by mauriceweiler** [comment]
I am working on a project where I need to add non-primitive objects to DictConfig. Currently I am using your approach from `test_allow_objects()`:
```
    c = OmegaConf.create({"foo": AnyNode()})
    c._set_flag("allow_objects", True)`
```
I am aware that this interferes with serialization, but I don't need that feature.

Are there any other concerns I should be aware of?
Why did you decide to not document the existence of this feature? It would have been useful for me to find it in the docs (with a warning of which other functionality might break).
