### ISSUE TITLE
TOML support

### ISSUE THREAD

**Issue by albertotb** [omry/omegaconf#388]
Is there any plan to support TOML configuration files?

**Describe the solution you'd like**
Support for TOML configuration files

**Describe alternatives you've considered**
Just use YAML files or parse the TOML file using toml library and then merge

**Comment by omry** [comment]
1. What do you imagine toml support in OmegaConf looks like?
Currently you can load yaml files via OmegaConf.load() and create configs from a string with yaml content with OmegaConf.create().
Do you imagine a new OmegaConf.load_toml() function?

2. Such support does not automatically means Hydra will also support toml. It has it's own constraints and is unlikely to support config files other than yaml.

**Comment by albertotb** [comment]
1. Either a load_toml() method or distinguishing in load/create using the extension (yaml/toml).
2. That is unfortunate, but I still think this will benefit OmegaConf. It seems Python is embracing the TOML format (see for instance pyproject.toml). 

A current workaround (not tested) is to load the TOML file as a dict and then create the conf from the dict. However the support is still convenient since that way you do not have to explicitily import the toml library. I guess you could argue for JSON support as well but it can be read using the standard library and proceed as above.

**Comment by omry** [comment]
I don't like relying on the extension for such things.
Your workaround will work, OmegaConf can be constructed from a dict.

As a side note, did you know that yaml is a superset of json and can parse it?
Looking at toml, I have to say I am not a fan. It seems pretty clunky compares to yaml.
Parsing it is for sure much much easier, but yaml is much easier to read and write.

Having played with toml for a moment:
```
cfg = OmegaConf.create(toml.load("1.toml"))
print(cfg)
```
I already got into an issue: It returns non primitive types (like datetime) which are incompatible with OmegaConf.
If you can find how to convince the built-in Python toml to not do that I can consider adding it but chances are I won't. I do not like what I am seeing so far.

**Comment by albertotb** [comment]
> I already got into an issue: It returns non primitive types (like datetime) which are incompatible with OmegaConf.
> If you can find how to convince the built-in Python toml to not do that I can consider adding it but chances are I won't. I do not like what I am seeing so far.

I don't think you can opt-out of that behaviour since the TOML specification has support for first class dates. 

I understand what you are saying so feel free to close the issue. Just out of curiosity, what do you mean with "non-primitive types are incompatible with OmegaConf"? The code you show seems to work fine for me.

**Comment by omry** [comment]
Run it on a toml config file that has dates to see what I mean (the one from [here](https://en.wikipedia.org/wiki/TOML) works).
OmegaConf only accept dicts, lists, int, float, str, bool and compatible dataclasses. datetime is not a supported type and is unlikely to be.

**Comment by albertotb** [comment]
I see. Thanks for taking the time to look into this.

**Comment by omry** [comment]
Thanks for making the suggestion and for the discussion.
