### ISSUE TITLE
Unexpected (additional) single quotes when converting a list of chars to YAML

### ISSUE THREAD

**Issue by redoctopus** [omry/omegaconf#406]
**Describe the bug**
Unexpected quotes around the letters `n` and `y` when converting a list of chars via `to_yaml()`, as well as around the apostrophe character `'`.

**To Reproduce**
```
from omegaconf import OmegaConf
c = OmegaConf.create({'labels': ["a", "b", "n", "o", "x", "y", "'"]})
print(OmegaConf.to_yaml(c))
```
Outputs:
```
labels:
- a
- b
- 'n'
- o
- x
- 'y'
- ''''
```

**Expected behavior**
I was expecting no additional quotes around these characters:
```
labels:
- a
- b
- n
- o
- x
- y
- '
```

**Additional context**
- [ ] OmegaConf version: 2.0.1rc12, also reproduced in 2.0.2
- [ ] Python version: 3.6.9
- [ ] Operating system : Mac OS

**Comment by omry** [comment]
This is a known issue.
OmegaConf supported keys are strings only, and YAML interprets y and n as boolean.
The quotes are added automatically to ensure they are interpreted as strings.
Beyond this being surprising and annoying, are there any actual implications?

**Comment by redoctopus** [comment]
Ah, got it--no issues then, as loading from the resulting file gets me what I'd expect.
Thanks for the clarification.

**Comment by omry** [comment]
Cool.
I agree that this is annoying. this is a side effect of fixing an actual bug, and pyyaml is not quiet flexible enough to do what we need it to so the only solution is to re-implement `yaml .dump()`, but I think it's not worth it for this issue.
