### ISSUE TITLE
Unable to pickle typing.Dict[kt, vt] and List[vt] on python 3.6

### ISSUE THREAD

**Issue by pereman2** [omry/omegaconf#407]
**Describe the bug**
Pickling generic types `Dict[kt, vt]` and `List[vt]`on python 3.6 produces an error.

**To Reproduce**
```python
@dataclass
class Pick:
    union: Dict[str, int] = field(default_factory=lambda: {})

with tempfile.TemporaryFile() as fp:
    c = OmegaConf.structured(Pick)
    pickle.dump(c, fp)
    fp.flush()
    fp.seek(0)
    c1 = pickle.load(fp)
```

**Expected behavior**
It should be able to pickle.

**Additional context**
- [x] OmegaConf version: 2.1.0
- [x] Python version: 3.6
- [x] Operating system : macOS
- [x] Please provide a minimal repro

**Comment by omry** [comment]
@jieruhu, this could be related to the issue you are seeing in the Ray Launcher on 3.6.
