### ISSUE TITLE
AssertionError, no explaination

### ISSUE THREAD

**Issue by charleswilmot** [omry/omegaconf#418]
```
Traceback (most recent call last):
  File "cluster.py", line 24, in start_job
    OmegaConf.to_container(cfg, resolve=True)
AssertionError

Set the environment variable HYDRA_FULL_ERROR=1 for a complete stack trace.
```
however
```
username@hostname :  echo $HYDRA_FULL_ERROR 
1
```

`to_container` throws an assertion error without any trace, nor error message. 
My configuration files are big and numerous. I finally found out where the problem came from, but the `AssertionError` really got on my nerves. I needed to talk about it.

I feel better now.

**Comment by omry** [comment]
Hi,
Sorry about the unexplained assertion error.
Hydra and OmegaConf goes to great length to ensure that the error messages are good and to the point.
assertion errors are typically an indication of a bug in the code, in this code there is at least a second bug that causes the error message to be opaque (it's also possible that it's not a bug in the first place but an omission).

I am assuming that you are talking about [this](https://github.com/omry/omegaconf/blob/master/omegaconf/omegaconf.py#L479) one, but without a stack trace or a repro it could be anywhere.

A minimal repro and the full stack trace you managed to get will help.
