### ISSUE TITLE
Deprecation of `register_resolver()` to introduce new functionalities

### ISSUE THREAD

**Issue by odelalleau** [omry/omegaconf#426]
# Migrating custom resolvers from OmegaConf 2.0 to 2.1

## Summary

1. Replace `register_resolver` with `register_new_resolver`
2. Update resolvers to handle non-string arguments (if applicable)
3. Only for resolvers whose output must be cached: ensure `use_cache=True` is passed to `register_new_resolver`

## Detailed migration instructions

Here are the main changes between resolvers registered with `register_new_resolver()` vs the old `register_resolver()`:

* They may take as input data of types supported by the new grammar (e.g. int, float, bool, dict, list) and possibly computed from other interpolations, e.g.: `${func: [3.14, ${oc.env:VAR}], true}`
* Their cache is disabled by default (and can be enabled by passing `use_cache=True` to `register_new_resolver()`)
* They may access the parent and the root config nodes (by declaring `_parent_` and `_root_` to the callable respectively) (#599).

In most cases, migrating an existing resolver from OmegaConf 2.0 to 2.1 means replacing `register_resolver()` with `register_new_resolver()` and ensuring the resolver is correctly handling non-string inputs, if applicable.

As an example, imagine you had the following resolver in OmegaConf 2.0:

```python
def add_ints(*args: str) -> int:
    return sum(int(x) for x in args)  # in 2.0 all arguments are strings and must be manually converted

OmegaConf.register_resolver("add_ints", add_ints)
cfg = OmegaConf.create("sum: ${add_ints:1,2,3}")
assert cfg.sum == 6
```

In this example arguments will now expected to be integers in OmegaConf 2.1:

```python
def add_ints(*args: int) -> int:
    assert all(isinstance(x, int) for x in args)  # if we want to prevent adding non integer values
    return sum(args)

OmegaConf.register_new_resolver("add_ints", add_ints)
cfg = OmegaConf.create("sum: ${add_ints:1,2,3}")
assert cfg.sum == 6
```

Note that here we didn't register the resolver with `use_cache=True`: it is expected that most resolvers should not need to use the cache. If you are depending on the caching behavior by assuming that your resolver is always returning the same value even when the underlying function may return a different value (e.g. `random()`, `time()`), then register your resolver with `use_cache=True`.

The new resolver behavior is documented in detail in [the documentation](https://omegaconf.readthedocs.io/en/latest/custom_resolvers.html).

__Additional remarks:__
* In 2.1 you can silence the deprecation warning by calling `legacy_register_resolver()` (without updating your resolver), but this is only a temporary workaround that will be deprecated in future versions.
* There are a few more small differences in the behavior of `register_new_resolver()` (compared to `register_resolver()` in 2.0), see #370 for details

# Deprecation plan for `register_resolver()`

The following deprecation plan is being applied to `register_resolver()` so as to enable new functionalities introduced in OmegaConf 2.1 (#445):

1. In 2.1 `register_resolver()` is deprecated, and users calling this function will see a warning redirecting them to this issue. The old behavior of `register_resolver()` remains temporarily available through `legacy_register_resolver()`. Users are **strongly encouraged** to switch to the new function `register_new_resolver()` (see above for an example).

2. In 2.2 `register_new_resolver()` will be renamed into `register_resolver()`, and users calling `register_new_resolver()` will be warned to call `register_resolver()` instead. Users calling the old `legacy_register_resolver()` will also be warned to switch to `register_resolver()`, updating their resolver accordingly.

3. In 2.3 `register_new_resolver()` and `legacy_register_resolver()` will be removed

**Comment by omry** [comment]
I think we don't need to quote the deprecation message here. people getting to this page will likely got here following the link there.
Also, we should encourage people to use the new function and only suggest the legacy one as a temporary fix.

**Comment by odelalleau** [comment]
> I think we don't need to quote the deprecation message here. people getting to this page will likely got here following the link there.
> Also, we should encourage people to use the new function and only suggest the legacy one as a temporary fix.

Sounds good -- I updated the warning, see https://github.com/odelalleau/omegaconf/blob/4f0db2dd70c40c5442838a736aab465e34b6fdb6/omegaconf/omegaconf.py#L368

(probably we can delete this comment and yours once all looks good to you, to avoid confusing readers of this issue)

**Comment by omry** [comment]
Yup. we can clear the comments once we are done.
I would suggest that you minimize details in the warning and tell people that this function is deprecated and they should check this link for migration guidance.
This page can contains much more details about the change, with nice formatting - that I don't see a good reason to give full details in the warning.
something like this should be enough:
```
register_resolver() is deprecated. 
See https://github.com/omry/omegaconf/issues/426 for migration instructions.
```

**Comment by odelalleau** [comment]
> I would suggest that you minimize details in the warning and tell people that this function is deprecated and they should check this link for migration guidance.

Makes sense, done in 9089ee9

**Comment by thoth291** [comment]
FYI, Compose API (hydra-core=1.0.4) reporting depreciation warning.
```python
from hydra.experimental import compose, initialize
from omegaconf import OmegaConf
OmegaConf.new_register_resolver("plus", lambda x,y: float(x)+float(y))
initialize(config_path="conf", job_name="test_ipython")
```
producing this
```python
/conda/x86_64/envs/hydra/lib/python3.8/site-packages/hydra/core/utils.py:143: UserWarning: register_resolver() is deprecated.
See https://github.com/omry/omegaconf/issues/426 for migration instructions.

  OmegaConf.register_resolver(name, f)
```

**Comment by omry** [comment]
what version of OmegaConf do you have installed?

**Comment by raphCode** [comment]
I am confused because I called `register_resolver()` with omegaconf version 2.2.2 and got the deprecation warning.
According to the deprecation plan outlined in the first post this is the behavior of omegaconf 2.1 .

If I understand the plan correctly, using `register_resolver()` in the current version is the future-proof method of registering resolvers and should not issue a warning.
Am I missing something or can I safely ignore the warning?

**Comment by odelalleau** [comment]
> I am confused because I called `register_resolver()` with omegaconf version 2.2.2 and got the deprecation warning. According to the deprecation plan outlined in the first post this is the behavior of omegaconf 2.1 .
> 
> If I understand the plan correctly, using `register_resolver()` in the current version is the future-proof method of registering resolvers and should not issue a warning. Am I missing something or can I safely ignore the warning?

Don't ignore the warning, there's a good chance the deprecation plan outlined above wasn't followed exactly in 2.2.x and this issue should be updated to match what actually happened.

@Jasha10 thoughts?

**Comment by raphCode** [comment]
I am developing new code so I am flexible.
Ideally I want write code that I don't have to update anymore with future omegaconf versions.
It is not clear to me how I can achieve that: The plan states that both `register_new_resolver()` and `legacy_register_resolver()` will be eventually removed in a future version, which leaves only `register_resolver()`.

**Comment by Jasha10** [comment]
> there's a good chance the deprecation plan outlined above wasn't followed exactly in 2.2.x

Yes, this is what happened.

In OmegaConf 2.2, `register_new_resolver()` is still the preferred method to use, and `register_resolver` still gives a deprecation warning.

I've updated the issue description above and will create a follow-up issue.
