### ISSUE TITLE
Unclear error: incorrect type for field of dataclass instance

### ISSUE THREAD

**Issue by Tetratrio** [omry/omegaconf#435]
**Describe the bug**
When using the incorrect value type for a field in a dataclass instance and then using that to construct a config object the error message is quite unclear.

**To Reproduce**
```python3
import omegaconf
import dataclasses
@dataclasses.dataclass
class Config:
    some_field: int = 3

omegaconf.OmegaConf.create(Config(some_field='test'))
```
gives the error
```text
omegaconf.errors.ValidationError: Value 'None' could not be converted to Integer
	full_key: 
	reference_type=None
	object_type=None
```

**Expected behavior**
I would love to have the same behavior as when running
```python3
omegaconf.OmegaConf.merge(Config, {'some_field':'test'})
```
which gives
```text
omegaconf.errors.ValidationError: Value 'test' could not be converted to Integer
	full_key: some_field
	reference_type=Optional[Config]
	object_type=Config
```

**Additional context**
- [ ] OmegaConf version: 2.0.2
- [ ] Python version: 3.8.3
- [ ] Operating system : Ubuntu 18.04

This issue is not important, it was just something I discovered while testing out error messages for a framework.

**Comment by omry** [comment]
Thanks for reporting, we will look into it.

**Comment by omry** [comment]
It may be pretty hard: I think that despite the two things looking similar, the error happens in a very different code paths.

**Comment by Tetratrio** [comment]
Ah, too bad. But no worries, I have made a somewhat hacky solution in the meanwhile. Don't bother if it is too much work. If I had more time I would take a look myself and see if I could contribute somehow.
