### ISSUE TITLE
Tuple in a List (and probably Dict) does not work

### ISSUE THREAD

**Issue by alexeib** [omry/omegaconf#436]
```python
@dataclass
class A:
  a: Union[str, float]
  b: List[Tuple[int, int, int]]
```

Trying to use those types leads to errors like:
Unsupported value type : typing.Tuple[int, int, int]

While Union may be debatable, something like Tuple in the lists should be relatively easy to support?

**Comment by omry** [comment]
Thanks Alexei.
Union has an issue already (#144).
Tuple is supported. this looks like a bug in List of Tuples.

**Comment by pereman2** [comment]
Union will be supported with #381, Union[str, int], Dict[str, Union[str, int], List[Union[str, int] ... 

On the other side Lists, Dicts and Tuple are not supported element_types for DictConfig and ListConfig. It should be easy to add support to it though, I'll check it.

**Comment by omry** [comment]
There is already a dedicated issue for both [Tuples](#392) and [Union](#144).
Closing as duplicate.

Both are very substantial features and I am not sure we will be able to get either of those in for 2.1.
