### ISSUE TITLE
Unexpected behavior when setting field to itself

### ISSUE THREAD

**Issue by 1matthewli** [omry/omegaconf#449]
**Describe the bug**
Under certain conditions, setting an entry of config to itself ends up clearing the entry entirely.

**To Reproduce**
```
cfg1 = OmegaConf.create({'a': 10})
cfg2 = OmegaConf.create({'b': 20})
cfg1["c"] = cfg2
print(cfg1["c"])
cfg1["c"] = cfg1["c"]
print(cfg1["c"])
```
The first print will be as expected, and the second print will be empty dictionary.
One workaround I have figured out is to set `cfg2.__dict__['_metadata'].ref_type = typing.Any` right after creating it, and it works as expected.

**Expected behavior**
It is expected for both prints to be the same, potentially with some interpolation resolution happening on access.

**Additional context**
- [x] OmegaConf version: 2.0.4
- [x] Python version: 3.7.9
- [x] Operating system : Ubuntu 16.04.7 LTS
- [x] Please provide a minimal repro

**Comment by omry** [comment]
Thanks for reporting.
