### ISSUE TITLE
Accessing path to the current config

### ISSUE THREAD

**Issue by YannDubs** [omry/omegaconf#45]
I was wondering whether we could access the path to the current config. Something likeK `${__file__}`

I'm wanted to test hydra, but don't want to hardcode the base directory to my working directory as different collaborators might have a different one. I was hoping that I define the base directory in the main `config.yaml` by using `${__file__}`.

**Comment by omry** [comment]
Yann,
Hydra uses the config directory to find and load the config, so you can't rely on it in your own code to do the same.
The current pattern is to have that directory right next to the code (and committed to the repo).

One thing you can do is to modify the config search path.
currently this can be done by writing s search path plugin in Hydra, and is not documented well in the public release.

See https://cli.dev/docs/advanced/plugins#searchpathplugin for a description of what a SearchPathPlugin is.

Closing as the actual request is not something I plan on adding to OmegaConf.
feel free to continue discussing here.
