### ISSUE TITLE
Dict[str, Optional[str]] fails

### ISSUE THREAD

**Issue by omry** [omry/omegaconf#460]
```python
from dataclasses import *
from typing import *
from omegaconf import OmegaConf
@dataclass
class Foo:
    a : Dict[str, Optional[str]]

OmegaConf.structured(Foo)
```

Raises an assertion failure

**Comment by omry** [comment]
@pereman2, related to your ongoing work on better containers support.

**Comment by Jasha10** [comment]
I think this will require expanding what `DictConfig._metadata` can handle.

For example, `DictConfig({}, element_type=str)` works but `DictConfig({}, element_type=Optional[str])` fails.

**Comment by omry** [comment]
Sounds right.
