### ISSUE TITLE
Pop with default on structured config with enum keys raises `KeyValidationError`

### ISSUE THREAD

**Issue by guillaumegenthial** [omry/omegaconf#471]
**Describe the bug**

Using `get(key, default)` or `pop(key, default)` on a config object whose key type is an enum raises an `KeyValidationError` if key is not a valid enum type.

I think a python user would probably expect a more lenient behavior (without the key validation if a default is explicitely provided).

However, I can also see how this is a valid behavior from OmegaConf perspective.

**To Reproduce**

```python
from omegaconf import OmegaConf
from dataclasses import dataclass
from enum import Enum
from typing import Dict


class Color(Enum):
    RED = "red"
    GREEN = "green"
    BLUE = "blue"


@dataclass
class ColorConf:
    colors: Dict[Color, float] = None


config = OmegaConf.structured(ColorConf({Color.RED: 0.1}))
config.colors.pop(Color.RED, None)  # 0.1
config.colors.pop(Color.BLUE, None)  # None
config.colors.pop("blue", None)  # Errors with any key that is not Enum
```
which raises

```bash
omegaconf.errors.KeyValidationError: Key 'some_other_key' is incompatible with the enum type 'Color', valid: [RED, GREEN, BLUE]
    full_key: colors.some_other_key
    reference_type=Dict[Color, float]
    object_type=dict
```

**Expected behavior**
Key "blue" is not in `config.colors`, but I said "give me None if not there".

```bash
None
```
**Additional context**
- [x] OmegaConf version: 2.1.0.dev14
- [x] Python version: 3.6
- [x] Operating system : MacOS
- [x] Please provide a minimal repro

**Comment by omry** [comment]
Having looked at it, I am leaning toward keeping things as is.
If you are passing a key with a type that is incompatible with the DictConfig key type, you have a code error.
This is true even if you do provide a default value.
It seems like allowing for an invalid key if a default value is provided is jumping through hoops for no good reason. might as well just let you know you have an error up front and not shy from it.

Let me know what you think.
