### ISSUE TITLE
Support TypedDict

### ISSUE THREAD

**Issue by indigoviolet** [omry/omegaconf#473]
**Is your feature request related to a problem? Please describe.**

`TypedDict` is a convenient way to tell `mypy` about the allowed keys in a dict. However, using a TypedDict as the type of a structured config causes an error.

```
from omegaconf import OmegaConf, MISSING
import attr
from typing import TypedDict

class Foo(TypedDict):
   foo: str

@attr.s(auto_attribs=True)
class Bar:
   f: Foo = MISSING


Bar(f={'foo': 'a'})
Out [39]:
Bar(f={'foo': 'a'})

In [40]:
OmegaConf.structured(Bar)

Truncated Traceback (Use C-c C-$ to view full TB):
~/dev/devr/py/.venv/lib/python3.8/site-packages/omegaconf/_utils.py in _raise(ex, cause)
    608     else:
    609         ex.__cause__ = None
--> 610     raise ex  # set end OC_CAUSE=1 for full backtrace
    611 
    612 

ValidationError: Unexpected object type : Foo
	full_key: 
	reference_type=None
	object_type=None
```

**Describe the solution you'd like**
I'd like TypedDict to be supported.

**Comment by omry** [comment]
Thanks for the suggestion.
Adding this on a provisional basis. If it turns out to have a serious conflict downstream I may revert this.

**Comment by omry** [comment]
NOTE: The runtime behavior of a typed dict after #474 is that it's just like a regular dict.
The extra type information is ignored at runtime. I am not currently interested in supporting additional inputs beyond dataclass and attr classes for Structured Configs.

**Comment by indigoviolet** [comment]
Thanks for the quick feature support, @omry .
