### ISSUE TITLE
OmegaConf.copy() doesn't make a copy

### ISSUE THREAD

**Issue by tommidigi** [omry/omegaconf#475]
When you create a OmegaConfg and use .copy() it doesn't make a copy.

```
>>> from omegaconf import OmegaConf
>>> conf = OmegaConf.create({"name": "test"})
>>> conf2 = conf.copy()
>>> conf2.name = "new name"
>>> conf2
{'name': 'new name'}
>>> conf
{'name': 'new name'}
```

At the end `conf` should equal to `{'name': 'test'}`

OmegaConf version: 2.0.5
Python version: 3.8.3
Operating system : macOS Big Sur

**Comment by omry** [comment]
1. Can you test on 2.1 dev release or on master?
2. Does it work if you use copy.copy(conf) ?

**Comment by tommidigi** [comment]
1. works on master.

**Comment by omry** [comment]
I am releasing 2.0.6 with the fix for this issue now.
