### ISSUE TITLE
Optimization: reduce number of deepcopies

### ISSUE THREAD

**Issue by omry** [omry/omegaconf#477]
During assignment of any value to an OmegaConf container, it is deep-copied.
the motivation is primarily address the case a node from an existing config tree is assigned to another config:
```python
    cfg1 = OmegaConf.create({"foo": {"bar": 10}})
    cfg2 = OmegaConf.create({})
    cfg2.foo = cfg1.foo
    assert id(cfg1.foo._get_parent()) == id(cfg1)
    assert id(cfg2.foo._get_parent()) == id(cfg2)
```

Without a deepcopy, the parent of the node cfg1.foo will change and cfg1 will be broken and the asserts will fail (resulting in interpolation and other issues).

Deepcopy is a clean solution, but it's expensive and most cases an overkill.
to improve initialization performance, we can limit deepcopy only to the rare cases where a node that belongs to an existing OmegaConf container is assigned.

This is a potentially breaking change in rare cases but think those are unlikely.

**Comment by o-smirnov** [comment]
Thanks for this -- it's made a huge difference -- my config load times dropped from 10s to <0.5s.

**Comment by omry** [comment]
Great to hear. There are some other optimization in 2.1 as well.
