### ISSUE TITLE
Setting non-dictconfig attributes

### ISSUE THREAD

**Issue by carmocca** [omry/omegaconf#480]
Hi @omry! First of all, thanks for the work you've put into this library!

I was wondering if there is any way to set a `DictConfig` attribute to a `dataclass`, without it getting converted into a `DictConfig`

```python
from dataclasses import dataclass
from omegaconf import OmegaConf

@dataclass
class Foo:
    bar: int = 1

# baseline
x = OmegaConf.create({"foo": {"bar": 1}})
print(type(x["foo"]), x)

# assignment
x["foo"] = Foo()
print(type(x["foo"]), x)

# update
OmegaConf.update(x, "foo", Foo())
print(type(x["foo"]), x)

# creation
x = OmegaConf.create({"foo": Foo()})
print(type(x["foo"]), x)
```

All of these print the same output and convert `Foo()` into `{bar: 1}`

My use case is wanting to parse some of the DictConfig attributes into dataclasses, while keeping others as DictConfigs.

Thank you!

**Comment by omry** [comment]
Hi @carmocca!

No, this is a fundamental design choice.

The dataclass objects are assumed to be Structured Configs and are converted to a type safe DictConfig.
You can access the underlying type with OmegaConf.get_type(cfg), and in principle you can instantiate the dataclass again from the data in the config.
This is not implemented now and has a large surface area. I am open to a pull request to add this functionality.

See my comment on #472.

Closing as a dup of #472 (but feel free to continue the discussion here).
