### ISSUE TITLE
DictConfig: Support float and bool keys

### ISSUE THREAD

**Issue by Jasha10** [omry/omegaconf#483]
Currently we have `DictKeyType = Union[str, int, Enum]`, i.e. `DictConfig` supports keys of type `str` or `int` or `Enum`.

This feature request is for expansion of `DictKeyType` to include `float` and `bool`:
`DictKeyType = Union[str, int, Enum, float, bool]`.

Additionally, given that `null` is a valid as a key in YAML, we could consider adding support for `None` as a `DictConfig` key, although I suspect that support for `None` may be more difficult than support for `float`/`bool`.

As a starting point for implementation, PR #454 implemented support for `int` key type in `DictConfig`.

**Comment by omry** [comment]
Thanks for filing @Jasha10.
I will welcome a diff from you adding support for those two types as keys but currently there are higher priority things to work so this is not planned for the next release of OmegaConf.
