### ISSUE TITLE
The flags cache may become inconsistent after serializing a container config

### ISSUE THREAD

**Issue by odelalleau** [omry/omegaconf#494]
**Describe the bug**

This test currently fails:

```python
def test_pickle_flags_consistency() -> None:
    cfg = DictConfig({"a": 0})
    cfg._set_flag("test", True)
    a_node = cfg._get_node("a")
    assert a_node is not None
    assert a_node._get_flag("test")

    cfg2 = pickle.loads(pickle.dumps(cfg))
    cfg2._set_flag("test", None)
    assert cfg2._get_flag("test") is None
    a2_node = cfg2._get_node("a")
    assert a2_node._get_flag("test") is None  # <-- FAIL!
```

This is because the flags cache of `cfg` is not preserved during serialization, while the flags cache of `cfg.a` is. As a result, when `cfg2`'s cache is invalidated (when setting its "test" flag to `None`), this is not propagated to its children, and the last line re-uses the (now invalid) cache.

**Potential solutions**

I can see at least two options to fix this issue:
1. Serialize the flags cache as an empty dict if it is not None (instead of ignoring it and setting it to `None` when de-serializing)
2. Also wiping the flags cache of non-container nodes during serialization

I'm leaning towards option 2, but I'm going to benchmark both options with the current benchmark and submit a PR with the fix

**Comment by omry** [comment]
Yup, definitely an oversight.
I thought the flags would not show up because they are not being copied by copy and deepcopy and forgot that pickle is using a different mechanism.

The correct fix is indeed to not serialize the flags on child nodes (2).
