### ISSUE TITLE
Feature: throw_on_missing keyword argument for OmegaConf.to_container

### ISSUE THREAD

**Issue by Jasha10** [omry/omegaconf#501]
# Feature:
Currently, calling `OmegaConf.to_container(cfg)` can result in a python object that contains some `"???"` MISSING strings.

I propose to add a `throw_on_missing` keyword argument to `OmegaConf.to_container`, so that the structure returned by `OmegaConf.to_container(cfg, throw_on_missing=True)` will raise `omegaconf.MissingMandatoryValue` if any missing values are encountered.

This way, if no `MissingMandatorValue` is raised, clients can be assured that the result of `to_container` does not contain any `"???"` strings.

To maintain backward compatibility, the default would be `throw_on_missing=False`.

**Comment by Jasha10** [comment]
I am working on a PR to implement this.

**Comment by omry** [comment]
Wouldn't resolve=True actually do what you want?
