### ISSUE TITLE
Interpolation success on merged configs depends on merge order

### ISSUE THREAD

**Issue by observingClouds** [omry/omegaconf#504]
**Describe the bug**
While the string interpolation after merging two configurations, in the example below `a` and `b`, that reference each other works fine independent of the merge order (`OmegaConf.merge(a,b)` and `OmegaConf.merge(b,a)` work both), it fails in case only a subset of the configuration is given as input to `OmegaConf.merge`.

**To Reproduce**
```
from omegaconf import OmegaConf
# config 1
a = OmegaConf.create({"a": {"conf": {"text":"${b.conf.text}"}}})
# config 2
b = OmegaConf.create({"b": {"conf": {"text":"btext"}}})

## Output as expected
print(OmegaConf.merge(b,a).a.conf.text)
# btext
print(OmegaConf.merge(a,b).a.conf.text)
# btext

## Merging subset of config
print(OmegaConf.merge(b, a.a).conf.text)
# btext
print(OmegaConf.merge(a.a, b).conf.text)
# results in
# ConfigKeyError: str interpolation key 'b.conf.text' not found
# 	full_key: a.conf.text
#	reference_type=Any
#	object_type=dict

```

**Expected behavior**
I expected that the merge process would work independent of the order of the configurations. While the above case can be solved by using the correct order, it is less clear how to solve this behaviour (issue?) in case config `b` would also contain string interpolations to `a`. Some keys would work for one order and another set of keys for another order.

**Additional context**
- [x] OmegaConf version: 2.0.5
- [x] Python version: 3.6.7
- [x] Operating system : macOS

**Comment by omry** [comment]
Please test on master (or the latest 2.1.0 dev release) as well.

**Comment by omry** [comment]
Checked and it's the same on master.

Took me some time to wrap my head around what you are doing (and I am still not sure I got it).

1. Interpolation is evaluated on access.
2. Merge does not change the parent of a config.

The combination of those two things results in the failure.
You can "fix" it by setting the parent of the resulting config:
```python
from omegaconf import OmegaConf

a = OmegaConf.create(
    {
        "a": {
            "conf": {
                "text": "${b.conf.text}",
            }
        },
    },
)
b = OmegaConf.create(
    {
        "b": {
            "conf": {
                "text": "btext",
            }
        }
    }
)

m1 = OmegaConf.merge(b, a.a)
assert m1._get_parent() is b._get_parent() is None

m2 = OmegaConf.merge(a.a, b)
assert m2._get_parent() is a.a._get_parent() is a

assert m1.conf.text == "btext"

# if you make b the parent of m2 (aka a.a) it will work:
m2._set_parent(b)
assert m2.conf.text == "btext"
```

I am not sure there is a good solution here. A node has only one parent and I can imagine scenarios where changing the parent to something that works for this case will fail in other cases. (not to mention that merge can take a sequence of configs, which one do you use as the parent?)

**Comment by observingClouds** [comment]
Thank you very much for your quick answer. I understand the setup and why this behaviour is occurring much better now. I simplified my example shown here and were indeed thinking about merging several configurations that reference each other in my application and not just two.

For my specific setup I'm now overwriting the parent with a merged version of all parents, such that all references are still valid:

```python
from omegaconf import OmegaConf

a = OmegaConf.create(
    {
        "a": {
            "conf": {
                "text": "${b.conf.text}",
            }
        },
    },
)
b = OmegaConf.create(
    {
        "b": {
            "conf": {
                "text": "btext",
            }
        }
    }
)

m2 = OmegaConf.merge(a.a, b)
# merge parents from configs to keep references valid
m2._set_parent(OmegaConf.merge(a,b))

assert m2.conf.text == "btext"
```
Thanks! Keep up this great work!

**Comment by omry** [comment]
In general, I recommend that you use [Hydra](hydra.cc) to do this kind of composition.
Are you aware of it?

**Comment by observingClouds** [comment]
Thanks, I wasn't aware of it.

**Comment by omry** [comment]
As you have noticed, config composition can be tricky.
Hydra provides a way to drive the config composition through the config itself (the Defaults List) and the command line.
