### ISSUE TITLE
OmegaConf 2.1: changes in DictConfig __getitem__ and __getattr__

### ISSUE THREAD

**Issue by omry** [omry/omegaconf#515]
An historical decision was to make `__getitem__` and `__getattr__` return None if a the input key is not found.
This is inconsistent with the behavior of plain dict and regular Python objects.

Fixing this is a breaking change, users depending on it will need small code changes.

```python
if cfg["some_attribute"] is not None:
   ...
```
And

```python
if cfg.some_attribute is not None:
   ...
```

Will have to be replaced with
```python
if "some_attribute" in cfg:
  ...
```

Note that is cfg is ducktyped as a type, you can use hasattr just like you would on an real instance of Config:
```python
def foo(cfg: Config):
  # before
  if cfg.some_attribute is not None: 
    ..
  # after
  if hasattr(cfg, "some_attribute"):
    ...
```

Note:
DictConfig put into struct mode is already behaving in the new way (raising exceptions).
This change should not affect most Hydra users because Hydra puts the cfg object into struct mode by default.

**Comment by odelalleau** [comment]
## **getattr**
``python
if cfg.some_attribute is not None:
   ...
```
Will have to be replaced with
> 
> ```python
> if hasattr(cfg, "foo"):
>   ...
> ```
> 
> ## **getitem**
> ```python
> if cfg["some_attribute"] is not None:
>    ...
> ```
> 
> Will have to be replaced with
> 
> ```python
> if "foo" in cfg:
>   ...
> ```
