### ISSUE TITLE
[Discussion] Resolver cache behavior

### ISSUE THREAD

**Issue by odelalleau** [omry/omegaconf#526]
Creating this issue to discuss potential changes to the cache behavior, following discussions in #445 

Open questions:

* Should resolvers be cached or not by default?
* How should the cache key be computed?

For the first question, the current behavior is to cache by default, but maybe this mostly makes sense for "non-deterministic" resolvers like random / time, to avoid config options to change on each access (while it may not be needed for most resolvers). Also, the answer may depend on the next question as well.

For the second question, we discussed several options (in the context of nested interpolations):

1. Current behavior in #445  as of 2021-02-08: use the inputs to the resolver functions as cache key. This may require caching arbitrary data (ex: outputs of other resolvers).
2. Use the string literal as cache key (ex: if `a` is equal to 0, the cache key for `${f:${a}}` would be `"${a}"`and not `0`). This makes the cache simpler, while losing the ability to dynamically depend on the value of other variables.
3. Also account for the node itself in the cache key. For instance, with a config `{"a": "${random:}", "b": "${random:}"}` someone is likely to want `a` and `b` to be two different numbers, while remaining fixed on each access.
4. (Not discussed so far, new idea I'm proposing) Let the user decide whether to cache or not (default: not cached), and which key to use. It would be a bit more verbose but more explicit and flexible. One possible syntax could be to use `[X]` to say that the resolver's output should be stored under key `X`, with `[]` implicitly using the current node as cache key. My previous example would become `{"a": "${random[]:}", "b": "${random[]:}"}`. And if for any reason we wanted both a and b to use the same random sample, it would be instead `{"a": "${random[sample]:}", "b": "${random[sample]:}"}`. The kind of flexible use that it would enable is something like `{"a": "${f[${b}, ${c}]: ${b}, ${c}, ${d}}"}` where the cache key depends on b and c but not on d.

I haven't thought through all these options in depth yet, just throwing them out there to serve as a basis for dicussion.

**Comment by omry** [comment]
Regardless of the default value for caching (I can see pros and cons in either choice), I am leaning toward making things as simple as they can be.
The motivation for introducing the cache was non-deterministic functions (specifically `time()`, not the performance aspect).

I think you are rightfully focusing on the cache key here. it's the bigger issue.
using arbitrary data as cache key seems dangerous to me. It's both a performance risk but also instability risk (a function that suddenly return an un-hashable value will cause issues in some scenarios).
In fact, hashing to determine if to use a cache or not can be more expensive that just computing the values in some scenarios (especially in the presence of high performance primitives like tensors).

> 1. Current behavior in #445 as of 2021-02-08: use the inputs to the resolver functions as cache key. This may require caching arbitrary data (ex: outputs of other resolvers).

This is also the behavior in 2.0, with the exception that there is no risk of using arbitrary data as the cache key.

> 2. Use the string literal as cache key (ex: if a is equal to 0, the cache key for ${f:${a}} would be "${a}"and not 0). This makes the cache simpler, while losing the ability to dynamically depend on the value of other variables.

I am leaning toward this.
Not only will the caching be simpler and more robust, it's probably also easier for users to understand the behavior.

> 3. Also account for the node itself in the cache key. For instance, with a config {"a": "${random:}", "b": "${random:}"} someone is 
likely to want a and b to be two different numbers, while remaining fixed on each access.

This is more about the cache scope. than about the key.
The data model actually supports a resolver_cache in every config node, but the implementation is always using the config cache at the config root.
I can imagine scenarios where you want this to pass:
```python
def test_resolver_cache_3(restore_resolvers: Any) -> None:
    OmegaConf.register_resolver("random", lambda _: random.randint(0, 10000000))
    c = OmegaConf.create(
        {
            "k1": "${random:_}",
            "k2": "${random:_}",
        }
    )
    assert c.k1 == c.k1
    assert c.k2 == c.k2
    assert c.k1 != c.k2
```

Currently it fails on master, but this makes it pass (and breaking other things of course):
```diff
$ git diff omegaconf
diff --git a/omegaconf/base.py b/omegaconf/base.py
index 46e1850..db75622 100644
--- a/omegaconf/base.py
+++ b/omegaconf/base.py
@@ -440,7 +440,7 @@ class Container(Node):
         else:
             resolver = OmegaConf.get_resolver(inter_type)
             if resolver is not None:
-                root_node = self._get_root()
+                root_node = self._get_node(key)
                 try:
                     value = resolver(root_node, inter_key)
                     return ValueNode(
```

As could in principle makes the use_cache flag an enum with multiple choices and allow user to differentiate on registration:
```
caching: [disabled,config_scope,node_scope]
```
(Current behavior is config_scope).

> 4. (Not discussed so far, new idea I'm proposing) Let the user decide whether to cache or not (default: not cached), and which key to use.

In the interest if simplicity, I suggest that we delay this until we have a concrete use case that needs this kind of flexibility.
The current cache behavior is something no one have complained about so far. I don't think it's worth adding a ton of flexibility there at this point.

**Comment by odelalleau** [comment]
Works for me. If we go with option (2) though I would prefer the cache not to be enabled by default (forcing people to specify the `use_cache`/`caching` argument when registering their resolver in 2.1, and making it disabled by default in 2.2) as I think it's a bit surprising that `"${a}"` would change with `a` but not `${add:${a}, 1}` (random example with `a+1`)

Also should it be part of #445 or in a follow-up PR? (I prefer the latter, but it would mean that the master branch would go through two consecutive breaking changes in a row)

**Comment by omry** [comment]
> Works for me. If we go with option (2) though I would prefer the cache not to be enabled by default (forcing people to specify the use_cache/caching argument when registering their resolver in 2.1, and making it disabled by default in 2.2) as I think it's a bit surprising that "${a}" would change with a but not ${add:${a}, 1} (random example with a+1)

I don't have a strong opinion about caching enabled or disabled by default.
If we want to disable it by default we can do it directly in 2.1 because users are already using a new API. (the how to migrate page should explain the behavior change).
not sure I understand your example with add though.

> Also should it be part of #445 or in a follow-up PR? (I prefer the latter, but it would mean that the master branch would go through two consecutive breaking changes in a row)

445 already have a lot of changes related to the register_resolver API.
If it's not too much work, I would rather that we remove those changes from it and only make the minimal changes there to keep the existing API working in the same way and have all the changes in a followup PR.
At minimum, we could postpone the encouragement of users to use new_register_resolver (via the deprecation warning) until we finalize it in master.

**Comment by odelalleau** [comment]
> not sure I understand your example with add though.

Not a big deal, but what I had in mind was a case where someone would start with e.g. `{"a": 10, "b": "${a}"}`, then realize later that what they reallly want is `b` to be equal to `a+1` instead of `a`, and implementing a custom resolver `add` for this purpose (setting `b` to `${add:${a},1}`). It may be surprising that `b` suddenly stops dynamically changing with `a`.

> 445 already have a lot of changes related to the register_resolver API.
> If it's not too much work, I would rather that we remove those changes from it and only make the minimal changes there to keep the existing API working in the same way and have all the changes in a followup PR.
> At minimum, we could postpone the encouragement of users to use new_register_resolver (via the deprecation warning) until we finalize it in master.

I'd rather go with the latter option to avoid un-doing a lot of stuff and re-doing it afterwards.

One question though is what "keep the existing API working" means in the context of nested interpolations? (which didn't work before). In my current implementation of #445, trying to use nested interpolations will raise an error like this:
```
ValueError: Resolver 'f' was called with argument '${b}' that appears to be an interpolation. Nested interpolations are not supported for resolvers registered with `legacy_register_resolver()`, please use `new_register_resolver()` instead (see https://github.com/omry/omegaconf/issues/426 for migration instructions).
```

**Comment by omry** [comment]
> Not a big deal, but what I had in mind was a case where someone would start with e.g. {"a": 10, "b": "${a}"}, then realize later that what they reallly want is b to be equal to a+1 instead of a, and implementing a custom resolver add for this purpose (setting b to ${add:${a},1}). It may be surprising that b suddenly stops dynamically changing with a.

Definitely a convincing argument to go without cache by default.

> One question though is what "keep the existing API working" means in the context of nested interpolations? (which didn't work before). In my current implementation of #445, trying to use an interpolation as input to a resolver will raise an error like this:

No, this is fine. It didn't work before so this doesn't break anything.
You can keep the custom error.

**Comment by odelalleau** [comment]
> You can keep the custom error.

Ok good.

Also, I just had a quick look and use string literals as cache key in #445 is essentially a one-line change. So no reason not to do it if that's the option you prefer.

**Comment by omry** [comment]
Sounds good.
Let's still do it in a followup.

With this discussion concluded, who has the ball on 445?

**Comment by odelalleau** [comment]
Based on all discussion so far, here is my current plan regarding the cache:
* Go with option (2) = cache key based on the string literals
* Disable the cache by default in `register_new_resolver()`
* Also disable the cache in the new `oc.env` resolver (while keeping it enabled in the deprecated `env` resolver)

**Comment by omry** [comment]
Sounds right.
We can use #383 for discussions about the new env resolver and eventually we can add dedicated issue to act as a an infgo link in the deprecation warning of people using the old env resolver.
