### ISSUE TITLE
DictConfig.get('missing') inconsistent with python dict.get('missing')

### ISSUE THREAD

**Issue by Jasha10** [omry/omegaconf#527]
This issue describes an inconsistency between `DictConfig` and python's standard `dict`:
```python3
{"a": 123}.get("b")  # returns None
OmegaConf.create({"a": 123}).get("b")  # currently throws a `ConfigKeyError`
```
The issue will be resolved in a pull request coming soon, so that `DictConfig.get` returns `None` if `key` is not found.

**Comment by omry** [comment]
Thanks.
Can you pull out the fix into it's own pull request? It can have a minimal test that can later be integrated into the more systemic test that discovered it.
