### ISSUE TITLE
Allow resolvers to output a dict / list to generate a DictConfig / ListConfig

### ISSUE THREAD

**Issue by odelalleau** [omry/omegaconf#540]
As discussed in https://github.com/facebookresearch/hydra/issues/1389, converting a resolver's output from dict / list to DictConfig / ListConfig would make it easier to generate parts of a config.

For instance:

```python
    OmegaConf.register_new_resolver("make_x", lambda: {"a": 0, "b": 1})
    cfg = OmegaConf.create({"x": "${make_x:}"})
    assert isinstance(cfg.x, DictConfig)
    assert cfg.x.a == 0 and cfg.x.b == 1
```

**Comment by omry** [comment]
This interacts with the idea to validate interpolations to ensure their type is matching.

**Comment by odelalleau** [comment]
> This interacts with the idea to validate interpolations to ensure their type is matching.

Yes, I actually implemented it in the same commit

**Comment by omry** [comment]
We backtracked on this one, right?
We still have this in the news dir:
```
- Custom resolvers can now generate transient config nodes dynamically. ([#540](https://github.com/omry/omegaconf/issues/540))
```

**Comment by odelalleau** [comment]
Yeah, the news item isn't entirely wrong since you *can* generate List/DictConfigs from a custom resolver now, but not exactly as per this issue.
=> I would either remove it or update this issue (there are two ways to do it now -- either by directly creating a container whose parent is set to `_parent_`, or by combining with `oc.create`)

**Comment by omry** [comment]
we have a news item for oc.create so I am just removing this one.

**Comment by masteranza** [comment]
@omry Could you link to the news item you're mentioning? I'm hoping to find a workaround for this: https://github.com/facebookresearch/hydra/issues/1389

**Comment by omry** [comment]
news fragments are just one-liners that are later copied into the release notes. this will not help you.

**Comment by odelalleau** [comment]
@masteranza maybe the comment I just added in that issue can help you? https://github.com/facebookresearch/hydra/issues/1389#issuecomment-900570245
