### ISSUE TITLE
Deprecate `OmegaConf.is_none()`

### ISSUE THREAD

**Issue by odelalleau** [omry/omegaconf#547]
**PROBLEM**

With the change to `OmegaConf.is_missing()` in #545, the current behavior of `OmegaConf.is_none()` in OmegaConf 2.0 can be confusing (because it resolves interpolations, while `OmegaConf.is_missing()` doesn't).

In addition, `OmegaConf.is_none()` has potentially non-intuitive behavior in situations where the key can't be resolved (see below for details).

**SOLUTION**
`OmegaConf.is_none()` is being deprecated in OmegaConf 2.1, and will be removed in OmegaConf 2.2

**MIGRATION INSTRUCTIONS**

*Please do not hesitate to open an issue if you run into problems that the instructions below do not address.*

__Scenario 1 -- Your code is checking a specific key:__
```python
OmegaConf.is_none(cfg, "foo")
OmegaConf.is_none(cfg, key)
```

It is recommended to change these to:
```python
cfg.foo is None
cfg[key] is None
```

Note however that when using this new syntax, an exception may be raised when accessing the key, while `OmegaConf.is_none()` used to silence such exceptions. If you want to keep the exact (but possibly unintuitive) behavior from before, you can implement your own `is_none()` function as follows:

```python
def is_none(obj: Container, key: Union[int, DictKeyType]) -> bool:
    try:
        return obj[key] is None
    except ConfigKeyError:
        return True  # `True` if the key does not exist in the config
    except (InterpolationResolutionError, MissingMandatoryValue):
        return False  # `False` if it is either missing ("???") or an invalid interpolation
```

__Scenario 2 -- Your code is not providing a key:__

```python
OmegaConf.is_none(obj)
```

There is currently no plan to keep supporting this usage in OmegaConf 2.2. If you need it, please open an issue explaining why.

**Additional context**
See discussion in https://github.com/omry/omegaconf/pull/545#discussion_r577239021

Dev note: at the same time, the internal `Node._is_none()` can be modified to *not* resolve interpolations.

**Comment by Jasha10** [comment]
> => let's deprecate `OmegaConf.is_none()`, instructing users to use `cfg.foo is None` instead.

I like this -- `cfg.foo is None` is more pythonic than `OmegaConf.is_none(cfg)`.
