### ISSUE TITLE
Can a schema be changed dynamically?

### ISSUE THREAD

**Issue by cgebbe** [omry/omegaconf#551]
**Is your feature request related to a problem? Please describe.**
Assume we want to perform logging either to a file or to a stream. However, depending on the choice the required parameters change!

Another similar scenario is choosing a CNN architecture. The choice of the architecture (e.g. ResNet or EfficientNet) affects the possible parameters.

**Describe the solution you'd like**
Based on the logging scenario, something like this would be great. However, how could I switch between FileLog or StreamLog?

```
@dataclass
class Log:
    pass

@dataclass
class FileLog(Log):
    file : str = MISSING
    rotation: int = MISSING

class StreamLog(Log):
    stream_type: str = MISSING


@dataclass
class MyConfig:
    log : Log

```

**Describe alternatives you've considered**
I believe Hydra allows this, see https://hydra.cc/docs/next/tutorials/structured_config/schema/ . I am mostly curious whether it is also possible using pure OmegaConf

**Comment by omry** [comment]
Try this:
```python
from dataclasses import dataclass
from omegaconf import OmegaConf, MISSING

@dataclass
class Log:
    pass

@dataclass
class FileLog(Log):
    file: str = MISSING
    rotation: int = MISSING


class StreamLog(Log):
    stream_type: str = MISSING


@dataclass
class MyConfig:
    log: Log


cfg = OmegaConf.merge(MyConfig, {"log": FileLog})
assert OmegaConf.get_type(cfg.log) == FileLog

cfg = OmegaConf.merge(MyConfig, {"log": StreamLog})
assert OmegaConf.get_type(cfg.log) == StreamLog

cfg.log = FileLog(file="foo")
assert OmegaConf.get_type(cfg.log) == FileLog
print(cfg)
```

Can you share why you want to do it manually instead of using Hydra to do that?

**Comment by Jasha10** [comment]
> ```python
> class StreamLog(Log):
>     stream_type: str = MISSING
> ```

I think you'll probably want a `@dataclass` decorator for `StreamLog` too.

**Comment by omry** [comment]
I agree. turns out it works anyway because it inherits being a dataclass but it's definitely better to decorate it properly.
