### ISSUE TITLE
OmegaConf.to_yaml fails when passed a plain `str`

### ISSUE THREAD

**Issue by Jasha10** [omry/omegaconf#560]
You can pass `OmegaConf.to_yaml` a `dict` or `list` with no problem:
```python
>>> OmegaConf.to_yaml(["abc"])
'- abc\n'
```
But if you pass a `str`, you get an `AssertionError`:
```python
>>> OmegaConf.to_yaml("abc")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/Jasha10/omegaconf/omegaconf/omegaconf.py", line 815, in to_yaml
    cfg = _ensure_container(cfg)
  File "/home/Jasha10/omegaconf/omegaconf/_utils.py", line 694, in _ensure_container
    assert OmegaConf.is_config(target)
AssertionError
```

# Desired Behavior:
- a more informative error message, such as `"to_yaml got a bad input of type <class 'str'>"`.

Does it make sense to do anything besides throwing an error? The output of the `to_yaml` function is a string, so I'm not sure what would be the correct way to handle inputs that are strings.

**Comment by omry** [comment]
Yes, I think it makes sense. assertion errors should be not be raised for bad user inputs, only for internal bugs.

**Comment by Jasha10** [comment]
> I think a plain ValueError explaining the valid inputs to the function will be good enough.

Sounds good.
