### ISSUE TITLE
Ensure all exceptions raised while resolving interpolations derive from a common class

### ISSUE THREAD

**Issue by odelalleau** [omry/omegaconf#561]
**Is your feature request related to a problem? Please describe.**

Currently, many types of exceptions can be raised when an issue occurs during interpolation resolution, which makes it difficult to separate interpolation errors from other exceptions, and to identify what went wrong during resolution.

**Describe the solution you'd like**

Have all interpolation-related exceptions be either `InterpolationResolutionError` or a subclass of it. The subclasses would be:
* `UnsupportedInterpolationType` (trying to call a custom resolver that does not exist)
* `InterpolationKeyError` (trying to interpolate a node that does not exist)
* `InterpolationToMissingValueError` (trying to interpolate a node that is missing, i.e., set to `"???"`)

**Additional context**
This is addressed by #545. Creating this issue to keep track of the changes.

**Comment by omry** [comment]
Since this (and other issues are for 2.1, can you set the milestone for it and others accordingly)?

**Comment by odelalleau** [comment]
> Since this (and other issues are for 2.1, can you set the milestone for it and others accordingly)?

All done!
