### ISSUE TITLE
Deprecation of the `env` resolver for variable environment interpolations

### ISSUE THREAD

**Issue by odelalleau** [omry/omegaconf#573]
In OmegaConf 2.1, the `env` resolver is being deprecated in favor of a new `oc.env` resolver.

To migrate to this new resolver:
* Replace `${env:MYVAR}` with `${oc.env:MYVAR}`
* Consider whether your config or code may need to be updated due to the following three main differences with `oc.env`:
  1. Contrary to `env`, `oc.env` does not use the resolver cache: this means that if `MYVAR` is updated within the program's process, the value of `${oc.env:MYVAR}` will change accordingly.
  2. Contrary to `env`, `oc.env` does not attempt to convert booleans, integers and floats: instead, the string representation of the environment variable is always returned. If you wish to convert from string to a different type, you may either take advantage of automatic conversion for typed nodes (see https://github.com/omry/omegaconf/issues/488#issuecomment-774490332), or use the new `oc.decode` resolver (see #574)
  3. The default value of `oc.env` can only be a string or `null`. For instance, `${env:MISSING,123}` should be replaced with `${oc.env:MISSING,"123"}` (and if the `MISSING` environment variable does not exist then the string `"123"` will be returned instead of the integer `123`)

**Comment by omry** [comment]
> The default value of oc.env can only be a string or null. For instance, ${env:MISSING,123} should be replaced with ${oc.env:MISSING,"123"}, and if the MISSING environment variable does not exist the string "123" will be returned instead of the integer 123.

I think it's reasonable to convert the default to str if it's not None in the new `oc.env` resolver.
Any thoughts?

**Comment by odelalleau** [comment]
> > The default value of oc.env can only be a string or null. For instance, ${env:MISSING,123} should be replaced with ${oc.env:MISSING,"123"}, and if the MISSING environment variable does not exist the string "123" will be returned instead of the integer 123.
> 
> I think it's reasonable to convert the default to str if it's not None in the new `oc.env` resolver.
> Any thoughts?

No strong objection, but in general I try to avoid implicit conversions unless they really make life easier. The kind of tricky situation that could happen with implicit conversion would be `${oc.env:COMMIT_ID, 540e327}` returning the string `"inf"` in case `COMMIT_ID` is missing (while throwing an error would point directly at the problem).

Happy to change it though if you still prefer the automatic conversion to string.

**Comment by omry** [comment]
Okay, let's leave it as is and see if we run into cases where implicit conversion would be really useful.

**Comment by odelalleau** [comment]
This is an example of how to take advantage of the automatic conversion for typed nodes (see also the [documentation](https://omegaconf.readthedocs.io/en/latest/structured_config.html#interpolations)):

```python
import os
from dataclasses import dataclass

from omegaconf import II, OmegaConf


@dataclass
class Config:
    some_int: int = II("oc.env: SOME_INT, '123'")
    some_bool: bool = II("oc.env: SOME_BOOL, 'True'")


cfg = OmegaConf.structured(Config)

assert cfg.some_int == 123
assert cfg.some_bool is True

os.environ["SOME_INT"] = "456"
os.environ["SOME_BOOL"] = "false"

assert cfg.some_int == 456
assert cfg.some_bool is False
```
