### ISSUE TITLE
Disable throw_on_missing_key

### ISSUE THREAD

**Issue by carmocca** [omry/omegaconf#577]
**Describe the bug**

Accessing a missing attribute raises an error after 2.1.0.dev18

Is this not allowed anymore? Is there a flag to use the old behaviour?

**To Reproduce**

```python
from omegaconf import OmegaConf

x = OmegaConf.create({"foo": "bar"})

# 2.1.0.dev20
print(x.missing)  # ConfigAttributeError: Missing key missing
```

**Expected behavior**

```python
# 2.1.0.dev18
print(x.missing)  # None
```

**Additional context**
- [x] OmegaConf version: 2.1.0.dev20
- [x] Python version: 3.9.1
- [x] Operating system : MacOS
- [x] Minimal repro

**Comment by omry** [comment]
This is one of the breaking changes in OmegaConf 2.1.
The motivation is to make OmegaConf DictConfig consistent with plain dict (thus allowing people to use it as a drop-in-replacement).

There is no flag to get the new behavior.
You can use get() instead:

```python
print(x.get("missing"))  # None
```
