### ISSUE TITLE
When validating the assignment to a list, `None` is not properly validated

### ISSUE THREAD

**Issue by odelalleau** [omry/omegaconf#579]
**Describe the bug**
The following code should crash (because `None` should be rejected) but currently does not:

```python
@dataclass
class Foo:
    bar: List[int] = "???"

cfg = OmegaConf.structured(Foo)
cfg.bar = [1, None]
```

**Expected behavior**
There should be an exception because it is `List[int]` and not `List[Optional[int]]`.

**Additional context**
- [X] OmegaConf version: current master (cb5e556)

**Comment by Jasha10** [comment]
Same issue for `Dict`:
```python
@dataclass
class Foo:
    bar: Dict[str, int] = "???"

cfg = OmegaConf.structured(Foo)
cfg.bar = {"foo": 1, "bar": None}
```
The above should crash but does not.

**Comment by Jasha10** [comment]
Reopened by PR #705.

**Comment by omry** [comment]
@Jasha10, you left the news fragment when you reverted. (clearing it).

**Comment by Jasha10** [comment]
Oops. Sorry about that.
