### ISSUE TITLE
Dict subclass data not preserved during assignment

### ISSUE THREAD

**Issue by Jasha10** [omry/omegaconf#584]
**Describe the bug**
When a `Dict` subclass is assigned to an omegaconf Node, the data from the dict is thrown away.

**To Reproduce**
```python
$ cat tmp.py
from dataclasses import dataclass
from typing import Dict
from omegaconf import OmegaConf

@dataclass
class Str2Str(Dict[str, str]):
    x: int = 0

a = Str2Str()
assert a.x == 0
a["y"] = 1
assert a["y"] == 1
cfg_a = OmegaConf.create(a)
assert cfg_a.x == 0
assert "y" in cfg_a
assert cfg_a["y"] == 1
```
```bash
$ python tmp.py
Traceback (most recent call last):
  File "/Users/lappy486/omegaconf/tmp.py", line 18, in <module>
    assert "y" in cfg_a
AssertionError
```

**Expected behavior**
We expect the above assertions to succeed.

**Additional context**
- OmegaConf version: 2.1.0dev20
- Python version: 3.9.1
- Operating system : MacOS

**Comment by Jasha10** [comment]
Originally based on comments here: https://github.com/omry/omegaconf/pull/581#discussion_r589148187

**Comment by omry** [comment]
Yup, definitely smells like a bug.
