### ISSUE TITLE
Example with interpolation not working

### ISSUE THREAD

**Issue by gygabyte017** [omry/omegaconf#596]
**Describe the bug**
Interpolation with relative levels seems not to be working.

**To Reproduce**
```
from omegaconf import OmegaConf

s = """
server:
  host: localhost
  port: 80

client:
  url: http://${server.host}:${server.port}/
  server_port: ${server.port}
  # relative interpolation
  description: Client of ${.url}
"""

conf = OmegaConf.create(s)
print(conf.client.url)  # Works
print(conf.client.description)  # Error
```

**Expected behavior**
Expected to be printed `Client of http://localhost:80/`, instead I get:
```
omegaconf.errors.ConfigKeyError: str interpolation key '.url' not found
        full_key: client.description
        reference_type=Any
        object_type=dict
```

**Additional context**
- [X] OmegaConf version: 2.0.6
- [X] Python version: 3.8.8
- [X] Operating system : Windows 10
- [X] Please provide a minimal repro

**Comment by omry** [comment]
Relative interpolation is not supported in OmegaConf 2.0.
The correct doc for 2.0 is https://omegaconf.readthedocs.io/en/2.0_branch/.

If you want to try relative interpolations, you can use the dev build (`pip install --pre --upgrade omegaconf`)
