### ISSUE TITLE
Omegaconf.create accept Protocol like Class

### ISSUE THREAD

**Issue by tamuhey** [omry/omegaconf#61]
Hi, thank you for this great repo!

I want to instantiate `omegaconf.Config` with protocol like class to tell IDE what member the config have, that is:

```python
class A:
    a: int = 1

cfg: A = omegaconf.OmegaConf.create(A)
print(cfg.a)
```
```
1
```

**Comment by omry** [comment]
Hi @tamuhey,
This seems very specific to some IDEs.
Is there any common standard to what a "protocol like class" is?
Can you achieve the same results by doing something like:
```
class A:
    a: int = 1

cfg = your_create(A)
print(cfgf.a)
```
?

**Comment by omry** [comment]
Can you explain what is the common use pattern here?
What are you getting by using OmegaConf? 
For example, are you merging your config objects with anything else?

**Comment by tamuhey** [comment]
Sorry for not explaining enough.

1. "Protocol like class" means [typing.Protocol](https://docs.python.org/3/library/typing.html#typing.Protocol) like class that provides structural subtyping for type checkes.

2. common use pattern

- The class (`class A` in previous example) provides structural subtyping, and you can use tab completion with IDE (e.g. VSCode)
- The class also provides default value of config in its class variable.

3. > For example, are you merging your config objects with anything else?

Yes, I'm merging config objects, that's why I'm using omegaconf.
For example:

```python
class ConfA:
    a: int = 1


default_config_a = create_config(ConfA)


def fn_a(cfg: ConfA = default_config_a):
    print(cfg.a)


class ConfB:
    b: str = "foo"


default_config_b = create_config(ConfB)


def fn_b(cfg: ConfB = default_config_b):
    print(cfg.b)


default_config = omegaconf.OmegaConf.create(
    {"a": default_config_a, "b": default_config_b, "foo": 10}
)


def fn_manager(cfg=default_config):
    fn_a(cfg.a)
    fn_b(cfg.b)
    print(cfg.foo)


fn_manager()
```
```
1
foo
10
```

**Comment by omry** [comment]
When I asked about merge,I was thinking more about OmegaConf.merge(conf1, conf2, ..) or conf1.merge_with(conf2, ...).

OmegaConf is surprisingly complex for such a small library and I want to very careful adding additional API surface area.
You already asked (more or less) the same question at the Hydra repo, the answer there was that it does not belong in Hydra. the same goes for OmegaConf - which is even a lower level library.

It looks like you should be able to use an aux creation utility that converts the Prototype to a dictionary, and then just pass that dictionary to OmegaConf.create, right?

```
conf = OmegaConf.create(prototype_to_dict(ConfA))
```

By the way, are you still using Hydra or did you decide to use OmegaConf directly?

**Comment by tamuhey** [comment]
Thanks! I got it. 

I paste the `protptype_to_dict` code snippet for users with the same problem.

```python
def prototype_to_dict(proto_cls):
    return {
        k: v for k, v in vars(proto_cls).items() if not callable(v) and not k.startswith("__")
    }
```

> By the way, are you still using Hydra or did you decide to use OmegaConf directly?

I'm using both of them - Hydra for applications, OmegaConf for libraries.

**Comment by omry** [comment]
Awesome.
Also glad to hear you are using both Hydra and OmegaConf.

Mind sharing some details about the projects you are using them for?
Also, is any those projects is or will be open sourced?

**Comment by tamuhey** [comment]
@omry I'm sorry I cannot tell you the details of the projects... I'll tell you if I can make the project public!

**Comment by omry** [comment]
No worries!

By the way, I just released 1.4.0rc3, I am expecting to release 1.4.0 from it soon (unless some new bugs comes up).
Please try it out if you can.

**Comment by omry** [comment]
@tamuhey, please join the Hydra chat. I am discussing this use case in the OmagaConf channel.

**Comment by omry** [comment]
https://hydra-framework.zulipchat.com
