### ISSUE TITLE
Improve documentation of built-in resolvers

### ISSUE THREAD

**Issue by odelalleau** [omry/omegaconf#619]
**Is your feature request related to a problem? Please describe.**

See https://github.com/omry/omegaconf/pull/606#discussion_r596482404

**Additional context**

I have a WIP branch (not up for PR yet) that moves built-in resolvers to a different file => better wait until this is done before addressing this documentation issue

**Comment by omry** [comment]
I think this is done?

**Comment by odelalleau** [comment]
> I think this is done?

Yes, fixed by #679 => closing
