### ISSUE TITLE
Possible way to convert `omegaconf.listconfig.ListConfig` into python list?

### ISSUE THREAD

**Issue by hwijeen** [omry/omegaconf#620]
Hi, thank you for the great library! I recently became a fan of omegaconf and hydra.

Is there any way I could get a list of values in a python list instead of ListConfig?
When my `config.yaml` looks like this,
```yaml
# @package _global_
a: [1,2,3]
```
the value I get for a in python is the following.
```python
@hydra.main(config_path="config", config_name="config")
def main(cfg):
    print(cfg.a)  # [1, 2, 3]
    print(type(cfg.a))  #  omegaconf.listconfig.ListConfig
```

The problem is that the libraries I am using (huggingface datasets, transformers) do not support ListConfig.
For example, the canonical way of loading data with `datasets.load_dataset(data_files=data_files)` does not work when `data_files` is ListConfig, whereas it does with python list.
I guess it is not omegaconf's fault, but it would be wonderful if ListConfig work seamlessly with List!

Could you give me a help?

**Comment by hwijeen** [comment]
The hack that I am using right now is
```python
data_files = list(cfg.data_files)
OmegaConf.set_struct(cfg, False) # to enable 'pop'
cfg.pop(**cfg, data_files=data_files)
```
but I would appreciate if you could share a better way!

**Comment by omry** [comment]
Yup, go over the docs :).

https://omegaconf.readthedocs.io/en/2.0_branch/usage.html#omegaconf-to-container
