### ISSUE TITLE
Add new resolver `oc.cache`

### ISSUE THREAD

**Issue by odelalleau** [omry/omegaconf#633]
**Is your feature request related to a problem? Please describe.**

What if you want to use an existing resolver registered with `use_cache=False`, but would like the cache to be enabled?
Currently, the only option is to re-register the same function under a different name with `use_cache=True`.

**Describe the solution you'd like**

Add a new resolver `oc.cache` that could be used this way:
```yaml
foo: ${oc.cache:${oc.env:VAR}}
```

`oc.cache` would essentially just be the identity registered with `use_cache=True`.

For convenience an optional "key" argument could be specified, which would allow to use a different cache key in different places:

```yaml
foo1: ${oc.cache:${oc.env:VAR}, key1}
foo2: ${oc.cache:${oc.env:VAR}, key2}
```
==> both `foo1` and `foo2` would be cached, but under different keys (so they could be different).

**Comment by omry** [comment]
I think caching behavior is subject to changes in the future.
This will make it harder to change the behavior in the future, so I vote that we avoid it for now.

**Comment by odelalleau** [comment]
Alright, closing it for now then. Just putting the recipe here in case it may help others:

```python
import time
from typing import Any
from omegaconf import OmegaConf

# Custom cache resolver

def cache(value: Any, key: Any = None):
    return value

OmegaConf.register_new_resolver("cache", cache, use_cache=True)

# Usage example

OmegaConf.register_new_resolver("time", time.time)
cfg = OmegaConf.create({"now1": "${cache:${time:}, t1}", "now2": "${cache:${time:}, t2}"})

print(f"now1 = {cfg.now1}")
time.sleep(1)
print(f"now2 = {cfg.now2}")
time.sleep(1)
print(f"now1 = {cfg.now1}")
print(f"now2 = {cfg.now2}")
```
Example output:
```
now1 = 1616271818.101857
now2 = 1616271819.108407
now1 = 1616271818.101857
now2 = 1616271819.108407
```

**Comment by omry** [comment]
Cool, updated the title to reflect what this is.
