### ISSUE TITLE
Error interpolating environment variable with '?'

### ISSUE THREAD

**Issue by dustyhorizon** [omry/omegaconf#634]
**Describe the bug**
'?' in environment variable throws exception whilst interpolating it in omegaconf.

**To Reproduce**
```
SOME_VAR='https://someurl.com?query=1'
run some python script with ${oc.decode:${oc.env:SOME_VAR,null}}
=>  omegaconf.errors.InterpolationResolutionError: GrammarParseError raised while resolving interpolation: token recognition error at: '?' whilst accessing config
```

**Expected behavior**
No errors should be encountered

**Additional context**
- [x] OmegaConf version: ref a1c00046ab8a34f12e99d3981d97672cda5af4c1
- [x] Python version: 3.9.2
- [ ] Operating system: Debian Buster
- [ ] Please provide a minimal repro

**Comment by omry** [comment]
@odelalleau, can you take a look?

**Comment by omry** [comment]
@dustyhorizon, what is your motivation for using oc.decode? if you just want the string using this should work:
```
${oc.env:SOME_VAR,null}
```

**Comment by odelalleau** [comment]
> @dustyhorizon, what is your motivation for using oc.decode? if you just want the string using this should work:
> 
> ```
> ${oc.env:SOME_VAR,null}
> ```

What @omry  said.

`oc.decode` should only be used if you want to "process" a string, e.g. to convert it into a different data type automatically (`"123"` -> `123`) or resolve an interpolation (`"${foo}"` -> `"stuff"` if option `foo` is the string `"stuff"`).

@dustyhorizon let me know if the doc from https://github.com/omry/omegaconf/blob/master/docs/source/usage.rst isn't clear enough, maybe it should be improved.

**Comment by odelalleau** [comment]
Also, if you actually need `oc.decode` because you expect strings that will require being converted to a different type, then the solution is to quote your string: `SOME_VAR='"https://someurl.com?query=1"'`

**Comment by odelalleau** [comment]
@dustyhorizon I'm going to close this for now since hopefully the above comments should help you solve this issue, but feel free to re-open in case you may haver further questions on this topic.
