### ISSUE TITLE
Resolver cache isn't cleared when clearing resolvers

### ISSUE THREAD

**Issue by odelalleau** [omry/omegaconf#637]
**Describe the bug**
In the following example I would expect the output to be `2` instead of `1`, because the resolver has changed. However this isn't the case because the old cache is re-used.

```python
OmegaConf.register_new_resolver("test", lambda x: x + 1, use_cache=True)
cfg = OmegaConf.create({"x": "${test:0}"})
assert cfg.x == 1
OmegaConf.clear_resolvers()
OmegaConf.register_new_resolver("test", lambda x: x + 2, use_cache=True)
assert cfg.x == 1  # this assert succeeds on master but it should be 2!
```

**Comment by omry** [comment]
The resolvers cache is on the config objects. One should use OmegaConf.clear_cache(cfg).
I am also not expecting people to dynamically change the meaning of resolvers.

**Comment by odelalleau** [comment]
Ok, closing then (will not fix)

**Comment by omry** [comment]
While this is fixable, I think the added complexity is not worth it.
