### ISSUE TITLE
Structured config from yaml (serialization)

### ISSUE THREAD

**Issue by cgebbe** [omry/omegaconf#654]
**Is your feature request related to a problem? Please describe.**
Structured configs are great. Use case e.g. the following

```
from dataclasses import dataclass
from omegaconf import MISSING, OmegaConf
from pprint import pprint

@dataclass
class Log:
    pass

@dataclass
class FileLog(Log):
    file : str = MISSING
    rotation: int = MISSING

@dataclass
class StreamLog(Log):
    stream_type: str = MISSING


@dataclass
class MyConfig:
    log : Log


cfg1 = OmegaConf.structured(MyConfig(log=StreamLog(stream_type="std")))
pprint(cfg1)
cfg2 = OmegaConf.structured(MyConfig(log=FileLog(file="a.log", rotation=2)))
pprint(cfg2)

```

**Describe the solution you'd like**
Is it also possible to initialize those via a yaml string (see example below)? Maybe not out of the box, but via a bit of workaround? 

```
s = """
log: !StreamLog
    file: a.log
    rotation: 3
"""
cfg3 = OmegaConf.create(s)
OmegaConf.merge(MyConfig, cfg3)
```

P.s.: https://github.com/omry/omegaconf/issues/456 seems related and maybe answers this question. But maybe things have changed 4 months later
P.P.s.: Maybe I'm also overthinking this and there is a easier solution for this use case

**Comment by omry** [comment]
1. You can serialize to pickle to get an accurate reproduction
2. You can use Hydra to compose the config automatically, it supports Structured Configs (https://hydra.cc).

**Comment by cgebbe** [comment]
thanks a lot for the quick comment
