### ISSUE TITLE
Error on subclassing Dict[Any, ...]

### ISSUE THREAD

**Issue by Jasha10** [omry/omegaconf#657]
Based on https://github.com/omry/omegaconf/pull/502#discussion_r605832350, it is proposed to deprecate support for structured configs that subclass `Dict[Any, ...]`, with only subclasses of `Dict[str, ...]` being supported going forward.

For example, creating a structured config node based on the following dataclass would issue a deprecation warning,

```python
@dataclass
class MyConf(Dict[int, Any]):
    ...
```

while a structured config node based on the following would be fully supported:

```python
@dataclass
class MyConf(Dict[str, Any]):
    ...
```

**Comment by omry** [comment]
> class MyConf(Dict[int, Any]) 

This is not supported in 2.0, we can just straight to error with it.

**Comment by omry** [comment]
I think the idea is that this is is a reminder for 2.2 to remove the deprecation warning from extending Dict and make it an error. (We can also just allow but completely ignore it).

**Comment by Jasha10** [comment]
I thought the idea was that subclassing `Dict[str, str]` is deprecated and subclassing `Dict[int, str]` or `Dict[Any, str]` should give an error message...

If you still want to go that route, I can try to get a PR ready tonight.

**Comment by omry** [comment]
Oh yeah, sorry.

**Comment by Jasha10** [comment]
Closing since we've already deprecated subclassing Dict in general.
