### ISSUE TITLE
Opaque ValidationError when calling OmegaConf.create() on dataclass

### ISSUE THREAD

**Issue by romesco** [omry/omegaconf#658]
**Describe the bug**
Calling `OmegaConf.create()` on a dataclass with defaults results in a `ValidationError` that does not specify the field that caused the error.
```bash
omegaconf.errors.ValidationError: Invalid value assigned : int is not a ListConfig, list or tuple.
    full_key:
    object_type=None
```
This makes debugging within large hierarchical structures challenging.

**To Reproduce**
```python
from typing import Tuple
from dataclasses import dataclass
from omegaconf import OmegaConf

@dataclass
class TopLvlConf:
    foo: Tuple[str] = 123

OmegaConf.create(TopLvlConf)
```

**Expected behavior**
The error would specify that the field `foo` is the culprit.

**Additional context**
- [x] OmegaConf version: 2.1.0.dev24
- [x] Python version: 3.8.6
- [x] Operating system: Ubuntu 16.04
- [x] Please provide a minimal repro

**Comment by omry** [comment]
Thanks for reporting, we will take a look.
