### ISSUE TITLE
Remove OmegaConf 2.0 deprecated APIs

### ISSUE THREAD

**Issue by omry** [omry/omegaconf#671]
`BaseContainer.{pretty,select,update_node}` have all been deprecated in OmegaConf 2.0 and should no longer be used.

**Comment by titu1994** [comment]
Hi Omry - just a note. According to Semver - https://semver.org/#how-should-i-handle-deprecating-functionality, OmegaConf 2.1 should not have dropped this, but the next major version (say 3.0) should have dropped it.

While these are semantic rules (by definition) and are not enforced explicitly - it helps keep maintain compatibility with dependent downstream libraries.

**Comment by omry** [comment]
semver is a recommendation and not something all projects in the world follows.
