### ISSUE TITLE
`OmegaConf.select()` with default value doesn't work with keys "", ".", "..", etc.

### ISSUE THREAD

**Issue by odelalleau** [omry/omegaconf#674]
**Describe the bug**

The following code runs without error, but the lines marked with `# !!!` should have failed:
```python
cfg = OmegaConf.create({"x": {}})

assert OmegaConf.select(cfg, "") is cfg
assert OmegaConf.select(cfg, "", default=0) == 0  # !!!

assert OmegaConf.select(cfg.x, ".") is cfg.x
assert OmegaConf.select(cfg.x, ".", default=0) == 0  # !!!

assert OmegaConf.select(cfg.x, "..") is cfg
assert OmegaConf.select(cfg.x, "..", default=0) == 0  # !!!
```

**Expected behavior**

The lines marked with `# !!!` should have instead returned the same object as the line just above.

**Additional context**

I haven't looked closely at it but I suspect this is caused by the `_last_key not in _root` check triggering the return of the default value.

**Comment by ppwwyyxx** [comment]
I encountered a similar issue:
```python
cfg = OmegaConf.create({"x": {}})

assert OmegaConf.select(cfg, "y", default=0) == 0  # works
assert OmegaConf.select(cfg, "y.z", default=0) == 0   # fails?
```

Not sure if the failure is expected or not. From a user's perspective it seems natural to allow the above usage.

**Comment by omry** [comment]
Smells like the same issue. What version is this against?

**Comment by ppwwyyxx** [comment]
I'm on `2.1.0dev22` from pypi
