### ISSUE TITLE
Possible edge case: interpolation to key containing a colon

### ISSUE THREAD

**Issue by Jasha10** [omry/omegaconf#680]
It is not uncommon to see config files that contain a value with a colon, e.g. `"<ip_address>:<port_number>"`. It is probably much less common to see a colon as part of a key in a config file. An edge case can arise when interpolating to a key that contains a colon, since OmegaConf uses colons for its resolver syntax.

Here is what will happen if you try to do this:

```python
$ cat tmp.py
from omegaconf import OmegaConf
cfg = OmegaConf.create({"fo:o": 123, "bar": "${fo:o}"})
print(cfg.bar)
```
```bash
$ python tmp.py
Traceback (most recent call last):
...
omegaconf.errors.UnsupportedInterpolationType: Unsupported interpolation type fo
    full_key: bar
    object_type=dict
```

If a resolver is registered with a name that equals the part of the key before the colon, you will get this behavior:

```python
$ cat tmp2.py
from omegaconf import OmegaConf
cfg = OmegaConf.create({"fo:o": 123, "bar": "${fo:o}"})
OmegaConf.register_new_resolver("fo", lambda x: 456)
print(cfg.bar)
```
```bash
$ python tmp2.py
456
```

I am posting this issue so that there will be documentation for this possible edge case.

**Comment by omry** [comment]
Nice catch.
In theory it's possible to support it by escaping the : "${fo\:o}" 
or by quoting the interpolation string: ${'fo:o'}.
None of those is working right now and I don't think it's an important enough use case.

OmegaConf never supported it and there have been no user reports about it.

**Comment by odelalleau** [comment]
In case someone runs into this issue, there are at least a few workarounds:
```python
# Workaround 1: create a variable to hold the key name
cfg = OmegaConf.create({"fo:o": 123, "bar": "${${bar_ref}}", "bar_ref": "fo:o"})

# Workaround 2: use `oc.decode` (@omry so actually it *is* useful with literal strings!)
cfg = OmegaConf.create({"fo:o": 123, "bar": "${${oc.decode:'fo:o'}}"})

# Workaround 3: use a "select" resolver to manually select arbitrary nodes (maybe later we'll have `oc.select`)
OmegaConf.register_new_resolver("select", lambda key, _parent_: OmegaConf.select(_parent_, key))
cfg = OmegaConf.create({"fo:o": 123, "bar": "${select:'fo:o'}"})
```

**Comment by omry** [comment]
I think #687 is addressing this.

**Comment by omry** [comment]
@Jasha10, if you agree - let's close this.

**Comment by Jasha10** [comment]
I am confused about how #687 is addressing this. After merging #687, the examples from the top of this issue still give the same output as before.

**Comment by omry** [comment]
It adds documentation.
https://omegaconf.readthedocs.io/en/latest/custom_resolvers.html#oc-select

**Comment by Jasha10** [comment]
Oh, got it :)
Ok, closing now.
