### ISSUE TITLE
support __delattr__

### ISSUE THREAD

**Issue by ppwwyyxx** [omry/omegaconf#682]
```python
from omegaconf import OmegaConf

a = OmegaConf.create()
a.b = {}
a.b["c"] = 1
del a.b["c"]   # works

a.b.c = 1
del a.b.c  # fails
```

**Describe the solution you'd like**
It seems counter-intuitive that this type of deletion is not supported.

**Comment by omry** [comment]
feel free to send a pull request to add it.
