### ISSUE TITLE
OmegaConf.select() crashes when selecting from a None container

### ISSUE THREAD

**Issue by odelalleau** [omry/omegaconf#685]
**Describe the bug**
```python
cfg = OmegaConf.create({"x": DictConfig(None)})
OmegaConf.select(cfg, "x.y")
```
triggers:
```
AttributeError: 'NoneType' object has no attribute 'get'
```

**Expected behavior**
`OmegaConf.select(cfg, "x.y")` should be `None`.

**Comment by omry** [comment]
Will fix this in #683. See my comment there for a related bug without OmegaConf.select.
