### ISSUE TITLE
`Omegaconf.to_container()` doesn't interpolate enum

### ISSUE THREAD

**Issue by syed-ahmed** [omry/omegaconf#691]
**Describe the bug**
When using `Omegaconf.to_container()`, it doesn't interpolate an enum instantiation.

**To Reproduce**
```Python
from enum import Enum
from omegaconf import OmegaConf

class RayAutoScalingMode(Enum):
    default = "default"
    aggressive = "aggressive"

d = {
    "autoscaling_mode": RayAutoScalingMode.default,
}

cfg = OmegaConf.create(d)
assert OmegaConf.to_container(cfg, resolve=True) == {
    "autoscaling_mode": "default",
}
```

**Expected behavior**
Currently it gives `'autoscaling_mode': <RayAutoScalingMode.default: 'default'>` in the above repro.
It should give `'autoscaling_mode': 'default'`

**Additional context**
- [x] OmegaConf version: <2.1.0.dev26 and master>
- [x] Python version: <3.8.8>
- [x] Operating system: <Ubuntu 20.04>
- [x] Please provide a minimal repro

**Comment by omry** [comment]
There are no interpolations in your bug report.

Expected behavior
> Currently it gives 'autoscaling_mode': <RayAutoScalingMode.default: 'default'> in the above repro.

So what is the expected behavior?

**Comment by syed-ahmed** [comment]
Ah I see your point about interpolation. May be it's not interpolation then. What's happening is `launcher.ray_cfg.cluster`, which is a ray config looks like this:
```
{'cluster_name': 'default', 'min_workers': 0, 'max_workers': 1, 'initial_workers': 0, 'autoscaling_mode': <RayAutoScalingMode.default: 'default'>, 'target_utilization_fraction': 0.8, 'idle_timeout_minutes': 5, 'docker': {'image': '', 'container_name': '', 'pull_before_run': True, 'run_options': []}, 'provider': {'type': 'aws', 'region': 'us-west-2', 'availability_zone': 'us-west-2a,us-west-2b', 'cache_stopped_nodes': False, 'key_pair': {'key_name': 'hydra-${oc.env:USER,user}'}}, 'auth': {'ssh_user': 'ubuntu'}, 'head_node': {'InstanceType': 'm5.large', 'ImageId': 'ami-008d8ed4bd7dc2485'}, 'worker_nodes': {'InstanceType': 'm5.large', 'ImageId': 'ami-008d8ed4bd7dc2485'}, 'file_mounts': {}, 'initialization_commands': [], 'setup_commands': ['conda create -n hydra_3.8.8 python=3.8.8 -y', 'echo \'export PATH="$HOME/anaconda3/envs/hydra_3.8.8/bin:$PATH"\' >> ~/.bashrc', 'pip install omegaconf==2.1.0dev26', 'pip install hydra_core==1.1.0dev4', 'pip install ray==1.3.0', 'pip install cloudpickle==1.6.0', 'pip install pickle5==0.0.11', 'pip install hydra_ray_launcher==1.1.0.dev1'], 'head_setup_commands': [], 'worker_setup_commands': [], 'head_start_ray_commands': ['ray stop', 'ulimit -n 65536;ray start --head --port=6379 --object-manager-port=8076             --autoscaling-config=~/ray_bootstrap_config.yaml'], 'worker_start_ray_commands': ['ray stop', 'ulimit -n 65536; ray start --address=$RAY_HEAD_IP:6379 --object-manager-port=8076']}
```
In the file created by
```
OmegaConf.save(
                    config=launcher.ray_cfg.cluster, f=file.name, resolve=True
                )
```
I can see `autoscaling_mode` gets resolved to the value `default` instead of staying `<RayAutoScalingMode.default: 'default'>`.

So I'm expecting the above repro to have the value `default`.

**Comment by omry** [comment]
Your report is a bit confused.
You didn't say anything about OmegaConf.save().

Maybe this is what you want?
```python
assert OmegaConf.to_container(cfg, resolve=True, enum_to_str=True) == {
    "autoscaling_mode": "default",
}
```

**Comment by omry** [comment]
If you debug into OmegaConf.save(), you would see that it's calling OmegaConf.to_yaml(), which in turn calls to_container with enum_to_str set to True.

https://github.com/omry/omegaconf/blob/master/omegaconf/omegaconf.py#L762

**Comment by syed-ahmed** [comment]
Aah thanks! Clearly I didn't dig enough. Closing this since this is not a bug.
