### ISSUE TITLE
Any chance to add option to check if there's duplicate arguments?

### ISSUE THREAD

**Issue by cyr0930** [omry/omegaconf#692]
I think there's a chance if we have too many argument, we can enter duplicate arguments by mistake.
Methods such as from_cli or from_dotlist doesn't check any duplicates.

I use this method as a workaround but since I'm not a heavy user, I don't know if this method has some side effects.

```python
from collections import Counter
def from_cli(args_list: Optional[List[str]] = None, check_duplicates: bool = False) -> DictConfig:
    if args_list is None:
        # Skip program name
        args_list = sys.argv[1:]
    if check_duplicates:
        duplicate_keys = tuple(k for k, v in Counter(x.split("=")[0] for x in args_list).items() if v > 1)
        if duplicate_keys:
            raise RuntimeError(f'some keys are entered more than once: {duplicate_keys}')
    return OmegaConf.from_dotlist(args_list)
```

Python argparse also has similar issue
https://stackoverflow.com/questions/30149851/python-argparse-how-to-detect-duplicated-optional-argument

**Comment by omry** [comment]
Hi,
The OmegaConf support for CLI is really minimal and is not an area of focus.
If you have that many arguments you should look at [Hydra](https://hydra.cc) and its config groups - which enables config composition without writing custom code.

As you pointed out, it's pretty easy to implement your own version of from_cli that will do what you want.
Side note: There are definitely cases where you would want the last instance of a key to win (which is the current behavior).

**Comment by cyr0930** [comment]
@omry Thanks. I never heard Hydra before. I'll try if it fits for my project.

**Comment by omry** [comment]
Sounds good @cyr0930, thanks.
