### ISSUE TITLE
Being able to get a set of all missing keys

### ISSUE THREAD

**Issue by Ohad31415** [omry/omegaconf#720]
Something I find myself use each time is a function that returns set of all missing keys so that if it's not empty by the end of the configuration setup I raise an error. 
This function consists of recursive calls to `OmegaConf.is_missing` and `OmegaConf.is_confg` and I think it would be helpful to include it under the library. 

The function implementation is something like this - 
```python
class OmegaConf:
    # ...
    @staticmethod
    def missing_keys(cfg: Container) -> Set[str]:
        missings = set()

        def gather(_cfg, prefix=""):
            for key in _cfg:
                if OmegaConf.is_missing(_cfg, key):
                    missings.add(f"{prefix}{key}")
                elif OmegaConf.is_config(_cfg[key]):
                    gather(_cfg[key], prefix=f"{prefix}{key}.")

        gather(cfg)
        return missings 
```

I've set a PR for this here https://github.com/omry/omegaconf/pull/719

**Comment by omry** [comment]
Thanks @Ohad31415.
This is something we can consider for OmegaConf 2.2 (which is pretty far away right now).
I am not planning to add any new features to OmegaConf 2.1.

I am going to hold off reviewing the PR until we start working on 2.1.

**Comment by Jasha10** [comment]
This functionality is similar to the proposed `throw_on_missing` keyword argument for `OmegaConf.to_container` (#501).

**Comment by Ohad31415** [comment]
> This functionality is similar to the proposed `throw_on_missing` keyword argument for `OmegaConf.to_container` (#501).

It's similar in the sense that they both report missing keys, however `throw_on_missing` doesn't give a list of the missing keys so that one get prompt that in an error.

**Comment by Jasha10** [comment]
Yes, that is correct -- the proposed `throw_on_missing` error message would only report the first missing key that is encountered.
