### ISSUE TITLE
Deprecation warning when merging structured configs inheriting from Dict

### ISSUE THREAD

**Issue by odelalleau** [omry/omegaconf#721]
*I am moving the discussion I started in https://github.com/omry/omegaconf/issues/663#issuecomment-844628488 into a new issue*

**Is your feature request related to a problem? Please describe.**

With OmegaConf 2.1.0.rc1 the following code raises a deprecation warning pointing to #663:
```python
@dataclass
class Config1(Dict[str, Any]):
   x: int = 0

@dataclass
class Config2(Dict[str, Any]):
   y: int = 0

cfg = OmegaConf.merge(Config1, Config2)
```

**Describe the solution you'd like**

Based on the migration instructions in #663, it would seem intuitive (to me for the following to be allowed):
```python
@dataclass
class Config1:
   x: int = 0

@dataclass
class Config2:
   y: int = 0

    
cfg = OmegaConf.structured(Config1)
with open_dict(cfg):
    cfg = OmegaConf.merge(cfg, Config2)
```

However, this currently fails with:
```bash
Traceback (most recent call last):
    ...
omegaconf.errors.ValidationError: Merge error: Config2 is not a subclass of Config1. value: {'y': 0}
    full_key:
    object_type=Config1
```

**Discussion**

Continuing the discussion started in #663:

> @odelalleau, you can merge a dict like config onto a Structured Config, or another Structured Config of the same type or of a subclass.

Hmm, right, so actually this is even more confusing than I thought. My example above indeed still works (with the deprecation warning) if only `Config2` inherits from `Dict` (it doesn't matter for `Config1`). I find this confusing because from an implementation point of view, the target is `Config1` (see [the code](https://github.com/omry/omegaconf/blob/a2e25ddc7aa34bf904ce6f111accc08f50557e58/omegaconf/omegaconf.py#L259))
And the resulting object type is `Config2` while I would have expected it to be `Config1`... 

Anyway, that's not a big deal, it's just a matter of merge semantics (I got it backwards), and as long as the user-facing behavior is consistent, the underlying implementation doesn't matter much. But even if I open the second config for writing instead:
```python
@dataclass
class Config1:
   x: int = 0

@dataclass
class Config2:
   y: int = 0

    
c1 = OmegaConf.structured(Config1)
c2 = OmegaConf.structured(Config2)
with open_dict(c2):    
    cfg = OmegaConf.merge(c1, c2)
```
I still run into the same `ValidationError`, so my problem remains.

On the question:

> What are you expecting the resulting underlying type to be?

I would say that if `OmegaConf.merge(Config1, Config2)` gives a config of type `Config2` when `Config2` inherits from `Config1`, then (assuming we can make it work) it should also be `Config2` when it doesn't inherit from `Config1`.

The merge semantics would thus be: "add into `Config2` the stuff found in `Config1`".

**Comment by Jasha10** [comment]
> Hmm, right, so actually this is even more confusing than I thought. My example above indeed still works (with the deprecation warning) if only `Config2` inherits from `Dict` (it doesn't matter for `Config1`). I find this confusing because from an implementation point of view, the target is `Config1` (see [the code](https://github.com/omry/omegaconf/blob/a2e25ddc7aa34bf904ce6f111accc08f50557e58/omegaconf/omegaconf.py#L259))
> And the resulting object type is `Config2` while I would have expected it to be `Config1`...

I think this is a bug; since `c1` is the target in `OmegaConf.merge(c1, c2)`, it should be required that `Config1` is a subclass of `Config2`, not the other way around. I've opened #724.

**Comment by Jasha10** [comment]
Also, I want to point out that once the above bug is resolved, it should be possible to do something like this:

```python
@dataclass
class Config1:
   x: int = 0

@dataclass
class Config2:
   y: int = 0

@dataclass
class Config3(Config1, Config2):
    pass

c1 = OmegaConf.structured(Config1)
c2 = OmegaConf.structured(Config2)
merged = OmegaConf.merge(Config3, c1, c2)
```

**Comment by odelalleau** [comment]
Thanks @Jasha10  -- I'll wait for the outcome of the discussion in #724 before giving more thought to my specific use case. I'm a bit ambivalent about your example: on one hand it makes the structure of the merge result explicit by defining `Config3`, but on the other hand it's probably going to confuse anyone who isn't familiar with the intricacies of Omegaconf merge mechanics. But if it works I'll be happy to use it :)

**Comment by omry** [comment]
> I think this is a bug; since c1 is the target in OmegaConf.merge(c1, c2), it should be required that Config1 is a subclass of Config2, not the other way around. I've opened #724.
> Or at least it should be possible to do OmegaConf.merge(c1, c2) in the case where Config1 is a subclass of Config2. Otherwise, if we require that Config2 is a subclass of Config1, then every field from c1 will be overwritten by a field from c2, so there is no point in doing the merge.

No.
We are promoting c1 the type of c1 to be c2 after the merge.
This is intentional behavior. After the merge the ref type remains the same but the object type is c2 similar to what would happen if you assign c2 to c1. the object type is c2 after that.

**Comment by odelalleau** [comment]
Closing since the approach from https://github.com/omry/omegaconf/issues/724#issuecomment-846277178 should make it possible to work around this issue.

**Comment by odelalleau** [comment]
> Closing since the approach from [#724 (comment)](https://github.com/omry/omegaconf/issues/724#issuecomment-846277178) should make it possible to work around this issue.

Actually I was a bit quick to hit the close button, I don't think this approach is fully satisfactory since we lose typing:
```python
@dataclass
class Config1:
   x: int = 0

@dataclass
class Config2:
   y: int = 0

    
cfg = OmegaConf.structured(Config1)
cfg2 = OmegaConf.structured(Config2)
with open_dict(cfg):
    cfg = OmegaConf.merge(cfg, OmegaConf.to_container(cfg2))
    
#cfg.x = "hello"  # ValidationError
cfg.y = "hello"  # allowed :(
```
=> I still believe it'd be worth having a better solution, so re-opening

(NB: we don't necessarily need to fix it in 2.1, since one can always stick to inheriting from `Dict` and silence the deprecation warning)

**Comment by Jasha10** [comment]
Though it's not elegant, creating a mutual subclass preserves typing:
```python
@dataclass
class Config3(Config1, Config2):
    pass

cfg1 = OmegaConf.structured(Config1)
cfg2 = OmegaConf.structured(Config2)
cfg = OmegaConf.merge(
    Config3, OmegaConf.to_container(cfg1), OmegaConf.to_container(cfg2)
)

# cfg.x = "hello"  # ValidationError
# cfg.y = "hello"  # ValidationError
```

**Comment by odelalleau** [comment]
> Though it's not elegant, creating a mutual subclass preserves typing:

Oooh thanks, that's a nice trick! I think I can live with it :)
