### ISSUE TITLE
List element selection in interpolation seems not to work

### ISSUE THREAD

**Issue by davidavdav** [omry/omegaconf#732]
**Describe the bug**
It seems like the interpolation of lists with `[]` is not always carried out. 

**To Reproduce**
```python
c = OmegaConf.create({'a': '${b[1]}', 'b': [0, 1, 2]})
c.a ## expected 1, but the result is '${b[1]}'
```
but
```python
c = OmegaConf.create({'a': '${b.1}', 'b': [0, 1, 2]})
c.a ## 1, as expected
```

**Expected behavior**
I expected `c.a` to evaluate via `c.b[1]` to 1, but it evaluated to `${b[1]}`.

**Additional context**
```python
c = OmegaConf.create({'a': '${b[1]}', 'b': [0, 1, 2]})
assert c.b[1] == 1
```

**Comment by Jasha10** [comment]
Hi @davidavdav, thanks for the report!

This is fixed in our recent release candidate, OmegaConf version 2.1.0.rc1. Please consider giving it a try :)
`pip install omegaconf==2.1.0.rc1 --upgrade`
