### ISSUE TITLE
Support partial merge

### ISSUE THREAD

**Issue by JSKenyon** [omry/omegaconf#756]
**Is your feature request related to a problem? Please describe.**
I am making use of dataclasses and `structured` to build a structured config. Part of the dataclass from which the structured configuration is built has to be generated dynamically (using `make_dataclass`) at run time. This means that sometimes users can end up specifying excess configuration. Currently, this will result in an error when I would prefer to be able to merge what I can and then log the excess config.

**Describe the solution you'd like**
In addition to `merge`, it would be useful if a `merge_known` existed. This would provide similar functionality to `argparse.parse_known_args`, returning one object with the merged configuration and a second with config that could not be merged. This would be particularly useful for `from_cli`, in the event that not all the arguments on the cli belong to a single config. 

**Describe alternatives you've considered**
I could likely go through each piece of configuration (multiple .yaml files and cli) and try and purge excess keys, but that doesn't appeal to me.  

**Additional context**
I am relatively new to OmegaConf, so if there is a better way to do this, I am all ears.

**Comment by omry** [comment]
In general, merge is very complex and I am not interested in doubling it's surface area by introducing a new variant.

Can you give an example snippet with your inputs and expected output?

**Comment by JSKenyon** [comment]
Here is a simplified (relative to my use-case) example of what I am doing:

```python
from dataclasses import dataclass, make_dataclass
from omegaconf import OmegaConf as oc
from typing import List


@dataclass
class BaseConfig:
    fields: List[str] = "???"


@dataclass
class Field:
    name: str = ""


def finalize_structure(user_config):

    fields = oc.select(user_config, "fields")

    FinalConfig = make_dataclass(
        "FinalConfig",
        [(f, Field, Field()) for f in fields],
        bases=(BaseConfig,)
    )

    return FinalConfig


if __name__ == "__main__":

    user_config = oc.from_dotlist(["fields=[field1,field2]",
                                   "field1.name=user1",
                                   "field2.name=user2"])

    FinalConfig = finalize_structure(user_config)

    config = oc.structured(FinalConfig)
    config = oc.merge(config, user_config)

    print(config)  # Works perfectly.

    user_config = oc.from_dotlist(["fields=[field1]",
                                   "field1.name=user1",
                                   "field2.name=user2"])

    FinalConfig = finalize_structure(user_config)

    config = oc.structured(FinalConfig)
    config = oc.merge(config, user_config)  # Error.

    print(config)
```
In the second case (the one which produces an error), a user has provided excess config i.e. they have specified only a single field but have provided config for a second field. I would really like the ability to do something like:
```python
    user_config = oc.from_dotlist(["fields=[field1]",
                                   "field1.name=user1",
                                   "field2.name=user2"])

    FinalConfig = finalize_structure(user_config)

    config = oc.structured(FinalConfig)
    merged, unmerged = oc.merge_known(config, user_config)
```
where `unmerged` is a `omegaconf.dictconfig.DictConfig` containing all the parameters which could not be merged. This is very useful in my opinion as it means that if a user wanted to disable a field (as in my example), they wouldn't have to delete every mention of it across all their configuration. Instead, one could merge where possible and log the unused config.

**Comment by omry** [comment]
Thanks for the additional context.
This is a very unusual usage of OmegaConf and is not  functionality I am interested in adding to OmegaConf.

One thing you can try is to merge the configs together as dicts without using the dataclass(es), and then sanitize the resulting config object from any extra fields, and finally merge the sanitized config on top of your schema dataclass.

**Comment by JSKenyon** [comment]
> One thing you can try is to merge the configs together as dicts without using the dataclass(es), and then sanitize the resulting config object from any extra fields, and finally merge the sanitized config on top of your schema dataclass.

This is likely the approach I will end up taking. Thanks for your swift responses.
