### ISSUE TITLE
PackageInfo: Invalid constraint (PyYAML (>=5.1.*)) found in omegaconf-2.1.0 dependencies, skipping

### ISSUE THREAD

**Issue by gygabyte017** [omry/omegaconf#758]
**Describe the bug**
When installing omegaconf with poetry command `poetry add omegaconf`, the follogin warning is issued:

    PackageInfo: Invalid constraint (PyYAML (>=5.1.*)) found in omegaconf-2.1.0 dependencies, skipping

**To Reproduce**
Just install the package in an empty environment.

**Expected behavior**
To correctly get and install the pyyaml dependency.

**Additional context**
- [X] OmegaConf version: 2.1.0
- [X] Python version: 3.8
- [X] Operating system: Windows
- [ ] Please provide a minimal repro

**Comment by omry** [comment]
Why is this an invalid constraints? pip likes it just fine.

**Comment by gygabyte017** [comment]
I'm not sure it is invalid, if with pip is ok I'll open an issue in poetry repo about it and let you know.

**Comment by omry** [comment]
I didn't hear or see any reports about it causing issues for anyone else.
This seems in line with https://www.python.org/dev/peps/pep-0440/ 

In particular, release segment below:
```
Public version identifiers are separated into up to five segments:

Epoch segment: N!
Release segment: N(.N)*
Pre-release segment: {a|b|rc}N
Post-release segment: .postN
Development release segment: .devN
```

**Comment by gygabyte017** [comment]
They say `>=5.1.*` is not a valid PEP440. (Issue: https://github.com/python-poetry/poetry/issues/4206 and linked issues)

In fact reading PEP440 I see that the `*` is accepted only with `==` or with `!=` and not with `>=`; moreover `==5.1.*` is equivalent to `>=5.1.0` but `>=5.1.*` is invalid.

What do you think?

**Comment by omry** [comment]
Thanks. Sounds fine.
Go ahead and send a PR fixing it to `>=5.1` or `>=5.1.0`.

**Comment by gygabyte017** [comment]
Opened PR #761

**Comment by ZetiMente** [comment]
@omry Hi, I just started using OmegaConf and ran into this error. It appears to be fixed now. PR #761. Is there any chance of a new release soon? I'm very excited to be using OmegaConf because it's making my newest ML project awesome. However, this error prevents it from working in Google Colab.

**Comment by omry** [comment]
@Jasha10, do you want to try to release 2.1.1 with this fix?

**Comment by Jasha10** [comment]
Sure, I'll give it a try!
