### ISSUE TITLE
ConfigKeyError ist not called and dict assignment freezes

### ISSUE THREAD

**Issue by brunovollmer** [omry/omegaconf#779]
**Describe the bug**
I have this very strange error that I don't know how to fix and I was wondering if somebody knows what to do about this. I have this config manager that is shared between multiple processes, which looks through a OmegaConf dict config to see if it can find the wanted value.

```
 @Singleton
  class Config:
    def initialize(self, cfg):
        if hasattr(self, '_cfg'):
            logger.warning("config overwritten")

        self._cfg = cfg
        logger.info("config initialized")
        logger.debug(cfg)
        self._lock = Lock()

    def get(self, *args):
        self._lock.acquire()

        if len(args) == 0:
            raise ValueError("at least one key is needed")

        # try to find value in overrides
        # if it does not exists check in "regular" config
        cfg = None

        try:
            cfg = self._cfg['overrides']
            for key in args:
                cfg = cfg[key]
        except (ConfigKeyError, KeyError) as e:
            print(e)
            cfg = self._cfg

            for key in args:
                print(cfg)
                cfg = cfg[key]
        finally:
            self._lock.release()
```
At one point in the project the calling process freezes in the try part where `cfg = cfg[key]`. The could should theoretically throw a key error and then look in the normal config but for whatever reason it just freezes.

Now the strange part comes. As part of my debugging I included some code to get the caller of the function (to rule out some edge cases) and whenever I add the following four lines behind the if at the beginning it runs flawless.

```
curframe = inspect.currentframe()
calframe = inspect.getouterframes(curframe, 2)
print('caller name:', calframe[1][3])
print(os.getpid(), args)
```
Does anybody have any idea what to look for or why this happens?

**Expected behavior**

No freeze and an exception raised.

**Additional context**
- [x] OmegaConf version: 2.1.0rc1
- [x] Python version: 3.8
- [x] Operating system: Ubuntu 20.04

**Comment by omry** [comment]
1. Can you use the latest released version?
2. Can you convert your example into a minimal runnable file that reproduces the problem?

Thanks.

**Comment by omry** [comment]
Taking a step back, the logic you are implementing seems weird. Wouldn't it be better to use OmegaConf.merge to combine the two configs and have a single config object you need to query instead of having this entire thing?

**Comment by Jasha10** [comment]
In the case where no error occurs, I think that the for-loop logic is equivalent to
`cfg = cfg[arg1][arg2]...[argN]` where `args == (arg1, arg2, ..., argN)`.
I don't understand how a call to `OmegaConf.merge` would be helpful here...

@brunovollmer, which lock are you using: `multithreading.Lock` or `multiprocessing.Lock`? I worry that `self._cfg` and `self._lock` could get overwritten while the `Config.get` method is running, e.g. if `Config.initialize` gets called at the same time as `Config.get`.

As Omry said, a minimal runnable file (or collection of files) would be very helpful.

**Comment by omry** [comment]
> In the case where no error occurs, I think that the for-loop logic is equivalent to
cfg = cfg[arg1][arg2]...[argN] where args == (arg1, arg2, ..., argN).
I don't understand how a call to OmegaConf.merge would be helpful here...

It would be helpful to eliminate the need to check one config and if a key is not there check another.

**Comment by brunovollmer** [comment]
Hey @omry and @Jasha10 ,

I've installed the newest versions of hydra and omegaconf. Problem still occurs. I'm currently working on a minimal example but one thing I noticed is that the previously mentioned fix only works when using `hydra.verbose=true` as command line argument. I'm very confused at the moment why this fixes it.

Will supply the minimal example soon!

**Comment by brunovollmer** [comment]
So I've fixed it but I can only guess why `hydra.verbose=true` and the `inspect` commands have had something to do with the earlier "fix". So the actual fix was that, as @Jasha10 suggested, the lock was not working for multiple processes. Now I have a "working" lock for all processes and the code works fine. I think the other things fixed it because the access was a bit slower or something and thus the problem of accessing the same resource at the same time did not occur.

Thanks for your help guys!

**Comment by brunovollmer** [comment]
Okay so with a fixed lock (thanks to the idea from @Jasha10 ) now I don't need the inspect code but it still only works if I add `hydra.verbose=true`.

**Comment by omry** [comment]
Please be aware that in general OmegaConf is NOT thread safe.
If you are consuming the config from multiple threads it's highly recommended that you deepcopy such that each thread gets it's own copy.

**Comment by Jasha10** [comment]
@brunovollmer can this issue be closed now?

**Comment by brunovollmer** [comment]
Still can't explain why `hydra.verbose=True` fixes the problem but we moved to use the [multi-processing dict](https://docs.python.org/3/library/multiprocessing.html) and that seems to solve the problem. Sorry for waiting this long with the answer.
