### ISSUE TITLE
Bumping antlr dependency to 4.9.2 (from 4.8)

### ISSUE THREAD

**Issue by suchenzang** [omry/omegaconf#798]
A project that would like to use omegaconf has some hard dependencies on antlr 4.9 in the existing build system. Would like to bump dependency here as well to integrate with existing system.

**Comment by omry** [comment]
The compiler is included with the repo (https://github.com/omry/omegaconf/tree/master/build_helpers/bin).
However this may be tricky with fbcode (It has 4.8 and if we will be required to upgrade there as well it will be hard).
Also, Hydra's antlr version must match.

**Comment by hmaarrfk** [comment]
Fundamentally speaking, is the code compatible with both? if we are rolling our own ecosystem, should we be able to change the dependencies ourselves?

The issue seems to be that `pip check` fails when we have 4.9 installed:

https://github.com/conda-forge/omegaconf-feedstock/pull/25
