### ISSUE TITLE
Merge nested dictionaries with missing values

### ISSUE THREAD

**Issue by fuhuifang** [omry/omegaconf#818]
**Describe the bug**
I want to merge two dictionaries
`OmegaConf.merge({"a": 0, "b": {"d": 0}, "c": 1}, {"a": 1, "b": MISSING, "c": MISSING})`
expected output is `{"a": 1, "b": {"d": 0}, "c": 1}`
where
1. Missing values in the second dict will not override, e.g. "c"
2. Nested dicts are updated, e.g. `"b": MISSING` -> `"b": {"d": 0}`
Are these supported?

**To Reproduce**
Please provide a minimal repro.
This can include a small Python file, and potentially a few small config files.
If you have more than one file you can attach a zip file with everything to the issue.

**Expected behavior**

**Additional context**
- [ ] OmegaConf version: <__FILL__>
- [ ] Python version: <__FILL__>
- [ ] Operating system: <__FILL__>
- [ ] Please provide a minimal repro

**Comment by Jasha10** [comment]
```python
>>> OmegaConf.merge({"a": 0, "b": {"d": 0}, "c": 1}, {"a": 1, "b": MISSING, "c": MISSING})
{'a': 1, 'b': {'d': 0}, 'c': 1}
```

This seems to match your expected output precisely.

**Comment by fuhuifang** [comment]
Yes upgrading omegaconf to 2.1 fixes the issue.
