### ISSUE TITLE
OmegaConf object doesn't support a .copy method

### ISSUE THREAD

**Issue by mannatsingh** [omry/omegaconf#82]
A dict is supposed to have a .copy() method (https://docs.python.org/3/library/stdtypes.html#dict.copy). For an OmegaConf object to be compatible with a dict's API, it should also support the copy() method -

```
>>> from omegaconf import OmegaConf
>>> conf = OmegaConf.create({"a": 2, "b": [1,2,3]})
>>> conf
{'a': 2, 'b': [1, 2, 3]}
>>> conf.copy()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: 'NoneType' object is not callable
```

**Comment by omry** [comment]
Thanks for reporting.
For now please use:

```python
from omegaconf import OmegaConf
import copy
conf = OmegaConf.create({"a": 2, "b": [1,2,3]})
conf2 = copy.deepcopy(conf)
```

I will look into implementing shallow copy as conf.copy() but it may not be trivial, the only support copy right now is deep copy.
