### ISSUE TITLE
Missing import in docs

### ISSUE THREAD

**Issue by astariul** [omry/omegaconf#833]
In the following page of the docs : https://omegaconf.readthedocs.io/en/2.0_branch/structured_config.html?highlight=field#lists

There is this code snippet : 

```
>>> from typing import List, Tuple
>>> @dataclass
... class User:
...     name: str = MISSING

>>> @dataclass
... class Lists:
...     # Typed list can hold Any, int, float, bool, str and Enums as well
...     # as arbitrary Structured configs
...     ints: List[int] = field(default_factory=lambda: [10, 20, 30])
...     bools: Tuple[bool, bool] = field(default_factory=lambda: (True, False))
...     users: List[User] = field(default_factory=lambda: [User(name="omry")])
```

But if I run this code, I have the error : `ImportError: cannot import name 'field' from 'typing'`

I don't know how I should import `field`...

**Comment by Jasha10** [comment]
`from dataclasses import field`

**Comment by Jasha10** [comment]
Thanks @astariul
