### ISSUE TITLE
Installing from sources 

### ISSUE THREAD

**Issue by bstaber** [omry/omegaconf#839]
**Describe the bug**
Hello,
I'm trying to install omegaconf from sources on a cluster without internet access. When I run the installation, I get the following message: `error: can't copy 'omegaconf.egg-info/PKG-INFO': doesn't exist or not a regular file`. 

I'm wondering if I should change something in the `setup.py` file.

Note: I'm not a root user.

**To Reproduce**
Download the sources (https://pypi.org/project/omegaconf/#files), extract files then run `python3 setup.py install --prefix=$PREFIX`

Thanks for your help.

**Comment by Jasha10** [comment]
Thanks for reporting @bstaber. We will look into this.

**Comment by Jasha10** [comment]
@bstaber a workaround is to use `pip install .` instead of running `setup.py` directly:
```text
$ wget https://files.pythonhosted.org/packages/91/80/c9268fedb0d63ddf7dfa4352070f8cfecf2b0443df7737462c3ab0437c11/omegaconf-2.1.1.tar.gz
...
$ tar -xzf omegaconf-2.1.1.tar.gz
$ cd omegaconf-2.1.1/
$ pip install .
...
```
Cross-link: #772.

**Comment by omry** [comment]
Closing as the solution is to use pip and not setup.py.
