### ISSUE TITLE
Resolving nested structured config with interpolation raises ValidationError

### ISSUE THREAD

**Issue by Messlow** [omry/omegaconf#847]
## Describe the bug

When using interpolation on Structured Config, resolving the object is raising a validation error:

```python
from omegaconf import OmegaConf, MISSING, II
from dataclasses import dataclass


@dataclass
class User:
    name: str = MISSING


@dataclass
class Config:
    user: User = User("John")
    admin: User = II("user")


cfg: Config = OmegaConf.structured(Config)
OmegaConf.resolve(cfg)
```

This raises the following error:
```
omegaconf.errors.ValidationError: Invalid type assigned: dict is not a subclass of User. value: {'name': 'John'}
```

## Expected behavior
Resolving the object should work as intended, by passing the User object instead of a dictionary.

**Comment by Jasha10** [comment]
Thanks for reporting this, @Messlow!
I can reproduce the bug.

**Comment by subhankar-ghosh** [comment]
I am also facing the same issue, any updates on how to solve this issue?

**Comment by Jasha10** [comment]
Thanks for the nudge @subhankar-ghosh. I've just opened PR #902 which should resolve this issue.
