### ISSUE TITLE
Would you please consider contructing omegaconf in a object-oriented way?

### ISSUE THREAD

**Issue by songyuc** [omry/omegaconf#921]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is.

**Describe the solution you'd like**
Please consider contructing omegaconf in a object-oriented way, such as,
```python
dict_config = DictConfig("cfg.yaml")
```

**Describe alternatives you've considered**

**Additional context**

**Comment by Jasha10** [comment]
@songyuc the official API for constructing OmegaConf objects is through the `omegaconf.OmegaConf` class:

```python
from omegaconf import OmegaConf, DictConfig
dict_config: DictConfig = OmegaConf.load("cfg.yaml")
```

**Comment by songyuc** [comment]
> @songyuc the official API for constructing OmegaConf objects is through the `omegaconf.OmegaConf` facade:
> 
> ```python
> from omegaconf import OmegaConf, DictConfig
> dict_config: DictConfig = OmegaConf.load("cfg.yaml")
> ```

I think this pattern might not be appropriate for inheritance programming, such as:
```python
class ExpConfig(DictConfig):
	...
```

**Comment by Jasha10** [comment]
Currently the `DictConfig.__init__` function works like this:
```python
cfg = DictConfig({"foo": "bar"})
assert cfg == {"foo": "bar"}
```
This is not documented and should not be considered a stable API.
You could load a yaml file like this: `DictConfig(yaml.safe_load(open("cfg.yaml")))`.

I would be curious to learn more about your use-case. Why do you want to subclass `DictConfig`? Are you adding some new methods?

**Comment by songyuc** [comment]
> Currently the `DictConfig.__init__` method works like this:
> 
> ```python
> cfg = DictConfig({"foo": "bar"})
> assert isinstance(cfg, DictConfig)
> assert cfg == {"foo": "bar"}
> ```
> 
> This is not documented and should not be considered a stable API. You could load a yaml file like this: `DictConfig(yaml.safe_load(open("cfg.yaml")))`.
> 
> I would be curious to learn more about your use-case. Why do you want to subclass `DictConfig`? Are you adding some new methods?

Yes, I may add some new methods and some custom attributes, like:
```python
class ExpConfig(DictConfig):
	def __init__(yaml):
		super().__init__(yaml)
		self.date = self.get_curr_date_time
```

**Comment by Jasha10** [comment]
> ```python
> class ExpConfig(DictConfig):
> 	...
> ```

Got it.
One downside of inheriting from `DictConfig` is that parts of OmegaConf's implementation are tightly coupled to the `DictConfig` class. For example, calling [`OmegaConf.merge`](https://omegaconf.readthedocs.io/en/latest/usage.html#omegaconf-merge) on `ExpConfig` will not work.

I wonder: would [custom-resolvers](https://omegaconf.readthedocs.io/en/latest/custom_resolvers.html) would work for your use-case?

```python
# tmp.py
from datetime import datetime

from omegaconf import OmegaConf

experiment_data = """\
datum1: 123
datum2: 456
"""

base_conf = {
    "date": "${get_curr_date_time:}",
    "other_custom_field": "...",
}

OmegaConf.register_new_resolver(
    "get_curr_date_time", lambda: datetime.now().isoformat()
)

cfg = OmegaConf.merge(base_conf, OmegaConf.create(experiment_data))
print(cfg.datum1)
print(cfg.date)
```
```text
$ python tmp.py
123
2022-05-16T05:27:39.668795
```

**Comment by songyuc** [comment]
> > ```python
> > class ExpConfig(DictConfig):
> > 	...
> > ```
> 
> Got it. One downside of inheriting from `DictConfig` is that parts of OmegaConf's implementation are tightly coupled to the `DictConfig` class. For example, calling [`OmegaConf.merge`](https://omegaconf.readthedocs.io/en/latest/usage.html#omegaconf-merge) on `ExpConfig` will not work.
> 
> I wonder: would [custom-resolvers](https://omegaconf.readthedocs.io/en/latest/custom_resolvers.html) would work for your use-case?
> 
> ```python
> # tmp.py
> from datetime import datetime
> 
> from omegaconf import OmegaConf
> 
> experiment_data = """\
> datum1: 123
> datum2: 456
> """
> 
> base_conf = {
>     "date": "${get_curr_date_time:}",
>     "other_custom_field": "...",
> }
> 
> OmegaConf.register_new_resolver(
>     "get_curr_date_time", lambda: datetime.now().isoformat()
> )
> 
> cfg = OmegaConf.merge(base_conf, OmegaConf.create(experiment_data))
> print(cfg.datum1)
> print(cfg.date)
> ```
> 
> ```
> $ python tmp.py
> 123
> 2022-05-16T05:27:39.668795
> ```

That looks like a good solution.
I will also try to adopt a factory pattern to realize this inheritance programming.

**Comment by songyuc** [comment]
I implement a custom configuration class as:
```python
class Config(DictConfig):
    def __init__(self, yaml_path, dict_exp_var=None, qa=QualityAssuranceBase(__file__)):
        super(Config, self).__init__({"Dataset": "None"})  # input an empty dict to init as, DictConfig({})
        # Read model config information
        conf = OmegaConf.load(yaml_path)
        print("before update()")
        self.update(conf)
        pass # Debug here
```
But when I use the debug of PyCharm, I meet an error as:
> Error evaluating: thread_id: pid_52995_id_140371051443776
frame_id: 140366443871296
scope: FRAME
attrs: self
Traceback (most recent call last):
  File "/home/user/software/python/anaconda/anaconda3/envs/conda-general/lib/python3.10/site-packages/omegaconf/dictconfig.py", line 351, in __getattr__
    return self._get_impl(key=key, default_value=_DEFAULT_MARKER_)
  File "/home/user/software/python/anaconda/anaconda3/envs/conda-general/lib/python3.10/site-packages/omegaconf/dictconfig.py", line 438, in _get_impl
    node = self._get_node(key=key, throw_on_missing_key=True)
  File "/home/user/software/python/anaconda/anaconda3/envs/conda-general/lib/python3.10/site-packages/omegaconf/dictconfig.py", line 470, in _get_node
    raise ConfigKeyError(f"Missing key {key}")
omegaconf.errors.ConfigKeyError: Missing key yaml_path

So, how can I resolve this error, and debug my custom class with debug of PyCharm?

**Comment by Jasha10** [comment]
>  File "/home/user/software/python/anaconda/anaconda3/envs/conda-general/lib/python3.10/site-packages/omegaconf/dictconfig.py", line 351, in `__getattr__`

It looks like `DictConfig.__getattr__` is being called with the key `"yaml_path"`.
This fails because the `"yaml_path"` key is not present in the config object.

A few questions that might be relevant for debugging:
- Do you get the same error if you use a factory pattern instead of using class inheritance?
- are you using the [OmegaConf PyDev.Debugger plugin](https://omegaconf.readthedocs.io/en/latest/usage.html#debugger-integration) to integrate with pycharm? It's source code is [here](https://github.com/omry/omegaconf/blob/master/pydevd_plugins/extensions/pydevd_plugin_omegaconf.py).

**Comment by songyuc** [comment]
> > File "/home/user/software/python/anaconda/anaconda3/envs/conda-general/lib/python3.10/site-packages/omegaconf/dictconfig.py", line 351, in `__getattr__`
> 
> It looks like `DictConfig.__getattr__` is being called with the key `"yaml_path"`. This fails because the `"yaml_path"` key is not present in the config object.
> 
> A few questions that might be relevant for debugging:
> 
> * Do you get the same error if you use a factory pattern instead of using class inheritance?
> * are you using the [OmegaConf PyDev.Debugger plugin](https://omegaconf.readthedocs.io/en/latest/usage.html#debugger-integration) to integrate with pycharm? It's source code is [here](https://github.com/omry/omegaconf/blob/master/pydevd_plugins/extensions/pydevd_plugin_omegaconf.py).

Thanks for the response. I find this error would appear only in the `Config` constructor function.
