### ISSUE TITLE
ENV support without additional wrappers

### ISSUE THREAD

**Issue by PerchunPak** [omry/omegaconf#957]
Reopen of #938, because I there is no button `reopen`.
![image](https://user-images.githubusercontent.com/68118654/171055065-7ac72495-defa-4bbc-9c1e-30175124c14f.png)

---

**Is your feature request related to a problem? Please describe.**
I want use human-readable config, without additional wrappers. Instead I need to wrap every option to `${oc.env:KEY,default_value}` and its looks ugly:
```yaml
token: ${oc.env:TOKEN,???}
locale: ${oc.env:LOCALE,en}
debug: ${oc.env:DEBUG,false}
verbose: ${oc.env:VERBOSE,false}
db_url: ${oc.env:DB_URL,sqlite:///data.db}
```
I want just:
```yaml
token: ???
locale: en
debug: false
verbose: false
db_url: sqlite:///data.db
```
Provide every option also with ENV variable can be helpful, example, for docker when the best will be just add arguments to `docker run` instead of add volumes and etc.

**Describe the solution you'd like**
Something like `overwrite_with_env` argument on `OmegaConf.create` and `OmegaConf.load` methods.

So this will just wrap every option to `"$\{oc.env:{0},{1}\}".format(key.upper(), value)` on parsing time.

**Describe alternatives you've considered**
Monkey patch as workaround, but this isn't good working, and produce additional bugs.

**Additional context**
[`python-decouple`](https://pypi.org/project/python-decouple/) provide support for ENV overwriting from box, but their architecture, in all cases, different from your.

---

I implement https://github.com/omry/omegaconf/issues/938#issuecomment-1138626501, but in some time noticed that this don't work if one of values `???` (https://github.com/omry/omegaconf/issues/938#issuecomment-1140508996).

**Comment by Jasha10** [comment]
Sorry my original solution did not handle missing values properly. Please give this a try:

```python
import os
from omegaconf import OmegaConf

cfg = OmegaConf.create(...)
for key in cfg:
    if key in os.environ:
        cfg[key] = os.environ[key]  # overwrite with environment var
```

**Comment by PerchunPak** [comment]
Working, thanks again. Really don't know why I didn't think about this.
