### ISSUE TITLE
Heterogenous tuple in structured

### ISSUE THREAD

**Issue by bottler** [omry/omegaconf#967]
In version 2.2.2, `Tuple` behaves strangely, whereas it did not in 2.1.

**To Reproduce**
This code fails with `Value 'four' of type 'str' could not be converted to Integer` 
```python
from dataclasses import dataclass
from omegaconf import OmegaConf
from typing import Tuple

@dataclass
class A:
    v: Tuple[int, str] = (34, "four")

OmegaConf.structured(A)
```

**Expected behavior**
`structured` should work in this case, as it does in previous versions of omegaconf.

**Additional context**
- OmegaConf version: 2.2.2
- Python version: 3.8
- Operating system: Linux

**Comment by Jasha10** [comment]
When I run your example with OmegaConf v2.1.2, I get the same behavior as with v2.2.2: both versions produce a `ValidationError`.

OmegaConf's support for Tuples is undocumented and incomplete. Currently, OmegaConf treats `Tuple[int, str]` as being equivalent to `List[int]`. This is why you're getting the message `Value 'four' of type 'str' could not be converted to Integer`
I'm going to close this issue in favor of https://github.com/omry/omegaconf/issues/392.
