### ISSUE TITLE
[Feature Request] detect unused parameters

### ISSUE THREAD

**Issue by terrykong** [omry/omegaconf#98]
Reposting from hydra https://github.com/facebookresearch/hydra/issues/323

For fairly large configs, it would be nice to be able to detect unused parameters to be able to help find stale parameters and prevent silent failures when a parameter was thought to be used, but wasn't.

Building on the example in the docs, it would be nice to do the following
```python
>>> conf = OmegaConf.create(dict(k='v',list=[1,dict(a='1',b='2')]))
>>> print(conf.pretty())
k: v
list:
- 1
- a: '1'
  b: '2'
>>> used_param = conf.list[0]
>>> conf.print_unused_params()
k: v
list:
- a: '1'
  b: '2'
>>> conf.list.print_unused_params()
- a: '1'
  b: '2'
```

**Comment by omry** [comment]
Hi @terrykong,
Thanks for the feature request.
While this is possible - I think this functionality does not justify the overhead of maintaining a usage flag per node and additional complexity.
Given the lack of significant interest in this feature by other users, I am going to close this.

**Comment by terrykong** [comment]
@omry No worries, makes sense 👍
